### ISSUE TITLE
WSL Setup Screens

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#102]
Since subiquity is also used in the WSL setup wizard and the UI design is similar it makes sense to host is as part of the installer, as another binary maybe though?

The design for those pages is on https://people.canonical.com/~platform/desktop/installer/WSL

**Comment by kenvandine** [comment]
I'd be in favor of a different binary.  Perhaps we could treat the future oem-config the same way?

**Comment by seb128** [comment]
@jibel opened issues for the individual screens now so let's close this one
