### ISSUE TITLE
Update split_view post 3.2.0 once published

### ISSUE THREAD

**Issue by CarlosNihelton** [canonical/ubuntu-desktop-installer#1031]
Per issue https://github.com/toshiaki-h/split_view/issues/19 , split_view version 3.2.0 was temoprarily removed from `pub.dev`.

PR #1030 was created to temporarily revert back to JP's branch until upstream is settled.

A new PR closing this must be issued as soon as a new version is published in `pub.dev`.

**Comment by jpnurmi** [comment]
I've pushed a fix proposal: https://github.com/toshiaki-h/split_view/pull/20
