### ISSUE TITLE
Keyboard not set according 'Keyboard layout' screen

### ISSUE THREAD

**Issue by corradoventu** [canonical/ubuntu-desktop-installer#1054]
Installing Kinetic from standard ISO I select 'English language' in the 'Welcome' screen and 'Italian' in the 'Keyboard layout' screen then the Italian keyboard is automatically set also in the top bar system properties.

Installing from canary ISO the Italian keyboard is NOT set in the top bar system properties and I'm forced to add a keyboard using Settings>Keyboard and then change in the top bar system properties.

**Comment by bittin** [comment]
this is still broken today, for Swedish keyboard in todays 20220813 image

**Comment by bittin** [comment]
> this is still broken today, for Swedish keyboard in todays 20220813 image

still broken with the 20220815 image

**Comment by bittin** [comment]
ah i see that @jpnurmi started working on fixing this

**Comment by jpnurmi** [comment]
Yes, I'm actively working on this. The situation is already better but not yet perfect with the latest candidate.

**Comment by jpnurmi** [comment]
https://github.com/canonical/subiquity/pull/1388

**Comment by bittin** [comment]
Still broken in the 20220823 build, works in the timezone chooser but not in the keyboard chooser

**Comment by bittin** [comment]
and still not fixed in 20220824

**Comment by jpnurmi** [comment]
All related changes have finally reached the stable channel in 20220825:
- https://github.com/canonical/subiquity/pull/1388
- https://github.com/canonical/ubuntu-desktop-installer/pull/1082
- https://github.com/canonical/ubuntu-desktop-installer/pull/1058

**Comment by bittin** [comment]
works here too, just tested with the 20220825.5 image
