### ISSUE TITLE
Telemetry report is written too late

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1057]
The GUI writes `/var/log/installer/telemetry` when the installation is finished and the user presses _Restart_ or _Shutdown_, which is too late for either:
- `subiquity/Late/run` that executes post-install scripts in `/etc/subiquity/postinst.d`, or
- `subiquity/Shutdown/copy_logs_to_target` that copies `/var/log/installer` to `/target`.

What makes this complicated is that the telemetry report is supposed to contain a timestamp for when the installation was finished. At this point, it's too late for the GUI to write anything. Therefore, it may be necessary to have some help from Subiquity.

**Comment by jpnurmi** [comment]
We have a plan. We'll write all steps up until the installation start from the GUI and finish up the report from a Subiquity post-install script.

GUI:
```json
{
  "Language": "en",
  "Minimal": false,
  "RestrictedAddons": false,
  "PartitionMethod": "use_device",
  "Type": "Flutter",
  "OEM": false,
  "Stages": {
    "0": "/welcome",
    "35": "/tryorinstall",
    "38": "/keyboardlayout",
    "39": "/updateothersoftware",
    "40": "/installationtype",
    "42": "/whereareyou",
    "44": "/whoareyou",
    "48": "/chooseyourlook",
    "49": "/installationslides",
    "80": "/installationcomplete"
  }
}
```

post-install script:
```json
{
  "Language": "en",
  "Minimal": false,
  "RestrictedAddons": false,
  "PartitionMethod": "use_device",
  "Type": "Flutter",
  "OEM": false,
  "Stages": {
    "0": "/welcome",
    "35": "/tryorinstall",
    "38": "/keyboardlayout",
    "39": "/updateothersoftware",
    "40": "/installationtype",
    "42": "/whereareyou",
    "44": "/whoareyou",
    "48": "/chooseyourlook",
    "49": "/installationslides",
    "80": "/installationcomplete",
    "123": "done"
  }
}
```

**Comment by jpnurmi** [comment]
Ubiquity's telemetry report for comparison:
```json
{
  "Media": "Ubuntu 22.04 LTS \"Jammy Jellyfish\" - Release amd64 (20220419)",
  "Type": "GTK",
  "OEM": false,
  "PartitionMethod": "use_crypto",
  "DownloadUpdates": true,
  "Language": "en",
  "Minimal": false,
  "RestrictedAddons": true,
  "Stages": {
    "0": "language",
    "27": "console_setup",
    "90": "console_setup",
    "92": "wireless",
    "124": "prepare",
    "174": "partman",
    "208": "partman",
    "333": "start_install",
    "368": "timezone",
    "374": "usersetup",
    "415": "user_done",
    "668": "done"
  }
}
```

Notes:
- ours is missing the "Media" entry
- we could probably leave out the leading "/" from route names

**Comment by mwhudson** [comment]
FWIW I would sort of like this sort of thing for server too but there is no kind of plan on how to make that happen as yet. So maybe this can move into subiquity in like 5 years or so :)
