### ISSUE TITLE
Broken image 16th August 2022

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#1068]
Hey!

Yesterdays Canary image did not install for me
![VirtualBox_Ubuntu 220816](https://user-images.githubusercontent.com/43197/185055114-97a28457-337f-4263-91cf-497a5fd673ed.png)

**Comment by bittin** [comment]
Still broken with todays 20220817 canary, but in another way
![VirtualBox_Ubuntu 2217](https://user-images.githubusercontent.com/43197/185089619-3bd858c7-5675-44c7-a7ff-2f13b82b4fe1.png) my VM has 30GB disk space

**Comment by jpnurmi** [comment]
Progress. :) Jokes aside, we noticed the same earlier. A [fix](https://github.com/canonical/subiquity/pull/1382) has been prepared that will be included in the next Subiquity [update](https://github.com/canonical/ubuntu-desktop-installer/pull/1067).

**Comment by jpnurmi** [comment]
It may actually help to try to close and reopen the installer window, could you try that?

**Comment by bittin** [comment]
Tested and works again with the 20220822 iso https://cdimage.ubuntu.com/daily-canary/20220822/ so closing this issue
