### ISSUE TITLE
[WSL] Option for deferring language pack installation

### ISSUE THREAD

**Issue by CarlosNihelton** [canonical/ubuntu-desktop-installer#1073]
A considerable amount of time of the WSL setup workflow in spent running apt to download and install language packs and fonts to ensure a good language support. The amount of time depends on which language is selected.

To make things worse, WSL 2 is known to have some internet speed limitation issue, such as what's described in https://github.com/microsoft/WSL/issues/4901 .

In line with the suggestion in https://github.com/ubuntu/WSL/issues/174 I plan to let the user opt-out for that language pack installation feature, trading setup speed for better language support. In such case Subiquity will only mark those packages for later installation, requiring from the user to run `sudo apt-get dselect-upgrade` at some point, whenever she feels like it's more appropriate.

To reflect that possibility in the UI, I propose changes to the `Select your language` page:

## Current

![image](https://user-images.githubusercontent.com/11138291/185249368-55dcb574-e3e9-4b82-8406-9dd868431725.png)

## Proposal

![image](https://user-images.githubusercontent.com/11138291/185248782-164ce9d0-4f46-4cf1-ad4f-2dd13ac1b23f.png) 
![image](https://user-images.githubusercontent.com/11138291/185248815-c32bf8b6-e827-47c2-83ff-cceba3af8307.png)

Notice that the checkbox subtitle changes from a disclaimer about the setup duration to an information about the command required to install the packages marked for later.

**Comment by CarlosNihelton** [comment]
The alternative I can see is placing the flag on its own page, right after this one.

**Comment by elioqoshi** [comment]
Hey @CarlosNihelton I think this looks okay. Do I understand it right that the checkbox help text changes based on whether it's checked or not? I'd not recommend that content change, it should stay static, regardless of the checkbox state.

Also is that checkbox impacting only a single language (the one you decided to install)?

**Comment by CarlosNihelton** [comment]
> Do I understand it right that the checkbox help text changes based on whether it's checked or not? I'd not recommend that content change, it should stay static, regardless of the checkbox state.

Yes, you're right. I'll make it static, then.

> Also is that checkbox impacting only a single language (the one you decided to install)?

Yes, we only install language packs for the selected language, and this flag is meant to skip that, if users want to. Should be on by default.

**Comment by elioqoshi** [comment]
> Yes, we only install language packs for the selected language, and this flag is meant to skip that, if users want to. Should be on by default.

In that case I'd recommend stating the name of the language as it's not clear it pertains to a single language
Something like:

[x] **Install English packages for better language support**
Not recommended for slow internet connections. 

I'd not mention the command line in the GUI, it feels like 2 worlds clash here

**Comment by CarlosNihelton** [comment]
Good! I'll proceed that way then.

**Comment by CarlosNihelton** [comment]
@elioqoshi due a limitation in the TUI, the terminal client for Subiquity will need a new page, after all. I'm placing it just after the language selection page. In principle I don't see a problem in having the GUI diverging at this point.

Feel free to criticize the wording and the UI on the screenshot below.

![image](https://user-images.githubusercontent.com/11138291/186022991-6354d27e-8a07-48d9-87d7-b28b8f2048da.png)

**Comment by elioqoshi** [comment]
That's fine! Just make sure to state the language of the language packages based on the prior selection.

Regarding the help text, should that not be usually indented on TUI? 

So something like: 


- [x] **Install English packages for better language support**
                 Not recommended for slow internet connections.

**Comment by CarlosNihelton** [comment]
I checked the other check boxes, they are not indented.

![image](https://user-images.githubusercontent.com/11138291/186146542-ef2fbe19-b52e-496f-ae75-661b9fe6f211.png)

Here's how it would look if indented:
![image](https://user-images.githubusercontent.com/11138291/186146784-dcbf83ff-ac49-42fb-8ebf-c04a994d5b10.png)

**Comment by elioqoshi** [comment]
Nevermind, not indented is okay then! But I remember in the past we have styled help text differently, with a gray colour I think, like here: https://docs.google.com/document/d/1rsapWIKR9xR3sXE56WUEETSvnZkxJH4RqrvJCKK7IWI/edit#heading=h.v8vlh9f5o0cz

<img width="582" alt="image" src="https://user-images.githubusercontent.com/5436686/186231619-fb6e2495-5adb-491d-ae8a-f6a6415e7586.png">

Is that possible?

**Comment by CarlosNihelton** [comment]
Yes, it's possible!

![image](https://user-images.githubusercontent.com/11138291/186396524-416da7d8-56b1-471f-aff5-8b96af93bfdf.png)

**Comment by elioqoshi** [comment]
The gray is a bit too dark, it has 3.66 colour contrast and should be 4.5 at least. Do you have a lighter gray you can use?

**Comment by CarlosNihelton** [comment]
That's the lighter gray we have in the palete. We can suggest the Subiquity team a lighter one. Would you have the RGB value to suggest?

![image](https://user-images.githubusercontent.com/11138291/186398888-e3941201-3d12-4d1b-b812-e663b250bddd.png)

**Comment by CarlosNihelton** [comment]
Here's how it looks like with the "gray" color set to `0x999999`:

![image](https://user-images.githubusercontent.com/11138291/186399744-7a0872d4-ddd3-483c-aadf-f7584a14a0fb.png)

**Comment by elioqoshi** [comment]
This should be synced with Subiquity as well to be consistent. The darkest gray this would be okay is #777777

**Comment by dbungert** [comment]
>  I remember in the past we have styled help text differently, with a gray colour I think, like here:  
> Is that possible?

The end state of that is, if we had help text and a disabled element on the same page, they would be the same color.  Is that intended?

**Comment by elioqoshi** [comment]
> The end state of that is, if we had help text and a disabled element on the same page, they would be the same color. Is that intended?

I think that would be fine if the main element is distinguished
