### ISSUE TITLE
Slightly clumsy English in screen 6

### ISSUE THREAD

**Issue by popey** [canonical/ubuntu-desktop-installer#110]
`"installThirdPartyTitle": "Install third-party software for graphics and Wi-Fi hardware and additional media formats",`

Generally we try not to `this and that and the other` in English, but prefer commas. So, this would be preferable.

`"installThirdPartyTitle": "Install third-party software for graphics, Wi-Fi hardware, and additional media formats",`

**Comment by MarcusTomlinson** [comment]
Hmm, I think `graphics and Wi-Fi hardware` expands to `graphics hardware and Wi-Fi hardware`, with `additional media formats` being separate.

Perhaps something like:

`"installThirdPartyTitle": "Install third-party software for graphics and Wi-Fi hardware, as well as additional media formats",`

**Comment by oSoMoN** [comment]
Thanks @popey for your attention to detail! I was going to go ahead and apply your suggestion, but @MarcusTomlinson has a point. To my non-native ear, all three suggestions look equally valid, so that's a tie. Thoughts?

**Comment by popey** [comment]
Good point. I think either are fine.
