### ISSUE TITLE
Slides need to be updated for Kinetic

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#1188]
We still have the previous cycle images in the slideshow

**Comment by jpnurmi** [comment]
1. wallpaper with mascot on the right (PNG, 960x480)
2. wallpaper without mascot (PNG, 960x480)
3. mascot only (SVG)

| | Current | Context |
|---|---|---|
| 1 | ![welcome](https://user-images.githubusercontent.com/140617/196621577-1199877c-cb5f-487f-9bf1-a06d173484f4.png) | ![Screenshot from 2022-10-19 08-57-23](https://user-images.githubusercontent.com/140617/196621666-2f73da67-f483-4184-b6be-5c712411b6e1.png) |
| 2 | ![background](https://user-images.githubusercontent.com/140617/196622018-3d52d45d-dfee-4a35-8b72-837cf6dacfe8.png) | ![Screenshot from 2022-10-19 08-57-41](https://user-images.githubusercontent.com/140617/196622048-399ec0d0-ad37-43b2-bc0e-d77143838d5c.png) |
| 3 | ![logo](https://user-images.githubusercontent.com/140617/196622134-02437ff9-f414-4e61-bc6f-fae1433af90a.svg) | ![Screenshot from 2022-10-19 09-10-05](https://user-images.githubusercontent.com/140617/196622309-5ad84af3-d103-4c82-92c9-56f75c792b30.png) |

**Comment by jpnurmi** [comment]
What about @2x assets for high-DPI screens?
