### ISSUE TITLE
Locations popdown is cut at the bottom edge of the dialog

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#1189]
On the 'Where are you' page, if you type a location name there is a popdown list displaying, it's cut at the bottom of the UI though which has basically only space for 1.5 entry. Is that a flutter issue? If so could we maybe make it pop up where there is space?

**Comment by jpnurmi** [comment]
- https://github.com/flutter/flutter/issues/101620#issuecomment-1286576417
