### ISSUE TITLE
CMake Error and Exception during `flutter run`

### ISSUE THREAD

**Issue by mugman174** [canonical/ubuntu-desktop-installer#12]
I run all of the commands to checkout and run on the README, but once I run `flutter run`, it gives me an error:
```
CMake Error at flutter/generated_plugins.cmake:12 (add_subdirectory):
    add_subdirectory given source
    "flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux" which is not
    an existing directory.
Call Stack (most recent call first):
    CMakeLists.txt:59 (include)

Building Linux application...
Exception: Unable to generate build files
```
My OS: Ubuntu Focal 20.04.2 LTS

###### P.S. This is the first Issue I have ever submitted, just fyi.

**Comment by MarcusTomlinson** [comment]
I think something failed in your set up earlier than this.

Please could you run through the whole checkout & run process again and share all logs.

**Comment by mugman174** [comment]
I just deleted the entire folder and rebuilt it. It works now. Strange... Anyways I'm gonna close this because problem solved.
