### ISSUE TITLE
Installer update

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1241]
- [x] Subiquity API: https://github.com/canonical/ubuntu-desktop-installer/pull/1240
- [ ] Desktop GUI: TBD

**Comment by jpnurmi** [comment]
@elioqoshi here's a minimal mockup for inspiration

![Screenshot from 2022-11-21 11-52-48](https://user-images.githubusercontent.com/140617/203054918-86d0cca8-ff38-41cf-9a8a-12d9ca10b2f6.png)

![Screenshot from 2022-11-21 12-57-35](https://user-images.githubusercontent.com/140617/203055045-553eeb9a-76a9-404c-ac8a-1bbc3977e51c.png)

![Screenshot from 2022-11-21 12-57-56](https://user-images.githubusercontent.com/140617/203055066-0f88d281-8c2f-4419-aaa0-83731c94fbca.png)

![Screenshot from 2022-11-21 12-58-06](https://user-images.githubusercontent.com/140617/203055082-1c93fb80-83f7-40d0-ab14-d4074f773ca0.png)

![Screenshot from 2022-11-21 12-58-12](https://user-images.githubusercontent.com/140617/203055127-7397a356-e351-4644-bd61-4888c55b43e5.png)

![Screenshot from 2022-11-21 13-21-08](https://user-images.githubusercontent.com/140617/203055168-9bee0055-95b0-4d9c-a1b9-91d2e0725a08.png)

**Comment by jpnurmi** [comment]
P.S. I stole and reused the artwork from the _Installation complete_ page...

![Screenshot from 2022-11-21 13-20-34](https://user-images.githubusercontent.com/140617/203055467-d04a63e5-8490-40d9-91c5-64533c88868f.png)

**Comment by elioqoshi** [comment]
@jpnurmi I think this works fine. Could you elaborate how do you imagine to merge the screens?

**Comment by jpnurmi** [comment]
I mean these two pages have the same elements but are laid out differently:
![image](https://user-images.githubusercontent.com/140617/211845940-a13064e4-ec67-4260-a507-7f94dc69222b.png)

**Comment by jpnurmi** [comment]
Even though the user will never ever see these two pages side by side or even one after another. The update page is already in the installation process, and the installation complete page comes 15 minutes later. :)

**Comment by jpnurmi** [comment]
@elioqoshi My earlier mockup is missing a "Go Back" button. :man_facepalming: Here's an updated proposal that uses a layout similar to the "Installation complete" page. How do you like it?

[Screencast from 2023-01-13 14-29-55.webm](https://user-images.githubusercontent.com/140617/212332153-725ca6cc-43be-4aca-aca3-817f0828552c.webm)

**Comment by elioqoshi** [comment]
This looks fantastic, can't add much more to that! :)
