### ISSUE TITLE
The window 'allocate disk space' is empty

### ISSUE THREAD

**Issue by corradoventu** [canonical/ubuntu-desktop-installer#127]
Trying install from ISO in https://cdimage.ubuntu.com/daily-canary/current/ dated 2021-07-03 10:30 the window -select keyboard- is empty and if i click on continue also the window -allocate disk space- is empty. can not continue with install.
![Screenshot from 2021-07-03 14-00-01](https://user-images.githubusercontent.com/26655337/124357293-4e842980-dc0a-11eb-8c5d-7de0ba16a869.png)

**Comment by Feichtmeier** [comment]
Yes because it has not been implemented it yet: https://github.com/canonical/ubuntu-desktop-installer/issues/36

I think you can close this issue  @corradoventu
