### ISSUE TITLE
not able to build with Flutter 3.3.9 due to outdated intl dependency

### ISSUE THREAD

**Issue by maks** [canonical/ubuntu-desktop-installer#1273]
I tried to build the current `main` branch following the instructions in the Readme, using current latest stable channel (3.3.9) on Ubuntu 22.04.
However doing `flutter run` I get a dependency issue:
```
Because ubuntu_desktop_installer depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because ubuntu_desktop_installer depends on intl ^0.17.0, version solving failed.
Running "flutter pub get" in ubuntu_desktop_installer...                
pub get failed (1; So, because ubuntu_desktop_installer depends on intl ^0.17.0, version solving failed.)
```
and simply trying to update to 0.18.0 of `intl` package doesn't work because of `ubuntu_localizations` (via `ubuntu_wizard`) having a dependency on 0.17.0.

I can see renovate bot has opened a PR to [update the intl dep](https://github.com/canonical/ubuntu-desktop-installer/pull/1271) as well as [on the ubuntu_localizations package](https://github.com/canonical/ubuntu-flutter-plugins/pull/111) which isn't passing CI, so I guess this is blocked on that getting fixed first.

**Comment by jpnurmi** [comment]
The latest Flutter main still depends on intl 0.17.0 and the line was last time touched in Feb 2021, 23 months ago.

https://github.com/flutter/flutter/blob/aa70994f60d2c0e33b0a82364ba87d0ac95f9fad/packages/flutter_localizations/pubspec.yaml#L11
```yaml
  intl: 0.17.0
```

I'm not sure how your Flutter SDK can have a `flutter_localizations` package that depends on `intl` 0.18.0. Are you sure you have a pristine Flutter installation?

**Comment by maks** [comment]
Hmm yes I don't know what happened there, I'm pretty sure I was using just the latest stable channel via `fvm`.
I just tried again, though now I'm on `3.3.10` and sure enough it all builds and runs fine.

My apologies for the taking up your time @jpnurmi .
