### ISSUE TITLE
Correct Btrfs filesystem description journaling on selection

### ISSUE THREAD

**Issue by emanuc** [canonical/ubuntu-desktop-installer#1294]
Hello,
When choosing manual partitioning you have a selection of filesystems to choose from, when selecting Btrfs it is incorrectly described as: "Btrfs journaling file system" [1], it is actually a COW filesystem and does not have journaling [2].

1:  
![installer](https://user-images.githubusercontent.com/27281121/211023910-a7e8deaf-90f7-4833-9128-bd9985a2aae0.png)

2:  
> btrfs is a modern copy on write (CoW) filesystem for Linux
https://btrfs.wiki.kernel.org/index.php/Main_Page

**Comment by jpnurmi** [comment]
Interesting, thanks for bringing it up! It had been copied from the old installer. :)

![image](https://user-images.githubusercontent.com/140617/220425240-9477e56f-1d6f-4019-9431-3aefe9df7897.png)
