### ISSUE TITLE
Hyperlink not changing mouse cursor on hover

### ISSUE THREAD

**Issue by fabiancrx** [canonical/ubuntu-desktop-installer#13]
I know it's a little silly to land an issue of a UI problem this early, but it comes with thte intention to land a PR(using url_launcher already includeded in the dependencies) to fix it.
And to ask for guidelines or roadmap to help this project (#8 ), as this would be a huge success to flutter if accomplished.

Problem:
In the try or install screen the release notes link does not change mouse cursor on hover:
![image](https://user-images.githubusercontent.com/37002358/106676635-49e91580-6585-11eb-87dd-74bfa7a7335b.png)

**Comment by oSoMoN** [comment]
Thanks for your attention to detail @fabiancrx. This is by no means silly, this kind of details is what makes a UI/UX polished and pleasant to use.
As you expressed the intention to fix this yourself, I'm assigning the bug to you. Looking forward to reviewing your PR!

**Comment by fabiancrx** [comment]
Hi made most of the changes and can check it out [here](https://github.com/fabiancrx/ubuntu-desktop-installer/tree/hyperlink-no-hover(%2313)).
It is not complete due to the translations, the current text in the app translations is `You may wish to read the <a href=\"$url\">release notes</a>.` which worked for the previous(current?) implementation which uses the HTML widget but I used just `Text` widgets which do not parse the html and the whole string would be displayed with tags.
* If I tried to add the hover effect to the html widget , the whole widget would hover, not just the hyperlink, I don't know if that is the wanted/accepted behavior.
* The  [PR](https://github.com/fabiancrx/ubuntu-desktop-installer/tree/hyperlink-no-hover(%2313)) makes only the link hover but translations would need to split `You may wish to read the <a href=\"$url\">release notes</a>.` into :
    - `You may wish to read the ` and  `release notes.`
which would be extra work.
Any recommendation @oSoMoN

**Comment by oSoMoN** [comment]
Using separate widgets is not going to work because of internationalization requirements: some languages may not necessarily order the translations of "you may wish to read the" and "release notes" like in English, so it needs to be one single string to enable correct translations.

I think the correct approach would be some CSS styling in the Html widget that changes the mouse cursor when hovering over the hyperlink only, but I'm not sure whether this is allowed by the current implementation. If not, filing a [feature request](https://github.com/Sub6Resources/flutter_html/issues) would be a good place to start.

**Comment by fabiancrx** [comment]
I have created a PR [here](https://github.com/Sub6Resources/flutter_html/issues/563) you can read further details.
Other packages I have found also face the limitations commented in the issue above like [flutter_html,simple_html_css].
So I have another question how much of the HMTL spec is needed,?
For now it just seems to be used to parse `<a>` tags  and maybe if only this is needed a smaller/simpler solution can be made.

**Comment by jpnurmi** [comment]
flutter/flutter#77754 (Add mouseCursor, onEnter, and onExit to TextSpan) has been merged.

**Comment by jpnurmi** [comment]
Fixed by https://github.com/Sub6Resources/flutter_html/pull/572
