### ISSUE TITLE
Installer Windows doesn't fit on a 1024x768 display

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1306]
Lunar / ubuntu-desktop-installer   0+git.518d1ff6    712

During the initial boot, the main window doesn't fit on a 1024x768 display, and the buttons on the bottom right are not reachable.

![installer_2023-01-13_09-42](https://user-images.githubusercontent.com/1928546/212277551-c613af7e-b184-49c6-a83f-c4142edce002.png)

**Comment by jpnurmi** [comment]
Fixed by https://github.com/canonical/ubuntu-desktop-installer/pull/1371
