### ISSUE TITLE
Try/Install page is displayed again during installation from live session

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1307]
Lunar / ubuntu-desktop-installer 0+git.518d1ff6 712

Test Case:
1. Boot the installer
2. When the page Try/Install is displayed, select "Try" to boot to the live session
3. Start the installer from the live session
4. Select a language and proceed to next page

Actual result
The page Try/Install is displayed again, while it shouldn't (we're in the live session already)

![installer_2023-01-13_09-42](https://user-images.githubusercontent.com/1928546/212278338-fcbb0940-b28b-49cc-8fde-3ae665ebf625.png)

**Comment by jpnurmi** [comment]
@seb128 Any thoughts on how to handle this? The installer is always running in the live session but can we detect the initial startup mode? GSettings?

**Comment by seb128** [comment]
> @seb128 Any thoughts on how to handle this? The installer is always running in the live session but can we detect the initial startup mode? GSettings?

Unsure what automatic logic we could use, but an option is to add a command line parameter --try-or-install and update the systemd unit to include the option (or the other way around, make it default and have a flag to disable the page and update the .desktop to use it)?

**Comment by jpnurmi** [comment]
@seb128 Could you help adding `--try-or-install` for the systemd unit, please? The command-line argument is available in the latest stable.

**Comment by seb128** [comment]
I've added it now, the change should be included in tomorrow's daily image

**Comment by jpnurmi** [comment]
Thanks! I've confirmed the correct behavior with 20230206.
