### ISSUE TITLE
Proposal: decouple routing logic from pages

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#133]
The proposal is to move routing logic out of wizard pages so that individual pages wouldn't have to care about what comes next.

Requirements:
- Introducing new pages shouldn't cause changes in existing pages.
- Re-ordering pages should be a matter of changing the order in one central place.
- It must be possible to have conditional routes (e.g. if online, skip the connect to internet page).

Example: [flutter_wizard_example](https://github.com/jpnurmi/flutter_wizard_example)

- Three dummy pages + an imaginary service that affects routing.
- Pages call `Wizard.of(context).next()` to request the next page.
- The list of pages and the routing order:
  https://github.com/jpnurmi/flutter_wizard_example/blob/main/lib/routes.dart
- The actual routing logic is implemented using [flow_builder](https://pub.dev/packages/flow_builder) which is based on the Navigator 2.0 Pages API:
  https://github.com/jpnurmi/flutter_wizard_example/blob/main/lib/wizard.dart

Any thoughts?

**Comment by Feichtmeier** [comment]
Sounds great - I also missed a single place for the routes!

**Comment by Feichtmeier** [comment]
Ah one idea: would it be possible to mark one of the routes somehow as "finalized route" or "lastRoute" so the wizardaction on the last page would be an ElevatedButton (yaru green buttons) instead of an OutlinedButton ?

**Comment by jpnurmi** [comment]
@Feichtmeier The example is a bit simplified version. In the real installer, highlighted actions are defined as `WizardAction(highlighted: true)`. There can be any amount of actions and they can do basically anything.

Note to self: naturally, the syntax should be `Wizard.of(context).next()`. The context needs to be inside FlowBuilder and a little shortcut was taken in the example... :)

**Comment by oSoMoN** [comment]
That looks like a sound proposal, thanks @jpnurmi!

What about pages that take arguments (see e.g. https://github.com/canonical/ubuntu-desktop-installer/blob/main/packages/ubuntu_desktop_installer/lib/pages/allocate_disk_space_page.dart#L135)?

**Comment by jpnurmi** [comment]
Provider most often eliminates the need of constructor parameters. State/info can be shared via models and services (i.e. Subiquity client, network service, ...).

In this specific case, would it be a bad solution to make the "Write changes to disk" page use `SubiquityClient.getGuidedStorage` instead of passing it as a constructor argument? It's an extra HTTP request but would cut the hard dependency.

If there's a need for tightly coupled pages, it's also possible to push routes outside the Wizard / Navigator 2.0 pages API. This would fit better for hierachical main vs. sub-page type of navigation, though. In linear wizard page navigation, it kind of fights against the internally maintained page route stack.

**Comment by oSoMoN** [comment]
> In this specific case, would it be a bad solution to make the "Write changes to disk" page use `SubiquityClient.getGuidedStorage` instead of passing it as a constructor argument? It's an extra HTTP request but would cut the hard dependency.

It's a bit counter-intuitive, but `SubiquityClient.getGuidedStorage()` doesn't return the information we want, the storage config we need is the response we get after calling `SubiquityClient.setGuidedStorage(…)`. So we need to pass this information from one screen to the next, somehow. I suppose we could use a separate model for this (or modify `SubiquityClient` to keep a copy of the storage config).

**Comment by jpnurmi** [comment]
Solved by https://github.com/canonical/ubuntu-desktop-installer/pull/183
