### ISSUE TITLE
Unsupported format options offered in custom partitioning

### ISSUE THREAD

**Issue by xnox** [canonical/ubuntu-desktop-installer#1332]
curtin supports consuming a large variety of filesystems. These are not supported by all Operating Systems.

For example the large variety of FAT and NTFS filesystems is to support installting Windows from MAAS. Installing Ubuntu on NTFS is not supported.

Majority of these are not supported by Ubuntu or Canonical for new installations. And are not offered in neither MAAS or subiquity.

See screenshots below:

![subiquity-options](https://user-images.githubusercontent.com/19779/214284883-37a1ed30-057f-45ac-be16-d5f3ef2c9f54.png)
![instaler-options-2](https://user-images.githubusercontent.com/19779/214284886-297bcc60-7f9f-47e0-aadd-b6e85a167079.png)
![installer-options-1](https://user-images.githubusercontent.com/19779/214284888-4a210eac-90f2-4990-999d-a39963971edd.png)

Please do not allow creating legacy/obsolete filesystems, or those with limited kernel support:
* ext2
* ext3
* ISO 9660 (read-only FS)
* JFS
* ReiserFS

No new installs should contain that.

Please do not offer creating FAT:
* FAT
* FAT12
* FAT16
* FAT32
* VFAT
It must not be used for any mountpoints, apart from EFI partition which is separate.

Please do not offer creating NTFS
* R/W and ACL support is limited, thus it must not be offered as a mountpoint

Unformatted option is not offered
* installer should offer leaving partitions unformatted

The offering of zfsroot option is confusing - it is not offered by subiquity; it is considered experimental in curtin; it doesn't setup things compatible with encryption; zsys; snapshotting; grub integration; or even a supported featureset. Meaning it is easy to bork such installations. Note that subiquity does not offer zfsroot option.

Compared with subiquity installer manual partitioning lacks LVM and RAID options. I don't know if this is intentional, or simply missing feature parity for now.

cc @mwhudson @dbungert @ogayot @vorlonofportland

**Comment by jpnurmi** [comment]
@dbungert `add_partition` throws when trying to create an unformatted partition

```
Traceback (most recent call last):
  File "/home/jpnurmi/Projects/canonical/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/common/api/server.py", line 134, in handler
    result = await implementation(**args)
  File "/home/jpnurmi/Projects/canonical/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/server/controllers/filesystem.py", line 746, in v2_add_partition_POST
    raise ValueError('add_partition must supply format')
ValueError: add_partition must supply format
```
