### ISSUE TITLE
Installer bigger than screen, continue button not visible and pointer integration missing in a VM

### ISSUE THREAD

**Issue by xnox** [canonical/ubuntu-desktop-installer#1336]
Firstboot (NB! no rounded corners neither top or bottom, suggests it is "full screen")
![installer-too-big](https://user-images.githubusercontent.com/19779/214325953-dbf03f5d-04c4-467a-bd20-866e998b39bb.png)

Unsnap & resnap (NB! rounded corners on the bottom, suggests it is just a large window, not "full screen"):
![installer-too-big-2](https://user-images.githubusercontent.com/19779/214325952-5512cae3-0335-40bd-bb93-2aaf1fc65894.png)

I am booting in VM. Potentially shell comes up in one resolution which receives resize notification somewhere after launching the installer.

the continue/back buttons are missing, if i unsnap the full screen window and resnap it, it becomes visible.

The lack of "full-screen button" on the installer confused me a little bit, i couldn't tell if the window is full-screen; or not full-screen yet bigger than the screen size.

Also mouse pointer didn't work smoothly across the VM from host to guest and out, normally i can wiggle mouse pointer which would smoothly grab the pointer between host OS and the guest VM.

**Comment by local-optimum** [comment]
Related but maybe unrelated technically. VirtualBox defaults to a screen resolution of 800x600 meaning the bottom section of the installer is largely cut off making it difficult to navigate the installer. Once you've completed an install you can enable guest additions which allows dynamic windows resizing but we should investigate the virtual box default resolution issue as it's not present on a number of other Linux OSs

**Comment by jpnurmi** [comment]
The design team wanted to keep a fixed 960x680 window size so we're trying to mitigate the problem by querying the available workarea on startup and if the window doesn't fit, we're making the window resizable and maximizing it.

The problem is that the installer starts so early that maximizing the window doesn't work reliably either. It's probably because GdkMonitor reports a wrong workarea e.g. the top-bar is not excluded. What makes it tricky to fix is that GdkMonitor doesn't notify workarea changes when the top-bar becomes visible (or when the dock visibility is toggled, for that matter). One wild idea was to query DING or implement our own little GNOME extension but I wonder if it would be better to reconsider the fixed window size...

**Comment by xnox** [comment]
> The design team wanted to keep a fixed 960x680 window size so we're trying to mitigate the problem by querying the available workarea on startup and if the window doesn't fit, we're making the window resizable and maximizing it.
> 
> The problem is that the installer starts so early that maximizing the window doesn't work reliably either. It's probably because GdkMonitor reports a wrong workarea e.g. the top-bar is not excluded. What makes it tricky to fix is that GdkMonitor doesn't notify workarea changes when the top-bar becomes visible (or when the dock visibility is toggled, for that matter). One wild idea was to query DING or implement our own little GNOME extension but I wonder if it would be better to reconsider the fixed window size...

i will double check, but i think with ubiquity we avoided this with extra calculation. Query size at launch (i.e. whatever gdkmonitor reported) but then we manually subtracted things that might appear later (i.e. top-bar and what not), and I thought we took a margin after that as well, like 90%.

Also potentially there are some Wayland / XServer integration regression. As I thought my VMs used to come with a large HD resolution, instead of tiny one. Such  that 960x680 should have fit just fine. So maybe we have graphics regression somewhere else. It would be nice to check that our Qemu / Libvirt in both UEFI and BIOS modes does produce VMs that come up with widescreen "normal" resolutions instead of pre-historic ones that can't even fit 960x680.

**Comment by xnox** [comment]
if the screen is small (i.e. too close to our desired fixed size) imho we should force the installer to be "full-screen". Not sure how that will work out.

**Comment by jpnurmi** [comment]
The window is now shown full screen if it doesn't fit (#1371).

I'm not sure what to do about the mouse pointer issue. Do you think it might have something to do with the installer or Flutter?

**Comment by jpnurmi** [comment]
The new installation slides are scalable and have been designed so that they work fine at 800x600 resolution:

- https://github.com/canonical/ubuntu-desktop-installer/pull/1598

Let us know if the mouse pointer issue persists.
