### ISSUE TITLE
Proposal: add a page indicator

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#135]
Could we eventually create some kind of indicator for the page index or some sort of orb indicator like so
![grafik](https://user-images.githubusercontent.com/15329494/124768123-b2735e80-df38-11eb-9de1-0a6f26a3755e.png)

?

Easy code snippet
```dart
Row(
  mainAxisAlignment: MainAxisAlignment.center,
  children: snapshot.data!.map((url) {
    int index = snapshot.data!.indexOf(url);
    return Container(
      width: 10,
      height: 10,
      margin: EdgeInsets.symmetric(
          vertical: 10.0, horizontal: 10.0),
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        color: _current == index
            ? Theme.of(context)
                .primaryColor
                .withAlpha(180)
            : Theme.of(context)
                .primaryColor
                .withAlpha(60),
      ),
    );
  }).toList(),
)
```

It could be either be put into the wizard page, or into the AppBar - or? Any other suggestions? :) 
@madsrh @long-chung

**Comment by jpnurmi** [comment]
Isn't the number of pages pretty high for page indicators?

**Comment by Feichtmeier** [comment]
> Isn't the number of pages pretty high for page indicators?

Yes. It doesn't need to be dots. But some kind of indication would be great. Currently you have no idea what to expect, how long this takes and where you are in this process.

Maybe a simple 2/17 would be enough

**Comment by madsrh** [comment]
I like the idea, BUT I wonder if it was a deliberate decision by the Canonical design team to "remove" them? (If these screens are based on ubiquity). 
I've ofc encountered page indicators many times before, but why aren't these found in the installation/setup for OSX, Windows 11, Adobe CS, Firefox or Android 🤷‍♂️

This would probably be something Will Grant (wgx) would have an opinion about.

![the-ubuntu-minimal-install-option](https://user-images.githubusercontent.com/3986894/124837799-df9a2e00-df85-11eb-8541-ad664be3b9b7.jpg)

**Comment by long-chung** [comment]
We purposely removed the indicators because it doesn't give you a good indication of where you are in the installation, as you could go to other pages during setup.

**Comment by Feichtmeier** [comment]
@long-chung @madsrh  it wouldn't need to be orbs - how about something like a page indicator in a book?

![grafik](https://user-images.githubusercontent.com/15329494/124908094-38e77900-dfe9-11eb-8f71-6498ad780029.png)

**Comment by long-chung** [comment]
Here's a rough flow of the various points you could end up. The indicator would be misleading if you end up in any one of the end points in the diagram.

<img width="602" alt="Screenshot 2021-07-08 at 11 40 36" src="https://user-images.githubusercontent.com/68847062/124908681-81029d80-dfe1-11eb-9866-b7107247187a.png">

**Comment by Feichtmeier** [comment]
Okay... You are right 😊 if the process is not "linear" then this doesn't make any sense
