### ISSUE TITLE
Flavours: Guidance sought how best to implement per flavour slides

### ISSUE THREAD

**Issue by fossfreedom** [canonical/ubuntu-desktop-installer#1354]
Hi,

  Is there any guidance available how per flavour slides are to be submitted?

https://github.com/canonical/ubuntu-desktop-installer/blob/main/packages/ubuntu_desktop_installer/lib/slides/default_slides.dart

Looking at the above the list of slides is hard-coded.   So would an alternative list for each flavour need some-sort of (pseudo code alert) if then else statement?

```
"if budgie flavour do

  this slides

elseif mate flavour do ....

else
  do the default slides
endif
```

I'm presuming there is only one snap - so the snap somehow needs to work out if its running on a specific flavour to provide the customisation? Or is there suppose to be a flavour specific snap installer?

**Comment by jpnurmi** [comment]
The idea is that the theme, slides, etc. can be passed to `runInstallerApp()` but we have a known issue that the current project structure is not good for creating flavors outside of the main repo, unfortunately. The `subiquity_client` package is not a normal Dart package because it needs to be coupled with the Subiquity submodule. We should move it to a separate repo to make it possible to build flavors with the same structure we have in the main installer repo.

**Comment by jpnurmi** [comment]
I'm preparing a dummy example with a custom theme, image assets, and installation slides:

[Screencast from 2023-02-01 17-47-37.webm](https://user-images.githubusercontent.com/140617/216107934-cbd1372f-4b94-4bd0-906f-9e0f28ff8a19.webm)

It will be a separate standalone repo that you can take as a starting point. It uses `ubuntu_desktop_installer` and `subiquity_client` as Git dependencies. I will push it as soon as I have all the necessary changes merged. I have already moved [subiquity_client](https://github.com/canonical/subiquity_client.dart) and the next step is to take it into use here: https://github.com/canonical/ubuntu-desktop-installer/pull/1355. After that, we'll need to tweak the local dependencies a bit and then we should be ready to start trying it out. :+1:

**Comment by ItzSwirlz** [comment]
Cool! When should it be implemented per flavor?

**Comment by jpnurmi** [comment]
There will be an example to get everyone started soon. :slightly_smiling_face: We will support you with any changes that may be needed for `ubuntu_desktop_installer` and `subiquity`. It's quite likely that there are some desktop-specific adjustments necessary here and there.

**Comment by jpnurmi** [comment]
Hi all, it's still lacking appropriate documentation but there's a starting point at https://github.com/canonical/ubuntu-flavor-installer that we could start playing with and see how far we get with different flavors. There are some minor changes coming to the template, still but if you don't mind being an early tester, any feedback would be very welcome so we can start tackling them case by case!

**Comment by jpnurmi** [comment]
https://github.com/canonical/ubuntu-flavor-installer/issues/3
