### ISSUE TITLE
Allocate disk space page doesn't support dark mode

### ISSUE THREAD

**Issue by charafau** [canonical/ubuntu-desktop-installer#136]
Most likely easy to fix: currect allocate disk space page doesn't change font colors for partition table

 
![Screenshot from 2021-07-07 16-59-01](https://user-images.githubusercontent.com/1143994/124792188-b1482e80-df44-11eb-9ad3-e8657e40feb9.png)

**Comment by Feichtmeier** [comment]
I guess I can fix this,  the color is hardcoded here:

https://github.com/canonical/ubuntu-desktop-installer/blob/a290e161896a0ae37936906280f977bf6ec26dc4/packages/ubuntu_desktop_installer/lib/pages/allocate_disk_space_page.dart#L68

**Comment by Feichtmeier** [comment]
![image](https://user-images.githubusercontent.com/15329494/124801327-02611e00-df57-11eb-85c0-e95a79d298ca.png)
![image](https://user-images.githubusercontent.com/15329494/124801631-57049900-df57-11eb-87d3-f9b8796877a1.png)

I think this is okay, right?
