### ISSUE TITLE
memtest not found

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1361]
lunar 20230203

=Test Case=
1. On the boot menu click on memtest

=Actual result=
This crash
![image](https://user-images.githubusercontent.com/1928546/216640793-862ebe92-110b-4eda-bfb3-b3a30362453b.png)

=Expected result=
Memtest starts.

**Comment by seb128** [comment]
The issue was fixed in https://git.launchpad.net/~ubuntu-cdimage/debian-cd/+git/ubuntu/commit/?id=d8280780 and the fix was verified to work on today's daily
