### ISSUE TITLE
Missing option to continue using the live session

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1363]
Lunar 20230203

At the end of the installation, the user can reboot or shut down the system. There is no option to continue using the live session.

![image](https://user-images.githubusercontent.com/1928546/216650840-d902dab1-c47c-4f7d-bc9f-d238436b96fd.png)

**Comment by jpnurmi** [comment]
Might have been intentionally left out in the new design /cc @elioqoshi 

![image](https://user-images.githubusercontent.com/140617/216653396-0561b83a-2cb9-4f4b-be1f-233159e96a1b.png)

https://github.com/canonical/ubuntu-desktop-installer/issues/43

**Comment by elioqoshi** [comment]
This was likely before my time so I don't know the decision behind it but it feels not deliberate. I think adding another button for continuing the live session should suffice, what do you think @jpnurmi ?

**Comment by jpnurmi** [comment]
We can easily add one more button to close the window if we want. :) This is how it looks in Ubiquity - it doesn't keep the main window visible but shows a separate message box:

![image](https://user-images.githubusercontent.com/140617/217301062-15701d19-e152-4da4-aa2c-fc5d53015fd9.png)

**Comment by elioqoshi** [comment]
I can provide a screen design for that if you prefer so we can track it properly

**Comment by jpnurmi** [comment]
<img width="1107" alt="Image Pasted at 2023-2-8 11-46" src="https://user-images.githubusercontent.com/140617/217517554-da24f275-5e53-474e-b00c-bc9a42d3b506.png">
<img width="1077" alt="Image Pasted at 2023-2-8 11-56" src="https://user-images.githubusercontent.com/140617/217517573-e5674e67-29d2-454f-8efb-890f0f13442d.png">

**Comment by jpnurmi** [comment]
I really like the new design. Thank you, Elio! :)

![image](https://user-images.githubusercontent.com/140617/218146360-06890a12-2e73-4498-a48f-42658c40167c.png)
