### ISSUE TITLE
Message is truncated in slideshow

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1373]
Lunar 20230207

The message on the last slide of the slideshow is incomplete and there is no scrollbar to read then end.

![image](https://user-images.githubusercontent.com/1928546/217273681-5b19910a-442c-4853-ba98-4911a7025328.png)

**Comment by jpnurmi** [comment]
Thanks for bringing it up! I'll hold off with this one a little because @local-optimum and @elioqoshi are updating the slides.

**Comment by elioqoshi** [comment]
Would it be possible to scale the content if needed for languages which have more than x characters?

**Comment by jpnurmi** [comment]
Scaling the font dynamically is an option but I'm a bit worried that it results in arbitrarily changing font sizes between slides.

Alternatively, we could tweak the font size and implement a test that ensures there's no overflow in any language we have translations for. We'd be at the mercy of our translators but at least we'd catch the issue if any translated string suddenly would no longer fit after a translation update...

**Comment by seb128** [comment]
Not directly related to fixing it but what's the layout difference with the old slideshow which didn't have the issue, afaik we didn't change the content?

**Comment by jpnurmi** [comment]
The old slides are HTML, and the size is different (752x376 vs. 960x480). We have loosely replicated the looks with Flutter widgets because Flutter for Linux doesn't have support for WebView yet.

**Comment by jpnurmi** [comment]
The left-side font is quite heavy compared to Ubiquity.
![image](https://user-images.githubusercontent.com/140617/218039481-87cffc4c-bb77-4ebe-8c59-2ff59e6c477a.png)

The situation is not that bad, actually. We should get away with minor font and layout tweaks.

![photos-uk](https://user-images.githubusercontent.com/140617/218038713-7c50e50d-2cca-4fbf-a428-b7b7cfe58112.png)
![photos-ru](https://user-images.githubusercontent.com/140617/218038723-6a5955fd-e3cc-429c-8554-eba2c92d7248.png)
![photos-pl](https://user-images.githubusercontent.com/140617/218038727-f591be3c-0140-462c-90b9-bfd590628a8a.png)
![photos-ja](https://user-images.githubusercontent.com/140617/218038731-d190aada-4729-441e-bd3f-3f2cd0ca8c04.png)
![photos-hu](https://user-images.githubusercontent.com/140617/218038735-5a3c547e-c8b1-4c87-9221-87b7dd0cbca0.png)
![photos-fr](https://user-images.githubusercontent.com/140617/218038736-3dbb48b0-c971-46c8-8a34-6249cbf5de0f.png)
![music-uk](https://user-images.githubusercontent.com/140617/218038738-205dfa39-767f-4c00-bec8-73abd98f7e03.png)
![music-ru](https://user-images.githubusercontent.com/140617/218038741-3a5b73c2-082a-41a8-912b-54c349d0bf4d.png)

**Comment by seb128** [comment]
> The old slides are HTML, and the size is different (752x376 vs. 960x480). We have loosely replicated the looks with Flutter widgets because Flutter for Linux doesn't have support for WebView yet.

Right, I know that the implementation is different and why, they are similar enough in result though which I was wondering what difference we had, screen size/spacing/font. Your proposed change answers the question though :)
