### ISSUE TITLE
Why "Libreoffice writer" in customisation options of the slideshow?

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1374]
lunar 20230207

"Libreoffice Writer" is listed in a slideshow on accessibility and customisation options but it is barely related

![image](https://user-images.githubusercontent.com/1928546/217277020-fa7c9d5a-dfb3-420c-a171-ca7052ee5998.png)

**Comment by jpnurmi** [comment]
Good catch, thanks! It should say "Appearance"

![image](https://user-images.githubusercontent.com/140617/217278946-79100e9f-7ea3-484b-927a-9be21096d9c6.png)
