### ISSUE TITLE
Improve OptionCard selections

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#139]
@Feichtmeier I really like the animation transitions but I'm not sure the orange text is working and it isn't explicitly obvious which selection you have made. I would suggest just using white and dark grey text and just use the orange to outline the box. Below are a couple of examples with the text and visual knocked back (when not selected) and a small shadow to emphasise your choice. There is also a text update but I'm not sure it's better than what we have, let me know what you think?
![Dark](https://user-images.githubusercontent.com/42238722/124945275-e8cadf80-e005-11eb-93af-1de6d841d5f4.png)
![Light](https://user-images.githubusercontent.com/42238722/124945285-ea94a300-e005-11eb-985d-73b7039c7081.png)
![screens](https://user-images.githubusercontent.com/42238722/124945302-eec0c080-e005-11eb-8869-8ee6602c4aca.gif)
Text change?
![Dark-text-change](https://user-images.githubusercontent.com/42238722/124945595-347d8900-e006-11eb-95a9-af34340f5aef.png)

_Originally posted by @waynecrosby in https://github.com/canonical/ubuntu-desktop-installer/issues/84#issuecomment-876517363_

**Comment by jpnurmi** [comment]
IMHO the gray one looks disabled. Also, if we want to mimic the real world, a toggle button is pressed down. It would be the unselected one that pops up with a shadow, right?

**Comment by Feichtmeier** [comment]
I would suggest to adapt to elevated buttons.
No elevation at all except on hover.

We can try opacity change depending on state but maybe not as drastically as Wayne proposed

**Comment by Feichtmeier** [comment]
@waynecrosby 

I think the elvation stuff does not work well at this size. How about a full flat widget? And only indicate hover / selected with text color and border?

Reducing the opacity of the picture looks indeed disabled, so I would prefer to skip this

![noelevation](https://user-images.githubusercontent.com/15329494/124965321-4a994280-e022-11eb-9ba9-e4a902aa8695.gif)

**Comment by waynecrosby** [comment]
@Feichtmeier Completely agree with you! I think it's clear now what you have selected and the font colour works much better. Looks good to me :)

**Comment by madsrh** [comment]
**jpnurmi** wrote:
> IMHO the gray one looks disabled....

**+1**, I still think the gray text looks disabled. Are you sure the orange border isn't sufficient @waynecrosby ?
Unselected text is usually black and gray is indicates a disabled state, like:

![image](https://user-images.githubusercontent.com/3986894/125196719-21172b80-e25b-11eb-8b18-e9a91269e0b9.png)

**Comment by waynecrosby** [comment]
@madsrh Ok, let's just try with the orange border and the text remains the same to avoid the disabled state issue. Thanks

**Comment by Feichtmeier** [comment]
opacity for unselcted cards when one card is selected is now on 0.65
![Peek 2021-07-12 11-46](https://user-images.githubusercontent.com/15329494/125267298-f4205280-e306-11eb-81d2-3ebf8b36cdb6.gif)

Or rather no text color change at all?
![Peek 2021-07-12 11-52](https://user-images.githubusercontent.com/15329494/125268133-b2dc7280-e307-11eb-9cd6-28052cd5991f.gif)

@waynecrosby @madsrh ?

**Comment by waynecrosby** [comment]
@madsrh @Feichtmeier I think it's probably simpler and will raise less issues if we have it with no text change :)

**Comment by Feichtmeier** [comment]
@waynecrosby we have one more question on this topic for you :)

Would you like the border to be 1px thick, like in the following gif? 

![Peek 2021-07-14 14-18](https://user-images.githubusercontent.com/15329494/125620912-ea0bfe68-63c0-42b5-bed6-8f0c99838bc3.gif)

**Comment by jpnurmi** [comment]
How about 1px gray border & 2px orange border like TextField?

**Comment by waynecrosby** [comment]
@Feichtmeier I think that the 1px looks ok in light mode, but when you switch to dark it gets totally lost. So to be consistent, I would be happy to use 2px for selected states in both light & dark mode. We are also in the install phase and settings realm where we need to be quite specific in what has been selected and 1px in my opinion is too thin.
