### ISSUE TITLE
Doesn't explain why the codec installation option is disabled

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#1390]
The codecs packages can't be provided on the ISO so the option isn't selectable unless the system is online. The reason/solution might not be obvious to the user though, should we have a string hint about it?

@elioqoshi

**Comment by elioqoshi** [comment]
We could add an information label saying the user is offline instead, I agree. @jpnurmi Should I mock something up or would you want to propose something?

**Comment by jpnurmi** [comment]
@elioqoshi please do if you have time. :) for reference, there's a warning when on battery:

![image](https://user-images.githubusercontent.com/140617/218073537-715b74fe-073a-4aee-a90d-99b664c8811e.png)

P.S. Ugh, that red error color needs to be fixed.

**Comment by elioqoshi** [comment]
I'd propose something like this as a warning. Red is a critical error semantic and too alarming for this.

![grafik](https://user-images.githubusercontent.com/5436686/218084464-4fb34a13-7bcf-4649-ab92-0a9af57eff3d.png)

**Comment by elioqoshi** [comment]
Bonus: We can update the label to be more specific that it downloads something:

`Download and install support for additional media formats`

![grafik](https://user-images.githubusercontent.com/5436686/218084820-31685388-e789-4903-882b-ae4659088eaa.png)

**Comment by jpnurmi** [comment]
I guess a red warning makes sense when running on battery because it could be dangerous if you run out of battery at a critical moment. Anyway, there's a chance that a system is both offline and on battery at the same time. Would you show both messages in a column, for example?

**Comment by dbungert** [comment]
From that mockup I'm not sure the relationship between being offline and the codecs checkbox is going to be clear.  What about moving the warning closer to the checkbox?  Maybe the user does want the codecs but just skipped the network step and they plan to resolve it later, that should indicate that setting up network would give the option to fix the problem.

**Comment by kenvandine** [comment]
I agree with @dbungert, it would also be cool to be able to take them back to the page to connect to wifi.

**Comment by elioqoshi** [comment]
We can move the label closer to the option:

![grafik](https://user-images.githubusercontent.com/5436686/218253452-18cd6fe4-f22b-4006-bb72-70d7b28c0098.png)


I do not think we need another option for connecting to the wifi beyond the user going back manually, as that was a user's deliberate choice.

**Comment by jpnurmi** [comment]
@elioqoshi Could it be an option to show the warning in a tooltip instead when hovering the disabled checkbox?

The content fits nicely in English but we'll run into issues that the labels start wrapping to multiple lines when using other languages. Also, if you happen to be on battery at the same time, the screen starts feeling somehow a bit too busy with all these warning labels here and there... :)

![image](https://user-images.githubusercontent.com/140617/218777642-14527392-4796-43f3-8daf-68d1dc3c41b7.png)

**Comment by dbungert** [comment]
I'm not too particular about the exact fix, I was just imagining the user looking at the disabled checkbox area and not knowing why.  A tooltip also sounds like a good solution, I think that would be a natural action. to hover the disabled entry.

**Comment by elioqoshi** [comment]
@jpnurmi I think that would be a good alternative too

**Comment by jpnurmi** [comment]
@elioqoshi does this look ok to you?

[Screencast from 2023-02-15 09-25-57.webm](https://user-images.githubusercontent.com/140617/218973031-90d3a27d-b9dd-4871-8deb-654d65b641d1.webm)

**Comment by jpnurmi** [comment]
I tried to make it look similar to the original proposal. The main difference is that as a floating tooltip, it won't take space in the layout.

| Light | Dark |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/218975458-1059a07e-c6bd-4033-8d7d-3507e56bbd6e.png) | ![image](https://user-images.githubusercontent.com/140617/218975424-d4a38b9b-6b1d-4bb6-b6eb-5682db8925db.png) |
