### ISSUE TITLE
"Continue" button on try/install page is unnecessary

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1403]
On the page "Try / Install" the "Continue" button is not necessary since Try and Install actions are already huge buttons and it should just continue to next step when clicked.

![image](https://user-images.githubusercontent.com/1928546/218703063-c03a144d-0299-462c-b728-5832623f3a68.png)

**Comment by jpnurmi** [comment]
It bothers me too that we force the user move back and forth between the huge cards and the continue button. :)

I once tried out of curiosity leaving out the _Continue_ button. The problem is that it moves the _Go Back_ button to a wrong place, right where the _Continue_ button is on the page before and after. Would it make sense to keep a useless disabled _Continue_ button there just to avoid that the _Go Back_ button moves to a wrong place?

![image](https://user-images.githubusercontent.com/140617/218710990-05156f30-0bb9-4197-9c7f-04ac573bcee1.png)

/cc @elioqoshi

**Comment by elioqoshi** [comment]
I had some thinking about this and I don't think the behaviour is ideal and maybe we want to rethink the installation option screen.

**Comment by elioqoshi** [comment]
I checked with @lyubomir-popov as well and I think he is right that the illustrations are not helping with the cognitive load here. I'd like to explore alternative ways we could optimize that screen.

First thing would be to replace the big cards with traditional radio buttons:

![grafik](https://user-images.githubusercontent.com/5436686/218739005-fb36bca5-ad5b-4d93-8ca8-6f142524df05.png)

The problem with I'd say is that it lacks gravitas as it's one of the main screens in the installation flows, as well we lose an opportunity to show off Ubuntu's visual identity.

A similar UX pattern, but differently laid out would be this:

![grafik](https://user-images.githubusercontent.com/5436686/218738544-843812b7-b545-48ad-ae3d-41b27b2ae81b.png)

This would be a different pattern from other screens but I'd argue that this could be justified for this particular screen. 

What do you think? cc @local-optimum

**Comment by local-optimum** [comment]
Whilst I agree the continue button is an unnecessary step I don't think this is something we necessarily need to action and I quite like the current setup.

That said the final mockup in Elio's comment looks quite classy and I would happy with this route

@jpnurmi @elioqoshi please don't forget to ensure that any Ubuntu logos used throughout are the new logo. The Try or Install illustrations are using an out of date logo so if we keep the current approach please make sure we have updated replacements for those images.

**Comment by elioqoshi** [comment]
> please don't forget to ensure that any Ubuntu logos used throughout are the new logo. The Try or Install illustrations are using an out of date logo so if we keep the current approach please make sure we have updated replacements for those images.

Yeah I was starting to update them and rethought this whole flow thinking that the icons are too much cognitive-load.

**Comment by elioqoshi** [comment]
One argument I'd have to require the user to select the option first before continuing is that a little bit of friction is well placed here as it's a critical choice it also avoids the user misclicking

**Comment by elioqoshi** [comment]
This is not relevant anymore with the new designs
