### ISSUE TITLE
crash when attempting to write to disk

### ISSUE THREAD

**Issue by dbungert** [canonical/ubuntu-desktop-installer#141]
I'm able to observe a UI crash when getting ready to write to disk:

1) impish daily canary, July-8 with md5 3c806e78d5af0140707433b98d6938e7
2) qemu like so: kvm -no-reboot -drive file=/path/impish-test.img,format=raw,cache=none,if=virtio -m 8192 -cdrom /srv/iso/impish/impish-desktop-canary-amd64-2021-07-08.iso -nic user,model=virtio-net-pci
3) 'try ubuntu'
4) snap refresh ubuntu-desktop-installer
5) apt install cloud-init
6) systemctl restart snap.ubuntu-desktop-installer.subiquity-server.service
7) finally run ubuntu-desktop-installer
8) accept all default options

flutter: type 'Null' is not a subtype of type 'String'                                                                               
flutter: #0      new _DiskObject.fromJson (package:ubuntu_desktop_installer/pages/write_changes_to_disk_page.dart:35)                
flutter: #1      _WriteChangesToDiskPageState.build (package:ubuntu_desktop_installer/pages/write_changes_to_disk_page.dart:133)     

See also attached logs
[subiquity-server-debug.log](https://github.com/canonical/ubuntu-desktop-installer/files/6786372/subiquity-server-debug.log)
[udi.log](https://github.com/canonical/ubuntu-desktop-installer/files/6786373/udi.log)

**Comment by oSoMoN** [comment]
I can confirm the problem, when running the latest ubuntu-desktop-installer snap from the edge channel in a fully up-to-date impish VM.  Relevant log:

    flutter: Storage config: [
      {
        "ptable": "gpt",
        "serial": "VBOX_HARDDISK_VB6fca352b-ba4cbf74",
        "path": "/dev/sda",
        "wipe": "superblock-recursive",
        "preserve": false,
        "name": "",
        "grub_device": true,
        "type": "disk",
        "id": "disk-sda"
      },
      {
        "device": "disk-sda",
        "size": 1048576,
        "flag": "bios_grub",
        "number": 1,
        "preserve": false,
        "type": "partition",
        "id": "partition-0"
      },
      {
        "device": "disk-sda",
        "size": 21471690752,
        "wipe": "superblock",
        "flag": "",
        "number": 2,
        "preserve": false,
        "type": "partition",
        "id": "partition-1"
      },
      {
        "fstype": "ext4",
        "volume": "partition-1",
        "preserve": false,
        "type": "format",
        "id": "format-0"
      },
      {
        "path": "/",
        "device": "format-0",
        "type": "mount",
        "id": "mount-0"
      }
    ]
    flutter: type 'Null' is not a subtype of type 'String'
    flutter: #0      new _PartitionObject.fromJson (package:ubuntu_desktop_installer/pages/write_changes_to_disk_page.dart:63)
    flutter: #1      _WriteChangesToDiskPageState.build (package:ubuntu_desktop_installer/pages/write_changes_to_disk_page.dart:136)

**Comment by oSoMoN** [comment]
In udi.log, the JSON entry with type "disk" doesn't have a "serial" property. @dbungert is that expected, or something missing in subiquity?

In my case, the missing property is "wipe" on the entry with type "partition".

In both cases we can handle more gracefully missing properties, but I'd like to understand whether this is valid input.

**Comment by dbungert** [comment]
@oSoMoN - as far as I know, real disks should have serial numbers, but as soon as we assume that someone's install is going to fail in a bad way.  In my experience, qemu disks don't have a serial unless you give it one - though I'm only seeing the serial option in the virt-install manpage, not qemu-system-x86_64, so let me explore.

Curtin has mixed opinions on needing the serial or not.  Some places in the code require it, other places are willing to work with one of several values.

**Comment by dbungert** [comment]
You also asked about 'wipe'.  It is not necessarily going to always be present - for instance maybe there are multiple disks, we're probably not wiping them all.  This page might help: https://curtin.readthedocs.io/en/latest/topics/storage.html
