### ISSUE TITLE
Installation complete

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1448]
It's too greedy with the margins :) make them relative

![image](https://user-images.githubusercontent.com/140617/220418444-66240909-f4b0-4d29-82a4-b1dc4a51a1c5.png)

**Comment by SohilBhanani** [comment]
Hi, I would like to contribute, Whom should I mention in **Please add the Canonical Project Manager or contact**? Thankyou

**Comment by jpnurmi** [comment]
Hi, thanks for your interest, and welcome! As far as I know, it's just a sanity check. Feel free to put my name there, it has done the trick before. :)

**Comment by SohilBhanani** [comment]
Hi thankyou it worked for me as well and It will help me for future contributions.
