### ISSUE TITLE
Differ animations for buttom buttons across screens

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1466]
While the slide and fade out animations feels quite crisp, it might look a bit more coherent with the buttom buttons (Go Back, Continue) not animating, as they are consistently at the same place. Them moving and being replaced by the same buttons feels rather awkward.

[Screencast from 2023-02-25 16-37-24.webm](https://user-images.githubusercontent.com/5436686/221368719-9f747d16-8660-4b8d-bf62-caba067d265a.webm)

**Comment by jpnurmi** [comment]
The original idea was to smoothen the transition from "Continue" to a highlighted "Start installing" that can be double the size in some languages.

![image](https://user-images.githubusercontent.com/140617/221369020-d5c38bf9-b7c5-498e-a7a7-2d8e1ebf637d.png)
![image](https://user-images.githubusercontent.com/140617/221369024-968f7063-19c2-4fb4-8b24-8d8053880e05.png)

**Comment by jpnurmi** [comment]
I must add that the page transitions were different back then. Flutter had some rather subtle vertical page transitions during the early days of the installer.

At some point, thanks to Android and Material design changes, the default page transitions were changed in Flutter. The new transitions felt out of place in the installer. We tried iOS-style horizontal slide transitions for a while but they had a bit too strong mobile phone feeling so we came up with the shorter horizontal transitions we have today.

That's the history. :)

**Comment by elioqoshi** [comment]
Yeah I get that. Would it be possible to use different animations for these buttons than the content uses?

**Comment by jpnurmi** [comment]
Yes, we can try different animations :)

**Comment by jpnurmi** [comment]
I hope we don't need different animations now that the button sizes have been made stable and the bottom bar is no longer animated:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1485
