### ISSUE TITLE
redesign 'Go Back' and 'Continue' buttons

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1467]
Currently the primary and secondary button are styled similarly. Is there any background why the primary button is not styled as such (green)? @jpnurmi 

Considering that primary button is reserved for the one time Installation is started, could we see to distinguish Go Back and Continue with other kinds of buttons?

![image](https://user-images.githubusercontent.com/5436686/221368858-ffec5dc3-c459-4540-b031-74d761731241.png)

**Comment by jpnurmi** [comment]
I don't know the background but the pattern is that buttons that modify the system are highlighted. "Go Back" and "Continue" are basically just navigating.

![image](https://user-images.githubusercontent.com/140617/221371865-d3bd5930-a48d-4c84-95cb-fb9abcc9f9a8.png)
![image](https://user-images.githubusercontent.com/140617/221371838-216abbee-458f-41e4-bc69-53516a12bbfe.png)
![image](https://user-images.githubusercontent.com/140617/221371848-281a6886-3298-43a8-b52d-476cd148efa8.png)
![image](https://user-images.githubusercontent.com/140617/221371946-bc943efb-c6a7-4139-b579-2fd4a923b465.png)

**Comment by elioqoshi** [comment]
I'd still recommend we distinguish Go Back from Continuing. Can we use buttons without any outlines for Go Back maybe? What are the available button styles we have at our disposal again?

**Comment by elioqoshi** [comment]
Since we are talking about this: ![grafik](https://user-images.githubusercontent.com/5436686/221372549-e0825493-1bd3-484d-a6f4-cdb08f5b25db.png)

This is likely my fault, however the order of Primary and Secondary button is inverted in the 'Continue Testing' screen. We should use the usual order, so "Secondary | Primary"

**Comment by elioqoshi** [comment]
Thanks!

Can I propose to use Text buttons for secondary actions (Go Back) and filled buttons for primary actions (Continue)?

**Comment by jpnurmi** [comment]
Sure, here's how that combination would look:

![image](https://user-images.githubusercontent.com/140617/221519494-bed5c140-01b6-4ba7-85ee-b5f14b496a56.png)

**Comment by elioqoshi** [comment]
I think that looks better, though are we set on the accent color for the text button? The issue that might create is that it looks highlighted.

**Comment by jpnurmi** [comment]
The looks come from Yaru and [M3](https://m3.material.io/components/buttons/overview) but we could either propose changes in Yaru or customize it locally in the installer.

**Comment by jpnurmi** [comment]
![image](https://user-images.githubusercontent.com/140617/221524432-fe59445a-e462-465a-a8d4-0382c921edf1.png)

**Comment by jpnurmi** [comment]
Should it look like an outlined button but without the outline?

[Screencast from 2023-02-27 10-33-03.webm](https://user-images.githubusercontent.com/140617/221526929-ee5e6f30-b808-48ce-bfb2-a69442fa3277.webm)

**Comment by jpnurmi** [comment]
I like this a lot especially if we make the buttons not animate :)

[Screencast from 2023-02-27 12-07-57.webm](https://user-images.githubusercontent.com/140617/221548360-43109923-6868-4f69-93d0-83edbc2eec82.webm)

For reference, with animations:

[Screencast from 2023-02-27 12-06-49.webm](https://user-images.githubusercontent.com/140617/221548486-31a16ced-c10a-4a1a-9fce-b0de3a9a4e44.webm)

**Comment by elioqoshi** [comment]
Yes! I do think it's an improvement. Let me mull it over a bit and peer review with other from UX for a bit longer before deciding on something here.

**Comment by jpnurmi** [comment]
Also, removing the outline from the _Go Back_ button makes it feel less disturbing that it jumps when the _Continue_ button is replaced by a _Start Installing_ button without animation.

[Screencast from 2023-02-27 12-14-22.webm](https://user-images.githubusercontent.com/140617/221549752-cee81d61-03b4-4915-9774-4c824d13f1d8.webm)

**Comment by elioqoshi** [comment]
@jpnurmi Could you show an example, for comparison, with a Secondary button in outline and primary button filled?

**Comment by jpnurmi** [comment]
Here's the variant with an outlined back button.

[Screencast from 2023-02-27 12-26-06.webm](https://user-images.githubusercontent.com/140617/221552000-110a71f9-0596-4115-9ede-5efde7ccde82.webm)

I don't know if it's just me but the outline, even if it's so subtle, makes the jump somehow stand out. With the outline removed it doesn't stand out nearly as much because you can't see the exact boundaries anyway.

**Comment by elioqoshi** [comment]
Thanks @jpnurmi ! I see what you mean. I would not prioritize the animation completely here if we think that statically it makes more sense but I think we should go with 1 of these 2 solutions. Will think a bit more about it

**Comment by elioqoshi** [comment]
So I am confident we should go with this:

- Secondary Button (i.e Back) is Outlined
- Primary Button (i.e Continue) is Filled (or in the case of Install) Elevated.
- Buttons have a minimum width of xxx pixels (Still thinking what that should be, maybe 120-150px?)
- If buttons are laid out as navigation buttons (i.e a wizard like here), they should be laid out left and right, as it's a linear representation and works better with the page indicator. I.e:

<img width="795" alt="grafik" src="https://user-images.githubusercontent.com/5436686/221827450-930ffb75-21b3-4d37-b02c-1b3547834277.png">

**Comment by jpnurmi** [comment]
> Buttons have a minimum width of xxx pixels (Still thinking what that should be, maybe 120-150px?)

I tested 120px and didn't notice it getting stretched in any language but it's on the borderline. It's probably safer to make it slightly wider than 120px.

> If buttons are laid out as navigation buttons (i.e a wizard like here), they should be laid out left and right, as it's a linear representation and works better with the page indicator. I.e:

Btw, there's still that one remaining info label that we need to move out of the way. :)

![image](https://user-images.githubusercontent.com/140617/221829164-cea52ab0-5f75-44ef-b018-0708a9131514.png)

**Comment by elioqoshi** [comment]
Sorry for revisiting this, though the more I look at it, the more I think filled buttons should be filled and not outlined, as the current filled buttons on light theme makes the buttons look disabled. I'd propose to make the fill darker (E5E5E5) and remove the border for all filled buttons in the installer. 

example:
![grafik](https://user-images.githubusercontent.com/5436686/221866337-0c672522-364a-4615-895a-52d4ce8bdc44.png)
