### ISSUE TITLE
Redesign Windows Bitlocker screen

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1469]
The Windows Bitlocker screen is quite neutral and could benefit from an improved layout, as well as semantic Warning/Information

![image](https://user-images.githubusercontent.com/5436686/221369503-6cda78d8-d49d-4997-819a-dca8c762d84c.png)

(TODO for @elioqoshi )

cc @local-optimum it's also rather not ideal looking that help.ubuntu.com/bitlocker links to our Discourse:
https://discourse.ubuntu.com/t/ubuntu-installation-on-computers-running-windows-and-bitlocker-turned-on/15338.

It doesn't feel well thought-through and at worst could make people distrust us. Can we spin up a proper tutorial page for this?

**Comment by elioqoshi** [comment]
Also, as a note, there is no Confirmation dialog after this screen. The machine restarts right away. We would likely need to introduce a little friction here to allow for user errors.

**Comment by elioqoshi** [comment]
After going through this process myself, I am not sure if I did something wrong because of being careless or because the instructions are unclear. It seems that I have overwritten my Windows installation (fresh Windows 10 Pro coming with my Intel NUC). Luckily I had nothing important there yet as it's for testing purposes, but I wonder how this could play out for end-users.

@local-optimum @jpnurmi Could we investigate this a bit further? Unless I did something completely wrong, this seems rather crucial to address.

**Comment by jpnurmi** [comment]
@elioqoshi Could you ZIP and attach the logs in `/var/log/installer` please? If Windows was correctly detected, it should have by default offered to install Ubuntu _alongside_ Windows:

![image](https://user-images.githubusercontent.com/140617/221495410-b44b4b09-5fac-49e0-8cfc-dc72193d1777.png)
![image](https://user-images.githubusercontent.com/140617/221495432-180e906d-906c-4244-af62-5170ec8ebbb5.png)

**Comment by jpnurmi** [comment]
P.S. If we decide to redesign the page, _Turn off RST_ currently looks the same :)

![image](https://user-images.githubusercontent.com/140617/221496019-47099c31-898c-4281-91c2-1b60196c8ddb.png)

**Comment by elioqoshi** [comment]
Correct me if I am not mistaken, but if Bitlocker is on, Ubuntu can't recognize there is a Windows installation, no? @jibel ?

I will have a look and for the log files

**Comment by kenvandine** [comment]
@linjuiche can you please test this flow to ensure we don't allow formatting a windows disk that has bitlocker enabled.  This bug shows we may have an issue there.

**Comment by linjuiche** [comment]
@elioqoshi 
Could you please provide information for the following question to help me clarify the issue and try to reproduce it?
1. Did you go to WIndows and disable bitlocker after you see "Turn off bitlocker" page?
2. After you turn off bitlocker in WIndows, did you reboot again to Windows to see if it could boot to WIndows successfully?

**Comment by elioqoshi** [comment]
@linjuiche 

I attempted to Restart into Windows after that page, however Windows was already wiped then. Ubuntu was installed without any Windows partition left, so that screen was not describing the reality of the actions.

**Comment by linjuiche** [comment]
@elioqoshi OK. Could you please advise the image is downloaded against which daily build?

**Comment by jpnurmi** [comment]
We can fix this by changing the page order. It was not a good idea to have the confirmation screen before the bitlocker screen. I'm glad this got caught now and Elio didn't lose anything critical.

**Comment by elioqoshi** [comment]
@linjuiche I used the daily build of last Friday, 24 February.

**Comment by linjuiche** [comment]
@elioqoshi I assume you click "Restart into Windows" Buttons right?

**Comment by elioqoshi** [comment]
@linjuiche Yes. It restarted into Ubuntu afterwards. At first I thought there was something wrong with the boot order, but there was no Windows to boot from.

**Comment by elioqoshi** [comment]
Quick mockups here to improve the layout of the Bitlocker screen. I am still trying out various QR formats to give it a bit more Ubuntu character still.

![grafik](https://user-images.githubusercontent.com/5436686/222359137-e384c89e-422e-4fdd-846b-1d45f16ef8c9.png)

We should also introduce a confirmation dialog prior to restarting the computer to ensure the user consents to it (text is a draft, need some polish)

![grafik](https://user-images.githubusercontent.com/5436686/222359277-f7daadf6-11a3-4279-9ca5-bdec3a3890de.png)
