### ISSUE TITLE
After install can not update - sources.list contains only one line

### ISSUE THREAD

**Issue by corradoventu** [canonical/ubuntu-desktop-installer#1471]
Install was successful but terminates with an error: https://bugs.launchpad.net/subiquity/+bug/2008546
sources.list contains only one line: deb [check-date=no] file:///cdrom lunar main restricted

**Comment by corradoventu** [comment]
Should be solved by fix for bug 2008546

**Comment by jpnurmi** [comment]
Thanks! Subiquity has been updated. The fix will be available in the next daily image.

- https://github.com/canonical/ubuntu-desktop-installer/pull/1472
