### ISSUE TITLE
Redesign Layout for Try or install page

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1482]
Proposed changes to the try or install page based on prior conversations:

![grafik](https://user-images.githubusercontent.com/5436686/221848151-cfc14855-61a1-4864-a5c5-ebe19f3cb129.png)

- Remove the illustration icons which are not really adding to understanding the options
- Turn the cards into actual radio buttons
- Other small changes (this includes the new proposed button layout)

**Comment by elioqoshi** [comment]
This is related to https://github.com/canonical/ubuntu-desktop-installer/issues/1403

**Comment by jpnurmi** [comment]
P.S. I found one more option, "Repair installation", which has been commented out because the operation is not supported by the backend yet.

![image](https://user-images.githubusercontent.com/140617/221853861-762b83c9-a4ce-4922-887f-63ac6166be9b.png)

**Comment by elioqoshi** [comment]
Sure, layout would be similar:

![grafik](https://user-images.githubusercontent.com/5436686/221859172-67d74d93-7973-4310-aab1-be7a71dbf147.png)

**Comment by elioqoshi** [comment]
As @local-optimum mentioned, we should change the order of the items to 

1. Install
2. Try
3. Repair

![grafik](https://user-images.githubusercontent.com/5436686/222083358-fd57864e-7a4b-435a-a741-eb11e3896e6b.png)
