### ISSUE TITLE
Remove title bar background

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1483]
I am wondering if it would work out well to remove the title bar background on all screens (similar to the slideshow) and have a divider instead.

![grafik](https://user-images.githubusercontent.com/5436686/221863868-ae3b5678-e686-4cee-b609-eb29b0b3111f.png)

Not deciding we should do it but I think it might be an interesting approach to get rid of the window chrome and allow viewers to focus on the content

**Comment by elioqoshi** [comment]
I think this works pretty well in the context of the installer, as it allows to focus on the content and not the window chromes.

Here is a quick mockup of a left-aligned layout:
![grafik](https://user-images.githubusercontent.com/5436686/221865549-078ec0ab-b970-43fe-ac62-5da8e8e0c4e0.png)

**Comment by jpnurmi** [comment]
Or, should I say, is the default frame from Yaru fine? It doesn't have gaps on the sides

![image](https://user-images.githubusercontent.com/140617/222202561-7dd966a1-6e29-462f-a506-d251563a90db.png)

![image](https://user-images.githubusercontent.com/140617/222202594-c2e733ed-919c-47dd-b635-c3fd5b0d59b6.png)

**Comment by jpnurmi** [comment]
Dialogs:

![image](https://user-images.githubusercontent.com/140617/222202843-93f56494-07a1-4813-8754-8b338d40da16.png)

![image](https://user-images.githubusercontent.com/140617/222202804-1624275e-c140-4eb3-a256-85b20e78d83d.png)

**Comment by elioqoshi** [comment]
I think the divider with no margins is okay, yes
