### ISSUE TITLE
Updated language selection input and button layout

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1488]
I think we can squeeze a bit of a better layout of the language selection screen. Quick mockup:

![grafik](https://user-images.githubusercontent.com/5436686/221947432-8f4e447c-41e4-4c00-8a1c-a73454c6cda1.png)

That would include:
- Text input and keyboard detection button horizontally laid out to save some vertical spacing
- Higher language selection frames to compensate.

What do you think? @jpnurmi

**Comment by jpnurmi** [comment]
Much better! :+1:
