### ISSUE TITLE
New layout and copy for 'No space' available screen

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1489]
The layout and copy for the 'no space available' screen is really dry. 

![grafik](https://user-images.githubusercontent.com/5436686/221948565-b02c2dba-f365-4f9e-8fc9-03ee070d1479.png)

We should improve the copy here as well as the layout, maybe adding an illustration as well.

I will come up with a proposal.

**Comment by elioqoshi** [comment]
@jpnurmi Can you remind me when this screen is triggered? Why can't the user go back here?

**Comment by jpnurmi** [comment]
The new installer doesn't have a design for this page so it was copied from Ubiquity. The page comes after _Connect to internet_, before _Updates and other software_.

[Screencast from 2023-02-28 20-07-51.webm](https://user-images.githubusercontent.com/140617/221954351-2139d42c-f167-4542-b05a-0fb05df9da9f.webm)

**Comment by jpnurmi** [comment]
Fixed by
- https://github.com/canonical/ubuntu-desktop-installer/pull/1638
