### ISSUE TITLE
Save & restore scrolling positions

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1499]
We could try using the state restoration framework to avoid losing scrolling positions even if navigating backward.

[Screencast from 2023-03-01 14-34-14.webm](https://user-images.githubusercontent.com/140617/222214652-bdec63c9-ff83-4ac2-b458-571edf98f693.webm)

**Comment by elioqoshi** [comment]
This will be less relevant after the keyboard layout screen is updated, but we could have a look at this post-UI freeze
