### ISSUE TITLE
Partition dialog size constraints

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1502]
![image](https://user-images.githubusercontent.com/140617/222221474-1308aa21-1924-4610-8c71-1d6b38af99aa.png)

**Comment by jpnurmi** [comment]
@elioqoshi is 600px a reasonable width for this kind of dialog or does it look too stretched when it's empty?

![image](https://user-images.githubusercontent.com/140617/223186447-0c3b1ae4-4766-43bf-bfd4-dd1cd068e6d8.png)

**Comment by elioqoshi** [comment]
@jpnurmi Yeah, growing the dialog dynamically is really awkward.

How about a much bigger width but not confine all the elements inside to the same width?

![grafik](https://user-images.githubusercontent.com/5436686/223363379-790cc38e-4428-4e9c-88a6-4e746a964df5.png)
