### ISSUE TITLE
Mount point validation

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1505]
Client vs. server side?

![image](https://user-images.githubusercontent.com/140617/222231086-6e142850-fa0a-4c8d-beac-625bf6f7973d.png)

**Comment by elioqoshi** [comment]
@dbungert Should Subiquity handle validation?

**Comment by dbungert** [comment]
For reference, the TUI:

A suggested list of mountpoints, including leaving unmounted:
![image](https://user-images.githubusercontent.com/235157/222444427-a4209b3f-6b82-4637-bbed-cc5816faee12.png)

Choosing "other" provides a text input field, but puts a '/' in front:
![image](https://user-images.githubusercontent.com/235157/222444638-97de8097-6fda-4833-b95b-e0f4f118ff16.png)

The challenge with up-front validation of the mountpoint is, for the arbitrary mountpoint case, we don't know if the listed directory will exist or not.  This screen is running before partitioning has happened, knowledge about if a particular mount point is valid will be after partitioning and rsync.

**Comment by jpnurmi** [comment]
The GUI has similar suggestions but in the end, the user is able to type anything.

![image](https://user-images.githubusercontent.com/140617/222446242-0e69484d-45e4-4c84-b7e4-37452b978d35.png)

**Comment by jpnurmi** [comment]
Ubiquity seems to have some validation there

![image](https://user-images.githubusercontent.com/140617/222448463-eef8ed84-e268-4b99-b072-7719832c2a50.png)
![image](https://user-images.githubusercontent.com/140617/222448485-e0d4fe98-6c24-4b89-a0fc-1d33aedf1fd0.png)
