### ISSUE TITLE
Still has Kudu instead of Lobster Branding 

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#1523]
Hey!

Helping to test todays Alpha image: http://cdimage.ubuntu.com/daily-live/20230303/lunar-desktop-amd64.iso during the Alpha test week, and noticed the installer still have Kinetic Kudo instead of Lunar Lobster branding but maybe that is expected at this stage?

Also the installer crashed after i choosed dark mode on the choose light/dark mode screen and had to be restarted so i had to re run it all again (but after that it seems to work) also getting a bunch of System Program Error detected popups

**Comment by jbicha** [comment]
These are two separate issues. Please file separate bugs.

**Comment by bittin** [comment]
@jbicha alright done

**Comment by kenvandine** [comment]
We don't have the new mascot yet, we'll get that before UI freeze.

**Comment by jpnurmi** [comment]
Fixed by
- https://github.com/canonical/ubuntu-desktop-installer/pull/1633
- https://github.com/canonical/ubuntu-desktop-installer/pull/1637
- https://github.com/canonical/ubuntu-desktop-installer/pull/1598

**Comment by bittin** [comment]
installation failed today, but maybe i am too early again, has the right branding now atleast but not fully Swedish yet as my Weblate submissions from yesterday evening has not been submitted yet
