### ISSUE TITLE
Installer crashes when choosing dark mode

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#1524]
The installer crashed after i choosed dark mode on the choose light/dark mode screen and had to be restarted so i had to re run it all again (but after that it seems to work) also getting a bunch of System Program Error detected popups

**Comment by jpnurmi** [comment]
How did the installer crash? Did the window disappear or what happened? Did you get any error popups at that point?

**Comment by bittin** [comment]
not anymore
