### ISSUE TITLE
Slideshow should be resized when installer in full-screen

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1525]
Lunar 20230303

### Test Case
1. Boot the iso and select "Install Ubuntu" on the first selection screen to skip the live session
2. The installer starts in full-screen mode. 
3. Proceed with all the stage up to the slideshow
4. The slideshow is not resized and is stuck on the top center of the page

![image](https://user-images.githubusercontent.com/1928546/222737462-fda39358-0792-49e7-aa7d-c8e29248ecfe.png)

**Comment by bittin** [comment]
and also the bug for the picture behind so big and hiding some of the text is back 
![VirtualBox_Ubuntu 23 04 Test Week_06_03_2023_10_53_45](https://user-images.githubusercontent.com/43197/223078428-5b9a431e-a182-4ee8-a106-b10ab214aef0.png)

**Comment by jpnurmi** [comment]
We have new, more scalable installation slides coming in the near future. :wink:

**Comment by bittin** [comment]
> We have new, more scalable installation slides coming in the near future. wink

perfect :)
