### ISSUE TITLE
"$Ubuntu" in successful installation message.

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1526]
Lunar 20230303

There is a "$Ubuntu" in the successful installation message in French (I didn't check in English) 
![image](https://user-images.githubusercontent.com/1928546/222738138-a6ee7903-5e0f-43b8-92d4-ab1c2528f782.png)

**Comment by jpnurmi** [comment]
Thanks, fixed on Weblate! Now I can proudly say that I've participated in the French translation. :)

### Before
![Screenshot from 2023-03-03 16-12-44](https://user-images.githubusercontent.com/140617/222756552-e1a95b57-e9dd-46f7-96c6-70230e8ccd75.png)

### After
![Screenshot from 2023-03-03 16-13-07](https://user-images.githubusercontent.com/140617/222756570-a563b4c4-598e-4c39-b981-a8fa5c891081.png)

**Comment by jpnurmi** [comment]
Fixed by #1531

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/223063078-2501218c-fa10-4bde-a492-ce1acfef5580.png) | ![image](https://user-images.githubusercontent.com/140617/223063253-8f58aaf9-9c3b-4810-9b29-d0d34827bef8.png) |
