### ISSUE TITLE
Disable screensaver, screen blanking, power manager?

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1543]
Ubiquity:
```py
        self.disable_volume_manager()
        self.disable_screensaver()
        self.disable_screen_blanking()
        self.disable_powermgr()
```
https://git.launchpad.net/ubiquity/tree/ubiquity/frontend/gtk_ui.py#n842

**Comment by sergio-costas** [comment]
The key value to disable the screensaver seems to be org/gnome/desktop/session/idle-delay=0

**Comment by d-loose** [comment]
We still need to take care of disabling some power management features. As mentioned [here](https://github.com/canonical/ubuntu-desktop-installer/pull/1554#issuecomment-1459963020) we can't disable the entire plugin anymore by changing a single gsettings value.
Is there an alternative way to disable it? Otherwise we could temporary disable `idle-dim` and `sleep-inactive-*-timeout` in gsettings.

**Comment by sergio-costas** [comment]
I would check what VLC or MPV do to disable the screensaver...

**Comment by sergio-costas** [comment]
Ok, I'm checking the MPV code and it's not so easy... there are three paths valid for linux: X11, Wayland and SDL. X11 and Wayland have very low-level functions, requiring direct access to the X11/Wayland descriptors...

![imagen](https://user-images.githubusercontent.com/105285003/223986920-a93a460e-4c62-43d8-a3c1-d1859ab5a2fd.png)

![imagen](https://user-images.githubusercontent.com/105285003/223987071-cc13cbfa-470c-4b37-941f-43a010f38aa6.png)

**Comment by sergio-costas** [comment]
And SDL, being a low-level layer, probably does the equivalent... so, back at square one.

**Comment by d-loose** [comment]
`org.gnome.SessionManager` provides [this](https://lira.no-ip.org:8443/doc/gnome-session/dbus/gnome-session.html#org.gnome.SessionManager.Inhibit)

**Comment by d-loose** [comment]
I'm adding this to [ubuntu_session.dart](https://github.com/canonical/ubuntu_session.dart/pull/7)
