### ISSUE TITLE
WSL Screen 1 - Select your language

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#155]
This is the design for the stage "**Select your language**" of WSL OOBE.
Master issue: #160 

![WSL Screen 1 - Language](https://user-images.githubusercontent.com/1928546/125322820-7415df00-e33e-11eb-9f31-a3ac05406018.png)

Design specification: https://people.canonical.com/~platform/desktop/installer/WSL/#s0

**Comment by jpnurmi** [comment]
Just wanted to check because I was going to re-use the same page as is, but then I noticed that the text is different.
