### ISSUE TITLE
Language choosing gets wrong

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#1550]
Is it known that the installer sometimes decides to choose English even if i choose Swedish? 
some screens in it sometimes randomly changes back to English

Logs:

https://pastebin.com/ewcSDYNH 
https://pastebin.com/XXabeMWW

**Comment by jpnurmi** [comment]
Thanks, I was able to reproduce the issue. I had Swedish selected when entering the timezone page.

![image](https://user-images.githubusercontent.com/140617/223417571-8460e121-7dcb-47ab-8e39-a01e15888699.png)
