### ISSUE TITLE
WSL Screen 2 - Profile setup

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#156]
This is the design for the stage "**Profile setup**" of WSL OOBE. 
Master issue: #160 

Default
![WSL Screen 2 - Identity](https://user-images.githubusercontent.com/1928546/125323410-09b16e80-e33f-11eb-917d-44bf6cdca7f1.png)

Filled
![WSL Screen 2 - Identity filled](https://user-images.githubusercontent.com/1928546/125323423-0f0eb900-e33f-11eb-9e5f-b43b094b55f4.png)

Design specification: [Default](https://people.canonical.com/~platform/desktop/installer/WSL/#s1
), [Filled](https://people.canonical.com/~platform/desktop/installer/WSL/#s5)

**Comment by jpnurmi** [comment]
Should it have input validation similarly to the [Who are you](#40) page?

- error labels for invalid inputs (invalid username, password mismatch)
- green check marks for valid fields
- password strength label

**Comment by jibel** [comment]
On 13/07/2021 09:35, J-P Nurmi wrote:
>
> Should it have input validation similarly to the Who are you <#40> page?
>
>   * error labels for invalid inputs (invalid username, password mismatch)
>   * green check marks for valid fields
>   * password strength label
>
Yes to the 3 points. The pages are identical in behaviour. The main 
difference is that there is no "hostname" for WSL.

**Comment by jibel** [comment]
The "real name" is actually missing from this page. It is a required field.

**Comment by jpnurmi** [comment]
Ok, let's add that right away
