### ISSUE TITLE
Installer accent colours do not match OS accent colors

### ISSUE THREAD

**Issue by tim-hm** [canonical/ubuntu-desktop-installer#1560]
(1) has the hex colour `#E95420` while (2) has the hex colour `#E95622` but I assume these should be a perfect match?

I have sampled a few other OS-level accent colours, which do correctly update the installer's accent colours, but found that some match and some do not.

<img src="https://user-images.githubusercontent.com/1335525/223746352-20864b84-e3ef-487b-80df-8f06312ad818.png" width="400">

**Comment by elioqoshi** [comment]
@jpnurmi is this something which needs to be audited in Yaru, or did we change something in the installer that this happened? I assume it was some color picker issue someone might have accidentally done and it stuck around.

**Comment by jpnurmi** [comment]
The colors have been renamed and moved around many times but I think these are the ones that were originally added to yaru.dart

- olive `#4B8501`
- bark `#787859`
- viridian `#03875B`
- purple `#8856EB`
- red `#E61D34`
- blue `#0073E5`
- magenta `#BC33DB`

The [commit](https://github.com/ubuntu/yaru.dart/commit/d8a975e10f6871452da8737f2aa9053ebabf27b0) says the values came from:

- https://github.com/ubuntu/yaru/pull/3486

**Comment by jpnurmi** [comment]
Is this a reliable source?

https://github.com/ubuntu/yaru/blob/master/common/accent-colors.scss.in

- default `#E95420`
- bark `#787859`
- sage `#657B69`
- olive `#4B8501`
- viridian `#03875B`
- prussiangreen `#308280`
- blue `#0073E5`
- purple `#7764D8`
- magenta `#B34CB3`
- red `#DA3450`

**Comment by elioqoshi** [comment]
@jpnurmi were we able to address this?

**Comment by 3v1n0** [comment]
> Is this a reliable source?
> 
> https://github.com/ubuntu/yaru/blob/master/common/accent-colors.scss.in

It definitely is!

**Comment by jpnurmi** [comment]
This was fixed in Yaru for Flutter a while back and I've double-checked the values with daily-live 20230412.
