### ISSUE TITLE
partitioning dialog file system drop down selection options changes

### ISSUE THREAD

**Issue by tim-hm** [canonical/ubuntu-desktop-installer#1589]
## Issues

The first time you select a file system type you have a limited list of partitions but if you edit the partition type after it's selected there more options.

![image](https://user-images.githubusercontent.com/1335525/224349488-863ce86d-82ce-48d0-ae82-d8347e68791a.png)

![image](https://user-images.githubusercontent.com/1335525/224349545-fc6da327-426a-44ce-9b60-77b2e60c0ad5.png)

## Recommendation

1. The user should be presented with the same list of FS types in both instances.

**Comment by jpnurmi** [comment]
Some legacy options are intentionally filtered out when creating new partitions :)

- https://github.com/canonical/ubuntu-desktop-installer/issues/1332

We had some discussion about whether to hide them when editing partitions but it was left there for unknown/advanced use cases. If you really want to push it, you can go back and edit a newly created partition to get the legacy options that might not all be fully supported.

**Comment by elioqoshi** [comment]
Closing this unless there is an action item we want to consider here.
