### ISSUE TITLE
Review page titles

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1591]
The current page titles are off quite often. I did an audit of them and provided suggestions. These are not perfect but should improve all the titles. Ideally this needs to be reviewed by a proper copy editor.

| Current Title                                      | Proposed Title                              | Notes                                                                                             |
| -------------------------------------------------- | ------------------------------------------- | ------------------------------------------------------------------------------------------------- |
| Welcome                                            | Welcome to Ubuntu                           | mention Ubuntu explicitly                                                                         |
| Try or install                                     | Try or install Ubuntu                       | mention Ubuntu explicitly                                                                         |
| Keyboard layout                                    | Keyboard layout                             |                                                                                                   |
| Detect Keyboard Layout                             | Detect Keyboard Layout                      |                                                                                                   |
| Connect to internet                                | Connect to a network                        | Connect to internet sounds awkward. Network is mostly used                                        |
| Updates and other software                         | Install additional packages                 |                                                                                                   |
| Installation type                                  | Type of installation                        | worth to frontload the keyword here, which is 'type'                                              |
| Advanced features                                  | Advanced features                           | This will be legacy soon so keeping it as it is                                                   |
| Choose a security key                              | Security Key                                |                                                                                                   |
| Install Ubuntu Lunar Lobster alongside Windows 11  | Install alongside Windows 11                | remove the Ubuntu version to make it shorter                                                      |
| Install Ubuntu Lunar Lobster alongside them        | Install alongside current operating systems | this is wrong in this context, needs to explain better what it is about                           |
| Write changes to disk                              | Ready to install                            | Emphasize that this is the last step to confirm                                                   |
| Turn off Bitlocker                                 | Bitlocker is enabled                        | Change wording to status (adjective) instead of action (verb()                                    |
| Turn off RST                                       | RST is enabled                              |                                                                                                   |
| Where are you?                                     | Select your time zone                       |                                                                                                   |
| Who are you?                                       | Set up your account                         |                                                                                                   |
| Choose your look                                   | Choose your theme                           | look' is too off tone-wsie                                                                        |
| Welcome to Ubuntu                                  | Ubuntu 23.04                   | This is for the slideshow.                                                                        |
| Installation complete                              | Installation complete                       |                                                                                                   |
| Allocate disk space                                | Manual partitioning                         | Specifying what this really is                                                                    |
| Create partition                                   | Create partition                            |                                                                                                   |
| Create a new empty partition table on this device? | Empty partition table                       | In manual partitioning, a modal when new empty partition is created. This needs to be simplified. |

**Comment by local-optimum** [comment]
This largely LGTM, I would not mention our codename 'Lunar Lobster' in the installer however, in a formal location it should be Ubuntu 23.04 - which is the name of the release.

**Comment by elioqoshi** [comment]
I am a bit concerned about the lack of consistency which I did not address (or made even worse for some). e.g sometimes using a verb and sometimes an adjective and sometimes just the keyword. However I felt clarity-wise this would be better.

**Comment by elioqoshi** [comment]
@tim-hm Thanks, I do like these changes!

**Comment by elioqoshi** [comment]
@jpnurmi Can we get these new titles in as well?

**Comment by jpnurmi** [comment]
> - Current: Install Ubuntu Lunar Lobster alongside Windows 11
> - Proposed: Install alongside Windows 11

I don't know the history of these labels but I'd imagine the intention was to try to be more descriptive when running the installer on a system that already has Ubuntu installed. For example, the description could be:

> Install Ubuntu 23.04 alongside Ubuntu 22.10
> Install Ubuntu 23.04 alongside Ubuntu 22.04 LTS
> Install Ubuntu 23.04 alongside Ubuntu 22.04 LTS and Windows 11

Notice that it often says "Lunar Lobster (development branch)" in my screenshots because I'm taking them in a development environment. In a real live environment, it would always say "Ubuntu <version>" or "<flavor> <version>".

**Comment by elioqoshi** [comment]
Yeah I think these can be as they are, just worried they might be a bit too long in some cases but being more specific is priority here I guess
