### ISSUE TITLE
WSL OOBE Design specification

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#160]
This is the master issue to track the work on the design of the GUI of WSL OOBE.

The OOBE starts on the first boot of a WSL instance. It is similar, in concept, to the OEM setup of a current desktop installation. The OOBE is a first boot wizard which guides the user through the initial configuration of the WSL instances and helps him to:
- Select a language,
- Configure the default user,
- Configure various advanced options of WSL.

The OOBE can be executed afterwards to reconfigure WSL.

It is possible to preseed the OOBE and call it in automatic mode for automated setup of WSL.

The OOBE relies on the same components as the flutter based Ubuntu Desktop Installer such as Subiquity .

In first boot configuration mode the following stages are displayed:
- #155 
- #156 
- #157 
- #159 

In system reconfiguration mode (when the default user already exists) the following stages are displayed:
- #157 
- #158

**Comment by jpnurmi** [comment]
It's not a pixel-perfect replica of the design, but here's the current status (UI parts only, no actual functionality under the hood).

![wsl](https://user-images.githubusercontent.com/140617/125471383-5b169a15-0cef-4581-9db8-ec4b569d5b6c.gif)

I'm going to help with #144 so we can use the validated input field @Feichtmeier made.

**Comment by jpnurmi** [comment]
Feel free to reopen if there's anything missing. :)
