### ISSUE TITLE
Updated layout for language selection and keyboard layout

### ISSUE THREAD

**Issue by elioqoshi** [canonical/ubuntu-desktop-installer#1618]
I updated the layout for the loading screen, language selection and keyboard layout.

Loading screen:
![grafik](https://user-images.githubusercontent.com/5436686/224988696-d14b5e6d-b8b4-4d0f-95bb-f458b366dd7c.png)

Language selection:
![grafik](https://user-images.githubusercontent.com/5436686/224988908-389e7987-aec9-4647-b6b5-733d73a8522b.png)

Keyboard layout:
![grafik](https://user-images.githubusercontent.com/5436686/224988979-590896f6-95f3-41a5-a7df-25acde4aae18.png)

This should also address the keyboard accessibility issues addressed

**Comment by jpnurmi** [comment]
Could we have the same width for the language and keyboard layout lists? It could look jumpy with different sizes when animations (page transitions) are disabled. GNOME defaults to no animations when running with software rendering, or they can be explicitly disabled in the accessibility settings.

**Comment by elioqoshi** [comment]
@jpnurmi This looks indeed better, thanks!

**Comment by tim-hm** [comment]
A question/suggestion for the future and only if we have data to back it up. When someone selects their language how often do they then go on to change their keyboard layout and variant? 

For example, every time i select English (UK) I accept the default keyboard layout + variant. I'd be curious to understand what percentage of users are similar. If its the majority then we could consider a UX where the keyboard layout + variant are not a separate step from the initial language selection but rather a single button on that step for manual layout + variant selection.

**Comment by elioqoshi** [comment]
@tim-hm Great minds think alike :)

I asked this yesterday as I was designing this based on assumptions as we have neither data on this, neither time to do usability testing with humans. My assumption is similar to yours but that was challenged by @seb128 and @jibel (do FR keyboards use alternate layouts more often? it might depends on the local context, which is not English-specific probably).

We currently do not collect telemetry on keyboard layouts via ubuntu-report so we cannot answer that. I requested that this be tracked (anonymously of course): https://github.com/ubuntu/ubuntu-report/issues/43

Maybe we will get tangible data for 23.10.
