### ISSUE TITLE
Keyboard selector doesn't default to the best variant

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#163]
Using r39 of the snap when picking a language it seems the variant selected is always the first one in the list on the right. Often that's not the preferred one, the debian installer and ubiquity use the definitions from https://salsa.debian.org/installer-team/console-setup/-/blob/master/debian/keyboard-configuration.config , is subiquity having a similar logic and providing an API for it?

**Comment by oSoMoN** [comment]
Indeed the current implementation is rather dumb and [selects the first variant in the list](https://github.com/canonical/ubuntu-desktop-installer/blob/main/packages/ubuntu_desktop_installer/lib/pages/keyboard_layout_page.dart#L100).

@dbungert can you comment on the availability of a subiquity API for that?

**Comment by mwhudson** [comment]
subiquity is dumb about this too and we should fix it to be better. Does anyone know where d-i keeps the "default keyboard for a language" information?

**Comment by seb128** [comment]
> subiquity is dumb about this too and we should fix it to be better. Does anyone know where d-i keeps the "default keyboard for a language" information?

in the file mentioned in the issue description afaik

**Comment by mwhudson** [comment]
Ah hah I should try reading issue description not just the summary!

**Comment by jpnurmi** [comment]
https://github.com/canonical/ubuntu-desktop-installer/pull/522 lets subiquity make the decision

**Comment by dbungert** [comment]
As of https://github.com/canonical/subiquity/pull/1370, this should be in a better state.  Please retest with newer Subiquity snapshot.

We may want to add data for a few more locales, but that isn't hard.
