### ISSUE TITLE
Write change to disk summary doesn't match design

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#164]
Screenshot from r39 doing an installation in a virtual env with one disk available

![installerdisks](https://user-images.githubusercontent.com/10974330/125439480-715e830b-d9ea-4de8-a0fd-8f0db0390af1.png)

Compared to the design on https://people.canonical.com/~platform/desktop/installer/12.%20Write%20Changes%20to%20Disk/

- the summary includes the path /dev/vda instead of the name vda
- the sublines should be indented and non bold
- only the first line shoud include the 'partition n°' label

**Comment by jpnurmi** [comment]
#1015 introduced some minor design changes.
