### ISSUE TITLE
Connect to internet: expanded radio buttons

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1673]
They used to be list tiles with the background highlighted so they were expanded to the whole width but it no longer makes sense with the radio buttons that don't have a full background hover highlight.

[Screencast from 2023-03-17 14-19-21.webm](https://user-images.githubusercontent.com/140617/225916152-c65956d2-f5a8-4716-badd-11308fb1ba90.webm)

**Comment by fabiancrx** [comment]
The issue here would be to make the clickable area smaller? (Maintain hover, but reduce it to the text, not the whole width of the view)

**Comment by jpnurmi** [comment]
Sorry for the late reply. My GitHub notifications are out of control. :) Yes, we could probably wrap them with `Align` to avoid expanding them to full width, or what do you think?

**Comment by fabiancrx** [comment]
OK, now each radio button is only highlighted when its content is hovered, not the entire width of the screen, is this behavior preferred?

https://user-images.githubusercontent.com/37002358/227698634-7a08cbf2-2240-405a-b9d2-941a5aaab0f0.mp4

**Comment by jpnurmi** [comment]
Something went wrong with the screen recording or attachment but the description sounds good. :)
