### ISSUE TITLE
Socket errors after idling for a while on a screen

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#171]
Using the current snap on a canary live session, if you go to the keyboard selection page, do nothing and wait for some minutes then select a layout and click next the installer hits a socket error

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = /run/subiquity/socket, port = 0

The socket is still available and Dan said that poking to it using curl seems fine so it sounds like an issue in the dart backend

**Comment by jpnurmi** [comment]
Fixed by https://github.com/canonical/subiquity/pull/1022
