### ISSUE TITLE
autoinstall installation failed: ubuntu-desktop-installer netplan apply exit non-zero

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-desktop-installer#1723]
In testing ubuntu-desktop-installer snap in 0+git.98600e08 with the following autoinstall in desktop live installer ISO, I encounter an installation failure due to 'netplan apply' being called by subiquity.
```
ubuntu@ubuntu:~$ cat /cdrom/.disk/info 
Ubuntu 23.04 "Lunar Lobster" - Alpha amd64 (20230326)
# with supplemental snap installed and cloud-init.service After=NetworkManager.service 
```

In this autoinstall run, cloud-init generated /etc/NetworkManager/system-connections/cloud-init-enp1s0.nmconnection 
[cloud-init-enp1s0.nmconnection.txt](https://github.com/canonical/ubuntu-desktop-installer/files/11083040/cloud-init-enp1s0.nmconnection.txt)
The related [cloud-init.log](https://github.com/canonical/ubuntu-desktop-installer/files/11083058/cloud-init.log)
and 
[subiquity-server-debug.log](https://github.com/canonical/ubuntu-desktop-installer/files/11083046/subiquity-server-debug.log)

are both attached for review.

Simple test autoinstall user-data provided via the following and supplementing grub kernel params with `autoinstall 'ds=nocloud-net;s=http://blackboxsw.com:8000/'`
```
cd /tmp
mkdir desktop-autoinstall
cd desktop-autoinstall
touch meta-data
cat > user-data <<EOF

#cloud-config
ssh-import-id: [chad.smith]
autoinstall:
  version: 1
  identity:
    hostname: asdf
    username: ubuntu
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
  user-data:  # passed to the target system as #cloud-config
    packages: [sl]
EOF
python3 -m http.server

**Comment by dbungert** [comment]
https://github.com/canonical/ubuntu-desktop-installer/pull/1747
https://github.com/canonical/subiquity/pull/1623

**Comment by dbungert** [comment]
I believe so.  If people are still seeing it in current builds then we'll want fresh logs.  Thanks!
