### ISSUE TITLE
Memory test fails with "error: bad shim signature" 

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#1727]
Lunar 20230327

On a EFI system, after installation, on the boot menu, select "Memory test"

The test fails to start and the following error is displayed:

error: bad shim signature

**Comment by seb128** [comment]
the issue would rather be in memtest86+ than in the installer no?

**Comment by vanvugt** [comment]
Indeed this bug has nothing to do with the installer app, but I understand the confusion.
