### ISSUE TITLE
Fedora Silverblue not detected as an OS by the installer

### ISSUE THREAD

**Issue by local-optimum** [canonical/ubuntu-desktop-installer#1741]
When installing on my X260 the Ubuntu installer failed to detect the existing OS on the device.
This OS is Fedora Silverblue, the immutable, btrfs version of Fedora (likely that either of these two properties could be affecting it)

Using probert, the presence of fedora as a label is present on the partition:
```
  "/dev/sda5": {
                "ESTIMATED_MIN_SIZE": -1,
                "LABEL": "fedora_fedora",
                "LABEL_ENC": "fedora_fedora",
                "TYPE": "btrfs",
                "USAGE": "filesystem",
```
But the OS output is blank:

```
"os": {},
```

Not a high priority but good to understand and resolve

**Comment by kenvandine** [comment]
os-prober bug filed https://bugs.launchpad.net/ubuntu/+source/os-prober/+bug/2013215

**Comment by jpnurmi** [comment]
Closing this out of the way because it needs to be fixed in os-prober and there's not much we can do in the GUI.
