### ISSUE TITLE
23.04 Beta installer formats EFI even when not selected.

### ISSUE THREAD

**Issue by mcoyle1960** [canonical/ubuntu-desktop-installer#1772]
I have a multiboot system, usually current Ubuntu release, Windows 10, and Ubuntu development version.

Three times I have installed 23.04, most recently with the beta release. Two of the three times the EFI partition was formatted, even though I did not tell the installer to do so. 

I always select the "Something else" option, then format my test partition and assign it as "/". The installer selects the EFI partition and assigns it to /boot/efi. Formatting of the EFI is NOT selected, yet twice it has been formatted. Fortunately, I had a recent backup so I was able to get back up and running pretty quick.

**Comment by dbungert** [comment]
Thanks, we'll take a look.

It sounds like the install completed successfully otherwise?  If so there should be logs at /var/log/installer and I'd like very much to see them.  We'll also try to produce this locally.

If you want to post the logs without having them visible to the whole world you could file a new bug at https://bugs.launchpad.net/subiquity/+filebug and use this option to mark it private.

![image](https://user-images.githubusercontent.com/235157/229537301-85dda73b-9869-40ea-960e-9643beb67998.png)

**Comment by mcoyle1960** [comment]
Here's the installer log folder. I went through and deleted my user name and password.

Let me know if you need anything else.

[installer_Issue_1772.zip](https://github.com/canonical/ubuntu-desktop-installer/files/11139529/installer_Issue_1772.zip)

**Comment by dbungert** [comment]
I'm sorry that the EFI partition was wiped, and I appreciate the logs.  I *think* we have enough info to proceed with a fix.  I also appreciate the note about reFind boot loader, but suspect it isn't a factor in this case.

**Comment by dbungert** [comment]
@mcoyle1960 - I notice during logfile analysis that you had used Ventoy.  There was a known issue with that, LP: #[2012722](https://pad.lv/2012722), which caused us to not gather complete information about the filesystems.

If you were to try again with the 20230404 or newer ISO, that has the Ventoy fix, or to skip using Ventoy, I expect you would not see the problem.  When things are working correctly, in the manual partitioning screen, it will show the filesystem types of the partitions.  When things are not working correctly, that fs type column is empty.

To be clear, I'm not blaming Ventoy here, it is that Subiquity handled it poorly.

I have an additional fix as well, in the form of https://github.com/canonical/subiquity/pull/1636 which increases the cases in which we gather the filesystem type info.  While I believe that that fix will be sufficient, I'm considering additional fixes as well.

**Comment by mcoyle1960** [comment]
@dbungert, thank you for the update. When I experienced this bug, I though of two things: I'm making some mistake OR this is a big deal.  I'm very relieved to see you jump on it so quickly. I'd hate to see it somehow tarnish the release of 23.04 and Subiquity.

**Comment by dbungert** [comment]
I did a final round of testing today with the 20230407 build ISO and believe that this is resolved.  Thanks again for testing and the bug report.
