### ISSUE TITLE
Installer should not set GNOME keyboard override

### ISSUE THREAD

**Issue by mdeslaur** [canonical/ubuntu-desktop-installer#1788]
The installer currently overrides some default GNOME schemas. In this particular case, it overrides the default keyboard layout by creating a file called 20_ubuntu-desktop-installer-input-sources.gschema.override.

That setting should be left at the default of empty, so that new users get the default system keyboard layout, and not be forced to use the layout selected during the installer. The user who installed the system may not be using the same layout as whoever will be using the system later on.

Steps to reproduce:

1- install system with a keyboard layout A
2- Once system is installed, change the default system keyboard layout to B using "dpkg-reconfigure keyboard-configuration"
3- Create a new user
4- Log into desktop. Keyboard layout should reflect B, and not A.
5- Check the default setting in org.gnome.desktop.input-sources sources to make sure it is empty

**Comment by jpnurmi** [comment]
Thanks! Fixed by:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1781
