### ISSUE TITLE
23.04 installer: LUKS block device on LVM does not use the entire disk space

### ISSUE THREAD

**Issue by heldchen** [canonical/ubuntu-desktop-installer#1811]
in the 23.04 beta, when using the full disk encryption, the ecrypted block device created by the installer is not using the entire available space. on my test device with a 1TB NVMe  drive, the installer creates the LVM partitions correctly, but then only uses 100G for the LUKS block device instead of making use of the available 950G like the 22.10 and previous installers did.

23.04 installer result:
```
~$ lsblk 
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
...
nvme0n1       259:0    0 953.9G  0 disk  
├─nvme0n1p1   259:7    0     1G  0 part  /target/boot/efi
├─nvme0n1p2   259:8    0     2G  0 part  /target/boot
└─nvme0n1p3   259:9    0 950.8G  0 part  
  └─dm_crypt-0
              253:0    0 950.8G  0 crypt 
    └─ubuntu--vg-ubuntu--lv
              253:1    0   100G  0 lvm   /target
```
22.10 installer result:
```
~$ lsblk 
NAME                  MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
...
nvme0n1               259:0    0 953.9G  0 disk  
├─nvme0n1p1           259:1    0   512M  0 part  /boot/efi
├─nvme0n1p2           259:2    0   1.7G  0 part  /boot
└─nvme0n1p3           259:3    0 951.7G  0 part  
  └─nvme0n1p3_crypt   253:0    0 951.7G  0 crypt 
    ├─vgubuntu-root   253:1    0 929.4G  0 lvm   /
    └─vgubuntu-swap_1 253:2    0   1.9G  0 lvm   [SWAP]
```

**Comment by heldchen** [comment]
it can be resized post-install using `lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv` and `resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv` but the desktop installer advertizes that the entire disk is used, not just 100G so these steps should not be necessary.

**Comment by jpnurmi** [comment]
Should be fixed in recent daily-live images. Subiquity gained a new "ALL" sizing policy and it was taken into use in:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1777

**Comment by heldchen** [comment]
thanks, will recheck with a more recent daily iso - the one I used today was ~5 days old and might indeed miss this change.
