### ISSUE TITLE
wrong NVME partition name shown in disk summary

### ISSUE THREAD

**Issue by ogayot** [canonical/ubuntu-desktop-installer#1819]
Hello,

When using NVME storage, the storage summary screen shows incorrect partition names:

![Screenshot from 2023-04-17 11-43-43](https://user-images.githubusercontent.com/4038023/232483382-65028b55-a9f5-446b-b13d-6469529940b0.png)

For the device nvme0n1 (where 1 is the namespace), the partition names are expected to be:

* nvme0n1p1
* nvme0n1p2
* ...
* nvme0n1p9

https://bugs.launchpad.net/subiquity/+bug/2016389

As far as I know, the desktop installer is generating those names from the partition indexes returned by subiquity.

Thanks,
Olivier

**Comment by asacha-ru** [comment]
I can confirm that the issue is fixed in 23.04 release
