### ISSUE TITLE
German translations for next and previous could be improved

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#1836]
Eventually this is already fixed but in case it is not 

<img width="1186" alt="grafik" src="https://user-images.githubusercontent.com/15329494/233029933-9e4ff5ea-0713-4785-89cf-a1f66a8431a3.png">

More correct would be "Weiter" for "Next" and "Zurück" for "Previous"

**Comment by jpnurmi** [comment]
Thanks, I've fixed it at https://hosted.weblate.org/projects/ubuntu-desktop-installer/ubuntu-localizations/de/ but the change won't make it to the release anymore, unfortunately.
