### ISSUE TITLE
welcome: add snapcraft.yaml

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#2120]

**Comment by d-loose** [comment]
Is it possible/recommended to maintain two independent snapcraft.yaml files in the same repository, or do we need to move this elsewhere?
As far as I can tell snapcraft doesn't allow you to specify the path to a specific snapcraft.yaml other than `snap/snapcraft.yaml`. I also tried putting the individual snap directories into different subdirectories, but snapcraft doesn't seem to like `source: ..` (I guess it would work if we just use the repo's URL there, but this feels wrong somehow).

**Comment by d-loose** [comment]
That sounds like a good solution

**Comment by d-loose** [comment]
#2141 adds a snapcraft.yaml that produces a devmode snap.
Next steps towards a strictly confined snap is to identify missing interfaces -> #2148
