### ISSUE TITLE
System restart doesn't work

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#224]
Steps:
- Finish installation
- Press restart

Result:
- Expected: the system restarts
- Actual: UI exits without restarting the system

It should help if Subiquity is able to ack the reboot request in the future, so the UI can wait until the request has been received.

**Comment by mwhudson** [comment]
The POST you do to subiquity to request a restart doesn't return until /sbin/reboot has been called. I'm not sure what you mean by "acking the reboot request"?

**Comment by jpnurmi** [comment]
I didn't dig deeper yet, but I'd guess subiquity never receives the request because the UI exits too soon. Flushing the socket didn't seem to help, though. If subiquity would send a response, the UI would know that the request has been received. Does that make sense?

**Comment by mwhudson** [comment]
Not really, no :)

The flow in the text mode client is: the user clicks reboot, this starts a POST request to /reboot and sets up the UI to indicate that the reboot has been requested and waits until a response is received, then the client exits. Is there some reason the graphical client can't do this?

**Comment by jpnurmi** [comment]
> The flow in the text mode client is: the user clicks reboot, this starts a POST request to /reboot and sets up the UI to indicate that the reboot has been requested and waits until a response is received, then the client exits.

Hmm, this is exactly the flow we wanted to have in the GUI too.

> Is there some reason the graphical client can't do this?

The GUI never received a response for /reboot (even before we made it exit). I recall this was a known issue. @dbungert was it you working on it?

**Comment by dbungert** [comment]
u-d-i is not currently sending the /reboot request.
I verified this by MITMing the socket - https://superuser.com/questions/484671/can-i-monitor-a-local-unix-domain-socket-like-tcpdump

@jpnurmi - I have delayed the work on changes to the behavior of reboot until the originally committed roadmap items, all of which are u-d-i related, have been addressed.

**Comment by jpnurmi** [comment]
Perhaps we could make the UI not exit in live-run mode.

**Comment by oSoMoN** [comment]
Yes, assuming that it will exit cleanly when being killed by the /reboot request.

**Comment by mwhudson** [comment]
It's certainly hard to be sure what's happening during shutdown, the subiquity server won't return from /reboot until /sbin/reboot has been invoked, so it's all a bit of a race as to whether the response makes it to the socket before everything gets torn down anyway. It also doesn't really make any difference to anything though.

The client not sending the /reboot request does sound like it is exiting too early though.

**Comment by jpnurmi** [comment]
Leaving this open until RST and BitLocker have been fixed (https://github.com/canonical/ubuntu-desktop-installer/pull/233#issuecomment-900635639).
