### ISSUE TITLE
ISOs with the new installer are 34% bigger than legacy ISOs

### ISSUE THREAD

**Issue by vanvugt** [canonical/ubuntu-desktop-installer#2253]
~~Or put another way, 25% of the ISO is the installer?~~

For example:
mantic-desktop-legacy-amd64.iso | 2023-07-18 09:06 | **3.8G** (https://cdimage.ubuntu.com/daily-legacy/)
mantic-desktop-amd64.iso | 2023-07-18 08:28 | **5.1G** (https://cdimage.ubuntu.com/daily-live/)

Slightly less severe in lunar:
ubuntu-23.04-desktop-legacy-amd64.iso | 2023-04-17 22:28 | **3.6G** (https://cdimage.ubuntu.com/releases/23.04/release/)
ubuntu-23.04-desktop-amd64.iso | 2023-04-18 21:06 | **4.6G** (https://releases.ubuntu.com/23.04/)

**Comment by jpnurmi** [comment]
The installer snap is pretty hefty at 134MB because it's a classic snap and has to bundle all dependencies (subiquity, curtin, gtk, glib, ...) but it doesn't explain those numbers. :)

**Comment by vanvugt** [comment]
The difference seems to be in `/casper/`:

Legacy ISO:
2.7G	filesystem.squashfs

New ISO:
1.3G	minimal.standard.live.squashfs
2.5G	minimal.squashfs

**Comment by vanvugt** [comment]
Seems the problem is two copies of each snap in the one ISO:

minimal.standard.live.squashfs: /var/lib/snapd/seed/snaps
```
4.0K	bare_5.snap
74M	core22_817.snap
67M	cups_980.snap
246M	firefox_2916.snap
47M	ghostscript-printer-app_769.snap
486M	gnome-42-2204_120.snap
92M	gtk-common-themes_1535.snap
39M	gutenprint-printer-app_702.snap
62M	hplip-printer-app_788.snap
4.1M	ipp-usb_101.snap
46M	ps-printer-app_1214.snap
54M	snapd_19457.snap
452K	snapd-desktop-integration_83.snap
13M	snap-store_959.snap
129M	ubuntu-desktop-installer_1153.snap
1.4G	total
```
minimal.squashfs: /var/lib/snapd/seed/snaps
```
4.0K	bare_5.snap
74M	core22_817.snap
67M	cups_980.snap
246M	firefox_2916.snap
47M	ghostscript-printer-app_769.snap
486M	gnome-42-2204_120.snap
92M	gtk-common-themes_1535.snap
39M	gutenprint-printer-app_702.snap
62M	hplip-printer-app_788.snap
4.1M	ipp-usb_101.snap
46M	ps-printer-app_1214.snap
54M	snapd_19457.snap
452K	snapd-desktop-integration_83.snap
13M	snap-store_959.snap
1.2G	total
```

**Comment by mwhudson** [comment]
Oh joy. I have been wanting to play with different ways of minimizing the layers but wasn't expecting to get to it any time soon ...

**Comment by vanvugt** [comment]
Do I need to move the bug report elsewhere?

**Comment by mwhudson** [comment]
Yeah I guess livecd-rootfs would be more appropriate -- that would be where the fix goes

**Comment by vanvugt** [comment]
Moved to https://launchpad.net/bugs/2028213
