### ISSUE TITLE
Merge Canary/FDE feature into main code base

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#2291]
To prepare the release with the possibility of having an FDE option, we want to merge the current code in the Canary image to the main code base.

A switch on the boot command line will hide this option if it is not ready for release.

**Comment by jpnurmi** [comment]
There are some final GUI tweaks to be done but the option was basically already brought in:
- https://github.com/canonical/ubuntu-desktop-provision/pull/58

**Comment by jibel** [comment]
Canary promoted to regualr with Mantic 20230907
