### ISSUE TITLE
Use latest localization technique

### ISSUE THREAD

**Issue by ArishSultan** [canonical/ubuntu-desktop-installer#23]
I have read some of the code and I can see that the old technique is being used for localization. whereas the new technique is much easier to use and it will reduce the overall complexity.

I propose to implement localization (using a new technique). If you approve this proposal then do comment so I will create a PR.

**Comment by oSoMoN** [comment]
Would you mind elaborating on what you call "the new technique"? Do you have pointers to documentation and/or a list of advantages over the current implementation?

**Comment by ArishSultan** [comment]
Currently, `intl_translation` is being used but the flutter simplifies this process. This plugin generates a lot of extra files and I can see that the `i18n.dart` file is being managed manually.

I can send you a document that explains the process of localization. (give me your email)

**Comment by oSoMoN** [comment]
There is no need for this to be a private conversation, other contributors could potentially be interested. Can you please share this document here?

**Comment by ArishSultan** [comment]
No Problem, here is the link,

https://drive.google.com/file/d/1xfga1vuBfPBhwPL-p3ZMWoYwMb3eC-X1/view?usp=sharing

**Comment by ArishSultan** [comment]
I am waiting for your response!

**Comment by oSoMoN** [comment]
Thanks for the link. I wonder why I didn't come across this documentation when I was researching internationalization.
Your contributions to streamline the localization process will be very welcome indeed, I'm looking forward to reviewing your PR.

For reference, the corresponding documentation is at https://flutter.dev/docs/development/accessibility-and-localization/internationalization.
