### ISSUE TITLE
Merge Swedish Translation from Weblate for 23.10 installer

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#2306]
Hello!

Could someone do a Merge for Weblate for the Swedish translation of the installer for 23.10 (got it from 100% from 90% today)
Sorry if this is after the feature freeze window, but would be good to have a fully done Swedish translation and this should not break anything

**Comment by d-loose** [comment]
Hey, thanks a lot for your translations! I merged the most recent translations from weblate this morning https://github.com/canonical/ubuntu-desktop-provision/pull/95 . Those changes should propagate to the installer tonight.

**Comment by bittin** [comment]
> 

@d-loose i did some more translations this afternoon however that was not there this morning
