### ISSUE TITLE
Hide TPM FDE option if Third party drivers option is selected

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#2310]
With the TPM FDE option there is no way to install third party drivers as deb packages. The TPM backed FDE option should be hidden if third party drivers option is selected.

If this option is selected, then the TPM FDE option in advanced partitioning settings must be greyed out with a message explaining the reason. This message is exposed by subiquity.

**Comment by tim-hm** [comment]
@jibel when you write "This message is exposed by subiquity" are you saying (a) that subiquity is going to provide the message to display in the UI, (b) that subiquity tells us if TPM-backed FDE is a valid option, or (c) something else?

I have the installer working locally correctly disable the TPM-backed FDE option when 3rd party drivers are installed. I just need to know what we want to say in the copy (wider re-design out of scope).

@anasereijo fyi

[installer-tpm-3pds.webm](https://github.com/canonical/ubuntu-desktop-installer/assets/1335525/aae9411a-ace7-406f-a295-f754b69a1b1d)

**Comment by jibel** [comment]
This is done in https://github.com/canonical/subiquity/commit/1b1e89b4648044ec0a198d18495dbc7b1f47f55c

Subiquity sets GuidedDisallowedCapabilityReason to expose the reason and the message if it is not possible to use the TPM. Currently the option is completely hidden, but for an improved UX we must display the "why" from subiquity and grey out the option instead of hiding it.

Most of the bug reports we receive right now are "Why don't I see the option to install FDE"

**Comment by tim-hm** [comment]
How does l10n work in that case?

**Comment by tim-hm** [comment]
@jibel the UI now displays subiquity's error messages. There's additional work to be done on l10n and we need to tidy up the message, but I don't know if thats going to land for 23.10.

Can you take a look at the beta and if you're happy close this?

**Comment by jibel** [comment]
I verified the fix in u-d-i 1243 and it works fine. The only remaining issue is the code of the enum displayed in the warning message.
