### ISSUE TITLE
Late Swedish after the 23.10 Beta

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#2352]
### Description

Hey!

Is it possible to push some Swedish translations to the 23.10 installer a few days after the Beta? been sick and barely been at a computer 

saw that the deadline for it is 28th September however, so hopefully it can be merged from Weblate and built into an updated daily beta ISO?

**Comment by bittin** [comment]
![VirtualBox_Ubuntu 23 10 Beta 22th September 2023_25_09_2023_06_15_52](https://github.com/canonical/ubuntu-desktop-installer/assets/43197/75c77cc9-ef3d-4d93-87b8-94f144185d49)

**Comment by tim-hm** [comment]
Hi ya these landed upstream https://github.com/canonical/ubuntu-desktop-provision/pull/145.

I'm aiming to publish a candidate installer tomorrow, which will track the latest upstream, and then when that's promoted these will be in the dailies.

**Comment by tim-hm** [comment]
Translations merged in https://github.com/canonical/ubuntu-desktop-installer/pull/2351

**Comment by bittin** [comment]
Tested and fully works with the RC installer :)
