### ISSUE TITLE
Where can partition size be reset on the fly during the install?

### ISSUE THREAD

**Issue by Mafoelffen1** [canonical/ubuntu-desktop-installer#2361]
### Description

I do support at UbuntuForums... I also help with DEV testing the DEV Cycles.

I have occasionally gotten requests from users, using the default canned scripts for "Erase ALL" > Default ext4, LVM, LVM with Encryption, or ZFS... To be able to jump out to the command prompt in the Live Session (that is already there) and be able to modify the size of either the EFI partition, and or the Boot partition. Especial in the case (currently in thread https://ubuntuforums.org/showthread.php?t=2491291) when it concerns bpool in ZFS (/boot).

I know that on the Mantic 23.10 daily, in folder /snap/ubuntu-desktop-installer/1243/bin/subiquity/examples/, there are 3 autoinstall.yaml example files there. But that is not what I am looking for.

With the previous Desktop installer, it used partman, where the files for those choices were stored in /usr/lib/partman/ and could be modified during the install. I have no idea which partitioner is being used in the new flutter installer, which would be the first clue.

I have search all the json and yaml files on the Live Image. Nothing found (yet.)

I see /var/log/installer/telemetry, which just says (at the end of the json): "PartitionMethod":"use_zfs"... That doesn't give me a lot to go from.

**Comment by Mafoelffen1** [comment]
Previous to Flutter... For Ubuntu 20.0.4 LTS
Quote:
# Tweaking partition layout

As told in the introduction, nothing is hardcoded in term of [ZSys](https://github.com/ubuntu/zsys) support for your partition layout (as long as you don’t have multiple pools with the same name, of course).

If you want to tweak the partition layout to your wish. For instance, to use multiple pools in mirrors, or using RAID-Z, you can for now (until we support manual partition layout in the installer) edit manually the [zsys-setup script](https://git.launchpad.net/ubuntu/+source/ubiquity/tree/scripts/zsys-setup?id=73243b196349e8a07ab77786464391ee93f11333) on the live ubuntu 20.04 LTS desktop image before reaching the partitioning page. This one is located at /usr/share/ubiquity/zsys-setup

I know that zsys was remove from the installer after 20.04, but still... Where is this ability to tweak the partitions for the install scripts in Flutter for ZFS?

**Comment by worldofgeese** [comment]
I'd also appreciate a more flexible installer. Currently, the automated options are to install alongside an existing OS (without any encryption), blow away the disk and get access to ZFS and TPM root, or advanced which offers a cut down version of filesystems, with BTRFS as the only COW filesystem option. All three of these make major trade-offs without any sort of customization presented to the user.

**Comment by Mafoelffen1** [comment]
Bump. Asked 2 weeks ago. Still no response.

**Comment by Mafoelffen1** [comment]
Bump. Still unanswered. No response.

**Comment by Mafoelffen1** [comment]
I had asked at launchpad: https://answers.launchpad.net/ubuntu/+source/subiquity/+question/708132
it went unanswered, by others, as it did here. As you can see, I answered it myself, when I found my own answers for that...
This still does not answer what the new partitioner actually is, but that is fine for now. 
*** My Answer Is Here ***
RE: https://ubuntuforums.org/showthread.php?t=2492697&p=14166522#post14166522
*** This Is Now Closed ***
Hopefully your staffing shift settles down, and things can continue.
