### ISSUE TITLE
Issues, Questions, And Enchancement Not Being Addressed

### ISSUE THREAD

**Issue by Mafoelffen1** [canonical/ubuntu-desktop-installer#2383]
### What happened?

It seems, that no one from the Canonical Team, nor it's contributors are addressing any issues here. Nor are they being addressed at Launchpad.

This is not just for me, but for many users here, and at Lauchpad. There seems to be a problem, that I would say is a Bug in the foundation of this project's support.

I help and support other Ubuntu Users. I am limited in helping, if this "issue" continues to be undefined.

### What was expected?

A qualified response from someone from the Team, besides just "other users" who are looking for answers to their own issues.

Direction to users and the support structure of where to report Issues, bugs and technical questions.

### Steps to reproduce

1. File an issue, question, or propose an enhancement here.
2. Wait 3-4 weeks
3. It gets unresponded to by anyone that will make any difference.
4. Issue gets timed out and marked as invalid.

### Additional context

The guidance from this project for support is undefined and unclear. It is not being address at launchpad, nor it is being addressed here.

I am not connected with Canonical, nor am I a contributor here. Because no one from the team is responding, I shouldn't feel compelled to provide answers to other users, in how things work, or to help them "here."

So where do they possibly go to report bugs, issues and answers? 

There needs to be direction. There really needs to be published clear guidance on this. Maybe something published on Discourse or an Ubuntu Blog?

**Comment by vanvugt** [comment]
The installer project is being handed over between developers so there will be a period of quiet.

Since this issue is not anything specific about the code I am going to close it.

This is still the correct place to discuss installer issues. And no I am not one of the new installer developers. Your patience is appreciated.
