### ISSUE TITLE
Upstream bug tracker not linked on Launchpad

### ISSUE THREAD

**Issue by Rovanion** [canonical/ubuntu-desktop-installer#2408]
### What happened?

When I was trying to report a bug in ubuntu-desktop-installer through `ubuntu-bug` I got to the page https://bugs.launchpad.net/ubuntu-desktop-installer/+filebug/f173d414-b3a9-11ee-b117-3f38c91796cf which told me that 

> [ubuntu-desktop-installer](https://launchpad.net/ubuntu-desktop-installer) does not use Launchpad as its bug tracker.

and that

> Launchpad doesn't know of any distribution packages that include upstream ubuntu-desktop-installer. You can help by [linking them for us.](https://bugs.launchpad.net/ubuntu-desktop-installer/trunk/+ubuntupkg)

but following that link I was met with 

> Sorry, you don't have permission to access this page or the information in this page is not shared with you.

### What was expected?

To be able to report a bug in ubuntu-desktop.

### Steps to reproduce

`ubuntu-bug ubuntu-desktop-installer`

**Comment by seb128** [comment]
Thanks, somehow the launchpad bugs config got changed which is weird, I've restored it now
