### ISSUE TITLE
Regression: translations not loaded on Welcome screen

### ISSUE THREAD

**Issue by oSoMoN** [canonical/ubuntu-desktop-installer#241]
This seems to be a fairly recent regression (although I only noticed it yesterday): when running the installer from a git checkout on a system where the default locale is fr_FR.UTF-8, the language selected by default on the Welcome screen is French (as expected), but UI elements aren't translated in French until I click again on the "French" entry in the list.

![screenshot](https://user-images.githubusercontent.com/11027549/129927887-ccd6ce2b-a05a-4034-b4e4-93586afa8da8.png)

**Comment by oSoMoN** [comment]
The regression was caused by https://github.com/canonical/ubuntu-desktop-installer/commit/b68d9b922f45b265017fc4fff94bf66155a05963.

**Comment by oSoMoN** [comment]
In `setupAppLocalizations()`, on my system `Intl.systemLocale`'s value is `fr_UTF-8_FR`. The call to `Intl.shortLocale()` in `Settings.dart` reduces it to `fr`, for which there aren't translations, because the commit mentioned above moved the French translations to `fr_FR`.

On the other hand, using the `fr_UTF-8_FR` value with the `Locale` constructor doesn't result in a valid locale, because the constructor doesn't try to parse the input string, it considers it entirely as a language code.

**Comment by jpnurmi** [comment]
> on my system Intl.systemLocale's value is fr_UTF-8_FR

Is it Intl that formats it like that? What are the values of Platform.localeName and LANG?

**Comment by oSoMoN** [comment]
`Platform.localeName` returns that value (`fr_UTF-8_FR`), whereas LANG is `fr_FR.UTF-8`.

**Comment by jpnurmi** [comment]
Strange, Dart isn't supposed to mess with the value like that:

https://github.com/dart-lang/sdk/blob/master/runtime/bin/platform_linux.cc#L127

**Comment by oSoMoN** [comment]
This is indeed very strange, but I confirmed that running with various values for LANG and printing the value of `Platform.localeName`, it always get reformatted to `[langcode]_[encoding]_[countrycode]`, e.g. `es_UTF-8_AR`.

@jpnurmi could you test this on your end and let me know if you're seeing something different?

**Comment by jpnurmi** [comment]
It must have something to do with Flutter because a plain Dart app doesn't seem to touch it at all.

```
import 'dart:io';
void main() => print(Platform.localeName);
```

```
$ LANG=foo_bar.baz dart run main.dart
foo_bar.baz
```

When I run the same with Flutter, I keep getting `en_US` no matter what I specify in `LANG`...

```
$ LANG=sv_SE.UTF-8 flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
flutter: en_US
Syncing files to device Linux...                                     6ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:33197/ApDYk0uSMws=/
```

```
$ LANG=fr_FR.UTF-8 flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
flutter: en_US
Syncing files to device Linux...                                     5ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:40947/io37qz5HnRc=/
```

<details><summary>locale -a</summary>

```
$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
fr_FR.utf8
POSIX
sv_FI.utf8
sv_SE.utf8
``` 
</details>

**Comment by jpnurmi** [comment]
Oh, and with something bogus I get a warning from GTK:
```
$ LANG=foo_bar.baz flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(flutter_locales:132024): Gtk-WARNING **: 17:13:57.900: Locale not supported by C library.
	Using the fallback 'C' locale.
flutter: en_US
Syncing files to device Linux...                                     5ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:33505/qYWXQlld_uE=/
```

**Comment by oSoMoN** [comment]
That format ([langcode]\_[encoding]\_[countrycode]) corresponds to the output of the [`Locale.toString()`](https://api.flutter.dev/flutter/dart-ui/Locale/toString.html) method.

It is also the input format expected by [`LocaleInfo.fromString()`](https://github.com/flutter/flutter/blob/master/dev/tools/localization/localizations_utils.dart#L31), but I'm not sure what to make of that.

**Comment by oSoMoN** [comment]
Looking at the flutter engine's implementation, in [`platform_impl.dart`](https://github.com/dart-lang/sdk/blob/master/sdk/lib/io/platform_impl.dart#L40), `localeName()` calls a `_localeClosure()` function if it's not null.
In [`platform_dispatcher.dart`](https://github.com/flutter/engine/blob/master/lib/ui/platform_dispatcher.dart#L725), `_localeClosure` is defined like this:

    String _localeClosure() => locale.toString();

Where `locale` is of type `Locale`. This would explain why I'm getting a string in the format [langcode]\_[encoding]\_[countrycode].

 But I don't understand enough of the flutter engine to figure out whether that's expected, or something wrong with my setup?

**Comment by jpnurmi** [comment]
The list of available locales (`PlatformConfiguration.locales`) is sent from the platform shell. For Linux, it's populated with values parsed from `g_get_language_names()`. Flutter simply picks the first one on the list.

https://github.com/flutter/engine/blob/master/shell/platform/linux/fl_engine.cc#L99

I had to set LANGUAGE instead of LANG to get the values I wanted to test. For example, `LANGUAGE=fr.UTF-8_FR flutter run` prints `fr_UTF-8_FR`.

**Comment by jpnurmi** [comment]
> `Platform.localeName` returns that value (`fr_UTF-8_FR`), whereas LANG is `fr_FR.UTF-8`.

Does `LANGUAGE` contains `fr.UTF-8_FR`? It doesn't match the expected format: `language[_territory][.codeset][@modifier]`.

The engine parses locales from the end by searching the separators in the expected order (`@` -> `.` -> `_`). If codeset and territory are in reverse order, it includes territory as part of the script code.

- `fr_FR.UTF-8`: lang=fr, country=FR, script=UTF-8
- `fr.UTF-8_FR`: lang=fr, country=, script=UTF-8_FR

**Comment by jpnurmi** [comment]
Just to double-check, does the correct language not get loaded on startup with `PlatformDispatcher.instance.locale`?
```diff
diff --git a/packages/ubuntu_wizard/lib/settings.dart b/packages/ubuntu_wizard/lib/settings.dart
index 0502b5c..b9319e1 100644
--- a/packages/ubuntu_wizard/lib/settings.dart
+++ b/packages/ubuntu_wizard/lib/settings.dart
@@ -1,6 +1,7 @@
+import 'dart:ui';
+
 import 'package:flutter/material.dart';
 import 'package:gsettings/gsettings.dart';
-import 'package:intl/intl.dart';
 import 'package:provider/provider.dart';
 
 /// Provides access to application-wide settings.
@@ -41,7 +42,7 @@ class Settings extends ChangeNotifier {
 
   /// The current application locale.
   Locale get locale => _locale;
-  Locale _locale = Locale(Intl.shortLocale(Intl.systemLocale));
+  Locale _locale = PlatformDispatcher.instance.locale;
 
   /// Applies the given [locale].
   void applyLocale(Locale locale) {
```

**Comment by oSoMoN** [comment]
On my system, LANGUAGE is empty, and for reference here is the output of `locale`:

    LANG=fr_FR.UTF-8
    LANGUAGE=
    LC_CTYPE="fr_FR.UTF-8"
    LC_NUMERIC=es_ES.UTF-8
    LC_TIME=es_ES.UTF-8
    LC_COLLATE="fr_FR.UTF-8"
    LC_MONETARY=es_ES.UTF-8
    LC_MESSAGES="fr_FR.UTF-8"
    LC_PAPER=es_ES.UTF-8
    LC_NAME=es_ES.UTF-8
    LC_ADDRESS=es_ES.UTF-8
    LC_TELEPHONE=es_ES.UTF-8
    LC_MEASUREMENT=es_ES.UTF-8
    LC_IDENTIFICATION=es_ES.UTF-8
    LC_ALL=


> If the above change doesn't fix the initial language,

It does, well done! Could you please submit it as a PR?

**Comment by jpnurmi** [comment]
The language selection is still not correct. For example:

- add localizations for `fr_CA` (supported locales: `fr`, `fr_CA`, and `fr_FR`)
- run the app with the `fr_FR` locale

Result: `fr_CA` gets selected on startup because the comparison in `WelcomeModel` takes only language codes into account
