### ISSUE TITLE
Manual partitioning fails

### ISSUE THREAD

**Issue by holmanb** [canonical/ubuntu-desktop-installer#2414]
### What happened?

Despite having a /boot partition, an esp (/boot/efi), a swap partition and a /home partition, the manual installer doesn't allow installation to continue.

### What was expected?

The desktop installer should allow manual partition schemes.

### Steps to reproduce

Despite having all of the necessary partitions, the installer doesn't allow this partitioning scheme.
![Screenshot from 2024-02-01 07-04-22](https://github.com/canonical/ubuntu-desktop-installer/assets/16310367/700e3405-7cf9-4e9c-b075-542f0e41e2cf)

**Comment by d-loose** [comment]
It looks like there is no partition with `/` as a mount point.

**Comment by holmanb** [comment]
> It looks like there is no partition with `/` as a mount point.

Correct, but this requirement isn't displayed by the installer. Some indicator of requirements before moving to the next stage would benefit the user.

**Comment by d-loose** [comment]
Right, good suggestion. I've opened an issue for that in the new provisioning project.
Closing this here, as the original report isn't an actual bug :)
