### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#261]
It would be useful to have logging with configurable levels for the installer UI.

https://pub.dev/packages/logging

**Comment by jpnurmi** [comment]
Nice idea from Ken: make it possible to show logs in the UI. The log view could be accessible by a shortcut and/or a small subtle indicator somewhere, for example.

**Comment by oSoMoN** [comment]
I like the idea too, but we should make sure that the log view is very easy to discard to go back to the installer itself (I can imagine users invoking the log view by accident, and freaking out because they don't know what happened). This will require design input.
