### ISSUE TITLE
Screen 2 - installation type

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#27]
The design for screen n°2, installation type

![try-or-install](https://user-images.githubusercontent.com/10974330/110313110-47eff780-8006-11eb-93fd-3d1379939d36.png)

Design details https://people.canonical.com/~platform/desktop/installer/2.%20Installation%20Type/

**Comment by fitojb** [comment]
I’m afraid those icons look a bit too wireframe-y. I would expect filled shapes with the Suru color palette and folds.

**Comment by fitojb** [comment]
Also, the Ubuntu logo is used excessively. I remember @matthewpaulthomas advising against that many years ago…

**Comment by fitojb** [comment]
I’m afraid those icons look a bit too wireframe-y. I would expect filled shapes with the Suru color palette and folds.
Also, the Ubuntu logo is used excessively. I remember @matthewpaulthomas advising against that many years ago…

**Comment by BillDietrich** [comment]
Is some "preseed" capability going to be supported ?  I would like it to be supported.  And there should be an option to read the preseed config file from anywhere, including another USB drive (not same as installer USB).  I don't know if it should affect the UI of this page, or some other.  Thanks.

**Comment by Mannshoch** [comment]
I hope so -> #16

**Comment by Feichtmeier** [comment]
@oSoMoN 

could you eventually close the issues that have been implemented? This could help a bit to keep track for external contributors 😊

**Comment by oSoMoN** [comment]
You're right. Implementation isn't 100% complete, but it's good enough to consider closing this issue I suppose.

**Comment by Mannshoch** [comment]
Could you please give me a short feedback about your thinking for #28

**Comment by jpnurmi** [comment]
- Do we have any specs for _Repair installation_?
- Does the _Try Ubuntu_ option do anything else besides closing the installer?
