### ISSUE TITLE
Screen 4 - Keyboard

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#29]
The design for screen n°4, Keyboard

![keyboard](https://user-images.githubusercontent.com/10974330/110313400-a7e69e00-8006-11eb-9124-53181ce616b8.png)

Design details https://people.canonical.com/~platform/desktop/installer/4.%20Keyboard/

**Comment by corradoventu** [comment]
trying the installer from http://cdimage.ubuntu.com/daily-canary/pending/ dated 2021-06-15 10:10 the screen for Keyboard layout is empty so i can't select a keyboard and continue with installation
![installer-keyboard](https://user-images.githubusercontent.com/26655337/122665411-56be7c80-d1a7-11eb-9441-a1a54e60c9a1.png)

**Comment by elbeicktalat** [comment]
Also me I have the same problem, it's not only not appear but also when try to write something it's go in the wrong way. 

Write ubuntu but the result is reversed.

![Screenshot from 2021-06-27 10-03-57](https://user-images.githubusercontent.com/59793332/123537337-29397c00-d72f-11eb-8342-fe2b2fa6f3b0.png)

**Comment by oSoMoN** [comment]
Thanks for the feedback @corradoventu and @elbeicktalat. The project is still very much WIP with lots of moving parts and we're aware of basic functionality that doesn't work as expected. At this point I can only encourage you to test again from time to time and share your feedback like you did already. We're hoping to get to a minimally-working state in the near future.

**Comment by corradoventu** [comment]
Try install from ISO dated 2021-07-10 09:44
snap:ubuntu-desktop-installer	stable/ubuntu-21.10	36
the window for Keyboard layout is now ok but the window for allocate disk space seems wrong. 
![Screenshot from 2021-07-10 16-02-24](https://user-images.githubusercontent.com/26655337/125170222-31250180-e1ae-11eb-9644-0ee87e3dcd1e.png)
