### ISSUE TITLE
Desktop Installer doesn't start if yaru-theme-icon is not installed on the host

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#323]
**Description**
The installer crashes with the following error when yaru-theme-icon is not installed on the host system.

```
root@ubuntu:~# ubuntu-desktop-installer

(ubuntu_desktop_installer:5341): Gtk-WARNING **: 15:41:46.254: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)
Abandon (core dumped)

```

**Test Case**
1. Boot Ubuntu Desktop ISO of Impish
2. Install ubuntu-desktop-installer snap package
3. Run it from the command line with: ubuntu-desktop-installer
=> Verify that it starts successfully
4. Remove the package yaru-theme-icon 
5. Run it from the command line with: ubuntu-desktop-installer
=> Verify that it fails to start with the trace above

**Issues**
1. It shows that the snap is not self contained and depends on packages installed on the host to run.
2. There is a problem with the fallback used by gdk-pixbuf.

**Comment by seb128** [comment]
The error is a bit weird

Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Format d’image non reconnu (gdk-pixbuf-error-quark, 3)

It's like if the gdk png loader was not working?

**Comment by seb128** [comment]
The assertion is the one GTK hits when it fails to load the icon for some reason, see https://launchpad.net/bugs/1627564 which is a problem happening on upgrades. What's weird is that GTK includes icon-missing.png as a resource so it should always be available. Unsure if that could be a bug on how flutter sets GTK up though?

**Comment by seb128** [comment]
Downgrading libgtk-pixbuf-2.0-0 to the hirsute version workarounds the issue. One change in impish is https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/179 which means the png loader is built-in now and now a shared .so anymore. Loading png icons in GNOME seems to work fine but perhaps that's confusing flutter somehow?

**Comment by seb128** [comment]
@robert-ancell would you perhaps have some idea about that one? Don't stop to the title description but it seems there is an issue with fallbacking to the image-missing png in impish, sounds like the new gdk pixbuf could potentially confuse flutter somehow?
