### ISSUE TITLE
Doesn't generate a default hostname

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#338]
The 'who are you' page has an empty hostname value by default, it should probably generate one based on the machine identifier as ubiquity is doing?

Also if you leave the entry empty the 'next' button is not active but it doesn't mark it '... is required' as it does for the username

**Comment by jpnurmi** [comment]
Where's the best place for specifying the default values? subiquity, UI, both?

The default identity data is already queried from subiquity when entering the _Who are you_ page, so the form gets filled if subiquity provides non-empty defaults. We can specify or generate some default values in the UI too if preferred.

/cc @mwhudson @dbungert

**Comment by jpnurmi** [comment]
I just tried Ubiquity and I can see now that it doesn't have any values by default either. I'll adopt the same behavior.

@long-chung What do you think about visualizing required form fields, which is pretty common on the web. It would make the initial empty state more clear at a glance by giving a strong hint about which fields must be filled up before they can continue.

![Screenshot from 2021-09-23 08-46-41](https://user-images.githubusercontent.com/140617/134465909-88668e25-a8e4-4ae2-8aa5-39de6fe82bbf.png)

**Comment by seb128** [comment]
> I just tried Ubiquity and I can see now that it doesn't have any values by default either. I'll adopt the same behavior.

Yes, sorry that was unclear, the behaviour in ubiquity is that the entry is empty but when you start typing an username it will autogenerate an hostname default in entry using the model 'username-machine-identifier'
