### ISSUE TITLE
Screen 9 - Choose a Security Key

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#34]
The design for screen n°9, Choose a Security Key

![key](https://user-images.githubusercontent.com/10974330/110314059-a7023c00-8007-11eb-8615-a8bd332af302.png)

Design details https://people.canonical.com/~platform/desktop/installer/9.%20Choose%20a%20Security%20Key/

**Comment by lyrebird-sound-cloning-system** [comment]
"A recovery key is generated and will be temporarily saved on the live system. You can select an alternative location. Save this file and keep it in a safe place elesewhere before rebooting." 

I think that the installer should explain to the end-user what's the purpose of the recovery key.

**Comment by jpnurmi** [comment]
The recovery key part is still missing but there's a separate dedicated ticket for it:
- https://github.com/canonical/ubuntu-desktop-installer/issues/1350
