### ISSUE TITLE
WizardPage: incorrect AppBar text theme

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#340]
![Peek 2021-09-23 11-23](https://user-images.githubusercontent.com/15329494/134488162-70ca4fed-53ae-4b69-8b4d-479edaf87fbb.gif)

The AppBar theme is not correctly taken from yaru.
Which does not happen with other apps using yaru
![grafik](https://user-images.githubusercontent.com/15329494/134489073-f602d8dd-eafb-402b-9800-40458d3b6a38.png)

**Comment by jpnurmi** [comment]
Looks fine here and I've never seen this problem before... Are there any special steps that could help us to reproduce the problem? Also, could you paste the output of `flutter doctor -v`, please?

**Comment by Feichtmeier** [comment]
> flutter doctor -v

It's a fresh ubuntu 21.10 VM with freshly installed flutter desktop from beta
```bash
ub@ub:~$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.1 at /home/ub/snap/flutter/common/flutter
    • Framework revision 02c026b03c (4 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.
ub@ub:~$ 
```

**Comment by jpnurmi** [comment]
> It's a fresh ubuntu 21.10 VM
20210922? daily-live or daily-canary?

**Comment by jpnurmi** [comment]
Could you try the master channel of Flutter while I download & install? :slightly_smiling_face:

```
flutter channel master
flutter clean
flutter run
```

**Comment by Feichtmeier** [comment]
Okay, the VM image is from 10.9. but I just installed flutter today from beta

![grafik](https://user-images.githubusercontent.com/15329494/134491821-c506170a-e7f6-4c6f-bc02-416aa685adcd.png)

Installing from master now with the commands you posted above needed to upgrade though
and you are right, no probs with master version and main branch
![grafik](https://user-images.githubusercontent.com/15329494/134492969-267f74be-0fa0-43fb-a3af-a4f821b36250.png)
wondering why beta is so outdated? :D 
On my host while working on the settings app I am using the stable flutter channel

**Comment by Feichtmeier** [comment]
I think you can close both the issue and the PR then :+1:

**Comment by jpnurmi** [comment]
I believe the snap package provides the version of Flutter that was the latest stable when the snap package was published. The versions and channels of the snap package vs. Flutter are otherwise not connected.

**Comment by Feichtmeier** [comment]
I meant I was using the beta flutter channel - yes snap and flutter channels are not connected :electric_plug: :)

**Comment by jpnurmi** [comment]
Apparently, one should always run `flutter upgrade` after installing the Flutter snap. :) Or re-publish it after every stable release if that's how it works.

**Comment by Feichtmeier** [comment]
> Apparently, one should always run `flutter upgrade` after installing the Flutter snap. :) Or re-publish it after every stable release if that's how it works.

ran upgrade, but maybe it was some cache issue in vscode, since I always use the 'run' label above the main signature - sorry for robbing your lifetime thinking about this - kinda funny that flutter had some appbar theme change in the versions :D

**Comment by jpnurmi** [comment]
No worries! It may help to run `flutter clean` after switching versions.
