### ISSUE TITLE
Who are you page: login strategy is not stored anywhere

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#362]
On the _Who are you?_ page, the user can select between the following options:
- _Log in automatically_
- _Require my password to log in_

This information is never passed to subiquity or stored anywhere.

**Comment by seb128** [comment]
I've opened a subiquity request to add a backend for that on https://bugs.launchpad.net/subiquity/+bug/1946490

**Comment by N0rbert** [comment]
Really needed.

**Comment by jpnurmi** [comment]
Fixed by:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1196
