### ISSUE TITLE
Multiple copies of the UI can be opened

### ISSUE THREAD

**Issue by dbungert** [canonical/ubuntu-desktop-installer#368]
If you keep double clicking the Install icon on the desktop, you'll keep getting new copies of the UI.

**Comment by jpnurmi** [comment]
_Originally posted by @seb128 in https://github.com/canonical/ubuntu-desktop-installer/pull/422#pullrequestreview-775949426_

>Thanks and sorry for not thinking about that when I reviewed the initial change. Indeed since the snap is classic it should be able to own the dbus name without needing snapd permissions

How should we proceed?

**Comment by seb128** [comment]
I think that's fixed, it seems to do the right thing here. The slot isn't needed since as a classic snap owning the dbus name is blocked by snap
