### ISSUE TITLE
Doesn't preselect a keyboard matching the language

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#388]
On the current canary, if you pick french on the first screen the keyboard page still opens with english as selected, it should try to select the layout corresponding to the language like ubiquity is doing

**Comment by dbungert** [comment]
As of https://github.com/canonical/subiquity/pull/1370, this should be in a better state. Please retest with newer Subiquity snapshot.

We may want to add data for a few more locales, but that isn't hard.

**Comment by jpnurmi** [comment]
Here's the [full list of locales](https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_localizations/lib/src/l10n) supported by the desktop installer GUI:
```
am_ET.UTF-8
ar_EG.UTF-8
be_BY.UTF-8
bg_BG.UTF-8
bn_BD.UTF-8
bo_IN.UTF-8
bs_BA.UTF-8
ca_ES.UTF-8
cs_CZ.UTF-8
cy_GB.UTF-8
da_DK.UTF-8
de_DE.UTF-8
dz_BT.UTF-8
el_GR.UTF-8
en_US.UTF-8
eo_AQ.UTF-8
es_ES.UTF-8
et_EE.UTF-8
eu_ES.UTF-8
fa_IR.UTF-8
fi_FI.UTF-8
fr_FR.UTF-8
ga_IE.UTF-8
gl_ES.UTF-8
gu_IN.UTF-8
he_IL.UTF-8
hi_IN.UTF-8
hr_HR.UTF-8
hu_US.UTF-8
id_ID.UTF-8
is_IS.UTF-8
it_IT.UTF-8
ja_JP.UTF-8
ka_GE.UTF-8
kk_KZ.UTF-8
km_KH.UTF-8
kn_IN.UTF-8
ko_KR.UTF-8
ku_TR.UTF-8
lo_LA.UTF-8
lt_LT.UTF-8
lv_LV.UTF-8
mk_MK.UTF-8
ml_IN.UTF-8
mr_IN.UTF-8
my_MM.UTF-8
nb_NO.UTF-8
ne_NP.UTF-8
nl_NL.UTF-8
nn_NO.UTF-8
oc_FR.UTF-8
pa_IN.UTF-8
pl_PL.UTF-8
pt_PT.UTF-8
pt_BR.UTF-8
ro_RO.UTF-8
ru_RU.UTF-8
se_NO.UTF-8
si_LK.UTF-8
sk_SK.UTF-8
sl_SI.UTF-8
sq_AL.UTF-8
sr_RS.UTF-8
sv_SE.UTF-8
ta_IN.UTF-8
te_IN.UTF-8
tg_TJ.UTF-8
th_TH.UTF-8
tl_PH.UTF-8
tr_TR.UTF-8
ug_CN.UTF-8
uk_UA.UTF-8
vi_VN.UTF-8
zh_CN.UTF-8
```


Should the desktop installer generate its own `keyboard_configuration.yaml` or should we push the full list to subiquity?
