### ISSUE TITLE
Don't restrict the languages to the available translations

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#401]
We current have a limited set of translations but are able to install any langpack available so we shouldn't limit the choice on the first screen

**Comment by seb128** [comment]
The subiquity list is quite limite as well though, no italian, turkish, portugues, japanese, arabic, ...

@subiquity maintainers, is your languagelist limited by design or should those be added?

**Comment by dbungert** [comment]
Language selection is two things
* what language should the installer run in?
* what language should the target system be configured for?

For the former, a fixed set of languages makes sense - we have the translations we have.  For the latter, any valid value should be possible.  See also @mwhudson's desired locale overhaul.

**Comment by long-chung** [comment]
@oSoMoN I think it is what it is. The message would have to be in English(?) anyway so defeats the purpose.
I think we should just display the available languages we do have as this would be updated later in subsequent releases?

**Comment by seb128** [comment]
The recent update resolve the issue described there I think, let's close it now
