### ISSUE TITLE
Screen 15 - Configure Active Directory

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#41]
The design for screen n°15, Configure Active Directory

![activedir](https://user-images.githubusercontent.com/10974330/110314853-b3d35f80-8008-11eb-93aa-f735f99b75e4.png)

Design details https://people.canonical.com/~platform/desktop/installer/15.%20Configure%20Active%20Directory/

**Comment by nafallo** [comment]
Any chance to support lightweight SSO, like utilising libpam-krb5?

**Comment by Mannshoch** [comment]
May allow use e.g. a sftp server. So If someone uses username and password which works on a certain server (may a family NAS) a user is allowed to login.

**Comment by seb128** [comment]
subiquity is going to need to help with backend work there right? ubiquity is using pam-auth-update on the target env in addition of using realm

**Comment by jibel** [comment]
Since the password input is hidden, a password confirmation field must be added to ensure that the password is correct.

**Comment by N0rbert** [comment]
Really needed.

**Comment by jpnurmi** [comment]
Which indentation looks best?

### Option 1

![image](https://user-images.githubusercontent.com/140617/220862287-f9ddae18-f4ea-4381-b78c-ade9f2bf37a5.png)

### Option 2

![image](https://user-images.githubusercontent.com/140617/220862392-72a1f81a-4f63-49ef-b195-9f2c27956e61.png)

### Option 3

![image](https://user-images.githubusercontent.com/140617/220862497-8ff1ebfc-6148-4733-94d3-4079b34194bd.png)

### Option 4

![image](https://user-images.githubusercontent.com/140617/220862558-93fba301-ab8b-4d38-8db2-fcf084fc82eb.png)

### Ubiquity for reference

![Screenshot from 2023-02-22 11-44-01](https://user-images.githubusercontent.com/140617/220862193-bac56448-e8db-4759-b9b3-e8adafc61015.png)

/cc @elioqoshi

**Comment by elioqoshi** [comment]
Definitely Option 2, Indentation always the same for form elements, description for the same element starting at the same position as its title.

**Comment by jpnurmi** [comment]
![image](https://user-images.githubusercontent.com/140617/222197122-20647eca-0ac5-4aaa-ac0f-800a1e9b75b0.png)

**Comment by elioqoshi** [comment]
Context: We should offer an error message explaining the error in case something goes wrong.

**Comment by elioqoshi** [comment]
@jibel Do you have the title of the error message too?

**Comment by jibel** [comment]
updated the comment

**Comment by jpnurmi** [comment]
@elioqoshi how's this?

![image](https://user-images.githubusercontent.com/140617/224070534-4a407cf2-24fe-468c-b0a1-5a3e9a106785.png)
