### ISSUE TITLE
Screen 16 - Installation Slides

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#42]
The design for screen n°16, Installation Slides

![slides](https://user-images.githubusercontent.com/10974330/110314968-dbc2c300-8008-11eb-9e1c-935e3267b102.png)

Design details https://people.canonical.com/~platform/desktop/installer/16.%20Installation%20Slides/

**Comment by Feichtmeier** [comment]
On this screen there is a big purple progress bar.
With flutter 2.3 it is possible to style the progress indicators independent of the accent color.
I had this in yaru.dart for some days but then decided to revert this until this feature is in the beta channel.
Just FYI

**Comment by charafau** [comment]
Is it possible to get other slide images for reference ?

**Comment by oSoMoN** [comment]
The source for all the slides is [on Launchpad](https://bazaar.launchpad.net/~ubiquity-slideshow/ubiquity-slideshow-ubuntu/html/files/head:/slideshows/ubuntu/slides).

**Comment by jpnurmi** [comment]
@charafau Did you already start working on this?

**Comment by charafau** [comment]
Yes, I will try to upload my code today

**Comment by jpnurmi** [comment]
Awesome, thanks!

**Comment by jpnurmi** [comment]
@charafau Just a heads-up that we are adding a simple temporary installation page to show that something is happening: https://github.com/canonical/ubuntu-desktop-installer/pull/186. We can replace it with the slides when ready. :)

**Comment by charafau** [comment]
thanks for info, hopefully soon! (famous last words)

**Comment by jpnurmi** [comment]
The last remaining piece is to allow expanding and collapsing the terminal output. And maybe resize the window too to make more room for the terminal, like in Ubiquity?

**Comment by Feichtmeier** [comment]
My 2 cents on the terminal:
I always felt that the terminal window inside the installation window looked too techy for the average dude installing Ubuntu. Is the terminal window a must?

**Comment by jpnurmi** [comment]
Even if it's collapsed by default?

**Comment by Feichtmeier** [comment]
> Even if it's collapsed by default?

Yes - when people click there they might think they broke something. Even if looking on the terminal might be the most natural thing in the world for "us" devs/techy people, for normal users this could mean that something went wrong.
I mean is there anything important from the design perspective or in the spec that says that the terminal is needed for the UX? (really curious because I was not part of the shaping process :) )

**Comment by jpnurmi** [comment]
There are surely still improvements to be made but I'm closing this original task out of the way because we've had installation slides for quite a long time now.
