### ISSUE TITLE
Existing OS installations

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#428]
A list of existing OS installations is needed for the installation type screen:

![image](https://user-images.githubusercontent.com/140617/136984834-784643fd-3d66-4a6b-932c-ab03b23a683c.png)

https://github.com/canonical/ubuntu-desktop-installer/issues/33

**Comment by corradoventu** [comment]
screen ‘Installation type’ says: ‘The computer currently has no detected operating systems…’ while I have 4 different Ubuntu versions installed in various partitions of nvme disk of my PC
Tested with subiquity 203, 209, 214, 226

**Comment by jpnurmi** [comment]
We are still missing the "Reinstall/upgrade" option but existing OSes are probed and listed.

**Comment by corradoventu** [comment]
I don't see other OS trying install with ubuntu-desktop-installer   0+git.74cbf061      560  from iso dated jul 23

**Comment by jpnurmi** [comment]
Let's take it case by case if there are still issues detecting existing OSes.
