### ISSUE TITLE
Screen 17 - Installation Complete

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#43]
The design for screen n°17, Installation Complete

![installed](https://user-images.githubusercontent.com/10974330/110315051-fac15500-8008-11eb-92d9-77fc25af2dab.png)

Design details https://people.canonical.com/~platform/desktop/installer/17.%20Installation%20Complete/

**Comment by HaroonAwan** [comment]
I would like to work on this screen.

**Comment by oSoMoN** [comment]
@HaroonAwan you stated your interest in implementing this screen on April 21st, but haven't followed up since then. Is this something you're still interested in? I'm asking because @charafau has proposed an initial implementation of it, so in order not to duplicate work, you might want to unassign yourself and pick something else?

**Comment by oSoMoN** [comment]
I'd be interested in getting more details from design on the format of the image asset: will it be provided already cropped, or is the expectation that the asset is square, and the circular cropping happens dynamically when rendering it in the application?

**Comment by long-chung** [comment]
@oSoMoN It would be great if the cropping can happen dynamically.
That way we can swap out the asset any time without waiting for a designer to supply a new asset that has been cropped and scaled each time.

**Comment by oSoMoN** [comment]
That was my reasoning, thanks for confirming @long-chung.

**Comment by madsrh** [comment]
The content on this screen takes up very little of window size. Would it be possible to add a faded mascot image in the background? (I apologize for the pixelated mockup below)

![image](https://user-images.githubusercontent.com/3986894/124367907-e0685280-dc5b-11eb-9e7c-650ebfd5f764.png)

**Comment by long-chung** [comment]
Not keen on this. There's a lot of noise and repetition on this screen.

**Comment by oSoMoN** [comment]
This has been implemented by @charafau, thanks!
