### ISSUE TITLE
Report required disk space

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#440]
The installer needs something similar to Ubiquity, which has at least the following checks for available disk space.

### Updates and other software

When entering the page, before selecting anything:

![updates_and_other_software](https://user-images.githubusercontent.com/140617/137932986-0aae0610-b87d-4536-9a13-65a071810782.png)

### Manual partitioning

After creating partitions, when clicking _Install now_:

![manual_partitioning](https://user-images.githubusercontent.com/140617/137933249-e4cf5b76-7b94-4254-a860-7d7ecaf34455.png)

**Comment by seb128** [comment]
It doesn't seem to be on the design assets, do we need their input there or do we just do what ubiquity was doing?

**Comment by jpnurmi** [comment]
Ubiquity's logic for calculating the required disk space: https://git.launchpad.net/ubiquity/tree/ubiquity/misc.py#n934
```py
def install_size():
    if min_install_size:
        return min_install_size

    # Fallback size to 5 GB
    size = 5 * 1024 * 1024 * 1024

    # Maximal size to 8 GB
    max_size = 8 * 1024 * 1024 * 1024

    try:
        with open('/cdrom/casper/filesystem.size') as fp:
            size = int(fp.readline())
    except IOError:
        pass

    # TODO substitute into the template for the state box.
    min_disk_size = size * 2  # fudge factor

    # Set minimum size to 8GB if current minimum size is larger
    # than 8GB and we still have an extra 20% of free space
    if min_disk_size > max_size and size * 1.2 < max_size:
        min_disk_size = max_size

    return min_disk_size


min_install_size = None
```

In Jammy, there's:
```
/cdrom/casper/filesystem.size
/cdrom/casper/minimal.de.size
/cdrom/casper/minimal.en.size
/cdrom/casper/minimal.es.size
/cdrom/casper/minimal.fr.size
/cdrom/casper/minimal.it.size
/cdrom/casper/minimal.no-languages.size
/cdrom/casper/minimal.pt.size
/cdrom/casper/minimal.ru.size
/cdrom/casper/minimal.size
/cdrom/casper/minimal.standard.de.size
/cdrom/casper/minimal.standard.en.size
/cdrom/casper/minimal.standard.es.size
/cdrom/casper/minimal.standard.fr.size
/cdrom/casper/minimal.standard.it.size
/cdrom/casper/minimal.standard.live.size
/cdrom/casper/minimal.standard.no-languages.size
/cdrom/casper/minimal.standard.pt.size
/cdrom/casper/minimal.standard.ru.size
/cdrom/casper/minimal.standard.size
/cdrom/casper/minimal.standard.zh.size
/cdrom/casper/minimal.zh.size
```

Is it best to have this sort of logic in subiquity since it already knows which squashfs is relevant?

**Comment by mwhudson** [comment]
Yes, this should be in subiquity. There's some additional fun because the filesystem layer subiquity installs does not have a kernel in but well. Details!
