### ISSUE TITLE
Unable to run in Ubuntu 21.10 on Lenovo Thinkpad T580, Intel i5

### ISSUE THREAD

**Issue by BioHazard1282** [canonical/ubuntu-desktop-installer#458]
```
achak@aC-ubThnkpd:~/ubuntu-desktop-installer/packages/ubuntu_desktop_installer$ LIVE_RUN=1 flutter run
"en": 159 untranslated message(s).
"es": 159 untranslated message(s).
"es_ES": 110 untranslated message(s).
"fi": 159 untranslated message(s).
"fi_FI": 156 untranslated message(s).
"fr": 159 untranslated message(s).
"fr_FR": 110 untranslated message(s).
"it": 159 untranslated message(s).
"it_IT": 144 untranslated message(s).
"nl": 159 untranslated message(s).
"nl_NL": 140 untranslated message(s).
"oc": 159 untranslated message(s).
"oc_FR": 17 untranslated message(s).
"pt": 159 untranslated message(s).
"pt_BR": 7 untranslated message(s).
"ru": 159 untranslated message(s).
"ru_RU": 140 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on Linux in debug mode...
/snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
Building Linux application...                                           
libGL error: MESA-LOADER: failed to open swrast: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1) (search paths /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri, suffix _dri)
libGL error: failed to load driver: swrast

** (ubuntu_desktop_installer:35748): WARNING **: 01:37:01.821: Failed to start Flutter renderer: Unable to create a GL context
Error waiting for a debug connection: The log reader stopped unexpectedly.
Error launching application on Linux.
```

**Comment by jpnurmi** [comment]
Hi, this was fixed by https://github.com/canonical/flutter-snap/pull/58. Could you try to refresh the Flutter snap?

**Comment by BioHazard1282** [comment]
How do I do that?

**Comment by jpnurmi** [comment]
`snap refresh flutter`

**Comment by BioHazard1282** [comment]
Did that, so am I able to start the desktop installer now? :3




*----------------------------------------------*
*Floofy Wolf (BioHazard)*
*Senior at High School*
*Computer and Calculator programmer*

***@***.*** ***@***.***>*
*c3-productions.github.io <http://c3-productions.github.io/>*

**Comment by jpnurmi** [comment]
Was the issue resolved?

**Comment by BioHazard1282** [comment]
No, I just kinda gave up on it XD

>

**Comment by jpnurmi** [comment]
Could you give it one more try with `snap refresh --edge flutter` (notice --edge) and then `flutter run --verbose` please?

**Comment by BioHazard1282** [comment]
[verbose.txt](https://github.com/canonical/ubuntu-desktop-installer/files/7521425/verbose.txt)

**Comment by BioHazard1282** [comment]
It worked when I refreshed the snap for flutter edge, The Keyboard Layout section was blank.

**Comment by jpnurmi** [comment]
The subiquity backend is missing some dependencies. I run/installed these:
```
sudo ./packages/subiquity_client/subiquity/scripts/installdeps.sh
sudo apt install cloud-init
```

**Comment by BioHazard1282** [comment]
Even with those, I still get to the same point with the keyboard layout.

**Comment by BioHazard1282** [comment]
Wasn't this installer orginally going to be in 21.10?

**Comment by jpnurmi** [comment]
Daily canary images have the new installer: https://cdimage.ubuntu.com/daily-canary/

**Comment by BioHazard1282** [comment]
Should I try current?

**Comment by Feichtmeier** [comment]
@jpnurmi 

After a fresh install on a new vm and following the readme instructions including the python dep installation for subiquity I also receive an empty keyboard layout page with the following errors:


The important part is (I think) that a python lib `aiohttp` is missing for a flutter snap installation:

```
Traceback (most recent call last):
  File "/snap/flutter/current/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/snap/flutter/current/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ub/Projects/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/cmd/server.py", line 122, in <module>
    sys.exit(main())
  File "/home/ub/Projects/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/cmd/server.py", line 78, in main
    from subiquity.server.server import SubiquityServer
  File "/home/ub/Projects/ubuntu-desktop-installer/packages/subiquity_client/subiquity/subiquity/server/server.py", line 24, in <module>
    from aiohttp import web
ModuleNotFoundError: No module named 'aiohttp'
```
Flutter channel I tried is master, dev and beta

After running the installation script there is a erroroutput at the end of the output moaning for a missing file 'ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt''

Will try the same with a manual flutter installtion

**Comment by jpnurmi** [comment]
Sorry, I don't know what is a good workaround for the Python conflict. The issue is described here: https://github.com/canonical/ubuntu-desktop-installer/issues/364. "Vanilla" Flutter works.

**Comment by jpnurmi** [comment]
> After running the installation script there is a erroroutput at the end of the output moaning for a missing file 'ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt''

My bad, apparently you have to be in the `packages/subiquity_client/subiquity` and execute `sudo ./scripts/installdeps.sh`.

**Comment by BioHazard1282** [comment]
So I guess I can close this now since my problem was (sort-of) resolved?

**Comment by jpnurmi** [comment]
My apologies that you are facing several issues. The original issue was resolved, though. :)

**Comment by BioHazard1282** [comment]
yay! owo

**Comment by Feichtmeier** [comment]
> > After running the installation script there is a erroroutput at the end of the output moaning for a missing file 'ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt''
> 
> My bad, apparently you have to be in the `packages/subiquity_client/subiquity` and execute `sudo ./scripts/installdeps.sh`.

This works, I could update the readme a little bit if you like

**Comment by jpnurmi** [comment]
> I could update the readme a little bit if you like

That would be very much appreciated, thanks!

**Comment by Feichtmeier** [comment]
> > I could update the readme a little bit if you like
> 
> That would be very much appreciated, thanks!

https://github.com/canonical/ubuntu-desktop-installer/pull/505
:) Please have a look
