### ISSUE TITLE
When running WSL OOBE on an already setup system, u-d-i is in setup mode, not reconfigure

### ISSUE THREAD

**Issue by didrocks** [canonical/ubuntu-desktop-installer#468]
The TUI is correctly showing up the reconfigure path.

The GUI though, is always running in setup mode and doesn’t use the mode returned by the backend. The GUI needs to do a GET on client_variant endpoint.

**Comment by jpnurmi** [comment]
Yeah, there must have been a misunderstanding because the UI expects a `--reconfigure` command-line argument.

**Comment by didrocks** [comment]
yeah, basically this is the daemon which is running on the target (you can imagine the client being somewhere else :)), so this is the decision factor. Also, it avoids logic duplication between the GUI and TUI (we already have enough of them :p)

Sorry for the misunderstanding.

**Comment by jpnurmi** [comment]
No worries, it's ok! :) I'll take a look
