### ISSUE TITLE
User can go back on first step

### ISSUE THREAD

**Issue by jibel** [canonical/ubuntu-desktop-installer#469]
**Description**
On first step of the installer, it it possible under certain conditions to go back, which leads to a blank page

**Test Case**
1. Launch the installer
2. Select a language 
3. Click on next
4. Click on back twice

**Actual result**
The installer displays a blank page

**Expected result**
The go back button is greyed and the user cannot go back.

**Comment by jpnurmi** [comment]
Fixed by #438
