### ISSUE TITLE
Should the theme selection titles be changed?

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#483]
It was pointed on by translators on https://hosted.weblate.org/translate/ubuntu-desktop-installer/ubuntu-desktop-installer/en/?checksum=c6aef533d958e29d#comments

> This phrase (which nowadays has been turned into a meme) must be a placeholder, otherwise it isn't a right fit for the UI of a professional operating system, and should be replaced by something else.

**Comment by jpnurmi** [comment]
I'd be in favor of removing the page altogether. It would be a better fit for a first-run wizard.

**Comment by jpnurmi** [comment]
Alternatively, make it a toggle somewhere in the corner to make it available right away in the beginning. Currently, theme selection comes pretty late in the wizard, when the user is almost done, and dark theme lovers have already hurt their eyes. :sunglasses:

**Comment by jpnurmi** [comment]
One more point for discussion:
> making it configurable for flavors gets actually more complicated because every desktop has their own way of configuring it

**Comment by yarons** [comment]
I put a lot of effort into translating this to Hebrew, I think that the best solution would be adding the "formal" string as a comment and allow the translators to choose their flavors, I find it very poetic.

**Comment by Muqtxdir** [comment]
> I'd be in favor of removing the page altogether. It would be a better fit for a first-run wizard.

I agree with this and moreover the opted theme preference is not remembered after install so the purpose of page is not achieved. 

regarding the description of optioncards for translation s @Feichtmeier could add more to this since he implemented this page

**Comment by Feichtmeier** [comment]
A simple toggle could be enough like in the first section here

![](https://cdn.discordapp.com/attachments/860793709912915988/906213513800867850/unknown.png)

![](https://cdn.discordapp.com/attachments/860793709912915988/906213425695297586/unknown.png)

**Comment by fitojb** [comment]
This issue is closed but the string isn’t removed.

**Comment by jpnurmi** [comment]
@fitojb My bad, I removed the UI elements but forgot the translation strings. Thanks for bringing it up! https://github.com/canonical/ubuntu-desktop-installer/pull/1105
