### ISSUE TITLE
Curtin traceback in latest jammy canary image

### ISSUE THREAD

**Issue by kenvandine** [canonical/ubuntu-desktop-installer#513]
[subiquity-server-debug.log](https://github.com/canonical/ubuntu-desktop-installer/files/7547490/subiquity-server-debug.log)

**Comment by dbungert** [comment]
lsblk output, in the manner curtin invokes it, is different.  I have started teaching curtin how to deal with the new format - https://code.launchpad.net/~dbungert/curtin/+git/curtin/+merge/412027 - or we might also solve this by bundling util-linux in the snap.
