### ISSUE TITLE
Low resolution support

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#518]
From https://discourse.ubuntu.com/t/new-desktop-installer-preview-build/24765/38
> Only issue noticed was I’d not setup screen resolution on the VM so it was small (800x600 maybe; end-user mistake) and the installers window was too large so I couldn’t progress forward until I corrected screen resolution.
>
> Maybe a pop-up balloon mentioning screen resolution issue maybe helpful for some users? with link maybe to https://help.ubuntu.com/community/Installation/SystemRequirements 1 which states 1024x768)

This is how 800x600 looks:
| Ubuntu Desktop Installer | Ubiquity |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/142040962-730eaeb7-549b-4948-9dd9-e60b34eca589.png) | ![image](https://user-images.githubusercontent.com/140617/142041643-157f7d87-d92c-4e4c-a164-c63eeacf6548.png) |

**Comment by jpnurmi** [comment]
See also #253

**Comment by fitojb** [comment]
This is the kind of issues caused by pseudo-“touch-friendly”, super-padded out UI design that is so en vogue right now. I already reported this exact issue years ago to Yaru designers, who were stubborn and rejected it

**Comment by Feichtmeier** [comment]
> This is the kind of issues caused by pseudo-“touch-friendly”, super-padded out UI design that is so en vogue right now. I already reported this exact issue years ago to Yaru designers, who were stubborn and rejected it

No this is not kind of the issue.
This problem can be fixed by building this page with a LayoutBuilder which can digest screen constraints, like for example:

https://github.com/ubuntu/yaru_widgets.dart/blob/9a94d220e98625b9a810c30a629a534d6dcd3f44/lib/src/yaru_master_detail_page.dart#L39-L63

**Comment by jpnurmi** [comment]
From what I've tried earlier, the app remains fairly usable even if the window size is significantly smaller. Earlier, 960x680 was seen as a reasonable minimum size, but I think we could improve the window sizing logic to make it fit into a 800x600 desktop's available workarea while the app would still remains usable.

**Comment by jpnurmi** [comment]
The window is now maximized on app startup if the preferred window size doesn't fit the available workarea. As suggested in https://github.com/canonical/ubuntu-desktop-installer/issues/518#issuecomment-971658672, we should consider improving it further by automatically resizing the window to the preferred size if it fits after changing the resolution.

**Comment by jpnurmi** [comment]
There's been a series of changes that made the installer support smaller resolutions. It should be fine at least down to 800x600.

- https://github.com/canonical/ubuntu-desktop-installer/pull/1598
- https://github.com/canonical/ubuntu-desktop-installer/pull/1371
- https://github.com/canonical/ubuntu-desktop-installer/pull/1474
