### ISSUE TITLE
Doesn't display a warning when trying to install on a laptop not connected to power

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#526]
Ubiquity is doing that, from the old installer specification

> If the PC is not connected to a power source, this screen should begin with a ⚠ warning icon and the text “You should connect to power before continuing.”.

**Comment by jpnurmi** [comment]
@seb128 Can you see the warning in Ubiquity? I'm having trouble getting it to show up.

**Comment by jpnurmi** [comment]
The conditions are met:
- `org.freedesktop.UPower.OnBattery` is true
- `/sys/class/power_supply/BAT0/type` contains "Battery"

- https://git.launchpad.net/ubiquity/tree/ubiquity/plugins/ubi-prepare.py#n109
- https://git.launchpad.net/ubiquity/tree/ubiquity/upower.py

I'm not sure, but I suspect that part of the UI went missing or was taken out (?) in https://git.launchpad.net/ubiquity/commit/ubiquity/plugins/ubi-prepare.py?id=8466af90d11aa7924203c8f4de1af95e332af0f4

**Comment by jpnurmi** [comment]
Ubiquity 21.10:
| No space, no internet, on battery | No internet, on battery | On battery | On AC |
|---|---|---|---|
| ![no_space](https://user-images.githubusercontent.com/140617/143850651-d3e7e6cd-2c31-4e76-8e59-aa37f045a23e.png) | ![VirtualBox_Ubuntu 21 10_29_11_2021_11_20_04_no_internet](https://user-images.githubusercontent.com/140617/143850820-43e752b6-04fa-466d-9ef9-102493cf44cb.png) | ![VirtualBox_Ubuntu 21 10_29_11_2021_11_21_01_battery](https://user-images.githubusercontent.com/140617/143850913-60f2be62-d679-426d-859f-7002b56ee009.png) | ![VirtualBox_Ubuntu 21 10_29_11_2021_11_21_30_on_ac](https://user-images.githubusercontent.com/140617/143850970-bc5ba894-811a-4f5b-b11e-e2342fb8f570.png) |

**Comment by jpnurmi** [comment]
I have compared Ubiquity's warnings between 21.10, 16.04, and 15.10. Even though the source code still has some leftover references to the warning about not being connected to AC, such warning doesn't show up in 16.04 or later.

**Comment by seb128** [comment]
Thanks for checking, the idea still makes sense I think so let's perhaps keep it as a wishlist and try to see if design think it's worth including to their visuals

**Comment by mwhudson** [comment]
Thanks to another bug report, we found that unattended-upgrades refuses to run on a metered connection. Should the installer perhaps default to an offline installation in this situation? Kernels are in general installed from the network and can be rather large.

**Comment by jpnurmi** [comment]
This reminds me that @vanvugt suggested always defaulting to offline for faster installation == better UX.

**Comment by seb128** [comment]
We should probably start another issue for the offline installation question. 

It would probably makes sense to not download much by default, but if offline means no use of the geolocation service as well then it's a bit of a more tricky question. 

On ubiquity we have a 'download updates during installation' option which unchecked by default
