### ISSUE TITLE
Increase the visual density?

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#546]
The default visual density of Flutter desktop apps is relatively low. As mentioned in the Material [density guidelines](https://material.io/design/layout/applying-density.html#usage), increasing the density could be beneficial especially for those screens that have lists and tables (languages, keyboard layouts, access points, partitions).

> By making more content available on-screen, increasing the density of lists, tables, and long forms makes information easier to scan, view, and compare.

Flutter allows specifying the visual density on a scale from -4.0 to 4.0, where a low scale means high density. On desktop platforms, the default density scale is -2.0 aka. "compact". The following screenshots illustrate the difference with increased densities:

| -2.0 | -3.0 | -4.0 |
|---|---|---|
| ![Screenshot from 2021-11-30 19-39-49](https://user-images.githubusercontent.com/140617/144112217-045d4f55-2c02-48b7-bb15-5ed06db8832f.png) | ![Screenshot from 2021-11-30 19-40-05](https://user-images.githubusercontent.com/140617/144112233-e350211a-ae75-461e-83e1-71bd21ce96b4.png) | ![Screenshot from 2021-11-30 19-40-20](https://user-images.githubusercontent.com/140617/144112276-f0cd3b48-0f0c-4a86-ab2a-31eff5174d1b.png) |
| ![Screenshot from 2021-11-30 20-49-12](https://user-images.githubusercontent.com/140617/144117559-dfc624a5-e5b2-4559-9d48-f4b39c33f9c6.png) | ![Screenshot from 2021-11-30 20-01-24](https://user-images.githubusercontent.com/140617/144117151-28b06da8-b961-478d-96ae-a93f07914a14.png) | ![Screenshot from 2021-11-30 20-01-53](https://user-images.githubusercontent.com/140617/144117149-c927e2f0-7233-47ce-b735-4bd774b3c7a6.png) |

**Comment by oSoMoN** [comment]
I am no designer but to my untrained eye a value of -4.0 looks way more desktop-friendly indeed.

**Comment by Feichtmeier** [comment]
If you limit this to list tiles I think this is a good idea.
However I would leave buttons as-is

You could try this yaru.dart branch and see if this fits for you:
https://github.com/ubuntu/yaru.dart/tree/dense_tiles

**Comment by jpnurmi** [comment]
Some random remarks:
- yaru.dart forces `VisualDensity.standard` for all buttons. Using (minimum) size constraints would be a less obtrusive way to ensure that buttons don't get too cramped. It would still allow adjusting the global density for accessibility reasons, for example.
- Dense list tiles could be an option indeed, even though there are others such as data tables to consider, too.
- The input decoration from yaru.dart is significantly higher than the button height. I wonder if it could be made dense by default and have its size constraints matched with buttons?

I decided to open the ticket here as we discussed some time ago, but perhaps we could try adjusting the sizes in yaru.dart first and apply final app-specific tweaks in the installer if necessary.

**Comment by Feichtmeier** [comment]
The buttons are in line with the GNOME themes also acked by a long Chung on a yaru ticket and a big click target is always a very good idea especially nowadays where people own laptops with touch screens

The input decoration looks indeed too big. 
At some point we've changed on the input decoration away from the standard underline but maybe this could be reconsidered. I'll try to change the height first though, maybe it works. Also tables

**Comment by jpnurmi** [comment]
> The buttons are in line with the GNOME themes also acked by a long Chung on a yaru ticket and a big click target is always a very good idea especially nowadays where people own laptops with touch screens

Notice that I'm not saying that buttons should be smaller by default, but that using minimum size constraints seems like a more flexible way to achieve the same looks. That way the button size is not hardcoded, but the overall density is respected when decreased.

**Comment by Feichtmeier** [comment]
I think changing the density globally outside of the theme is not a good idea. We should find sizes for all widgets we use that work for us and use this consistently across all apps/pages. Maybe we can indeed move this discussion to yaru, sorry for not reacting in time last time

**Comment by jpnurmi** [comment]
I understand the need of having consistent default sizes across the desktop and it should be easily achievable without hard-coding a fixed density for specific widgets. Hard-coding the density on a theme level doesn't prevent resizing widgets anyway. It just makes it clumsier to build specialized apps targeted at certain groups requiring increased accessibility. There's a good reason why UI frameworks provide a way to apply a global size factor. A general-purpose theme should not intentionally aim to break that mechanism. :)

**Comment by jpnurmi** [comment]
I guess we need to create a new ticket because GitHub doesn't allow moving tickets between orgs.

**Comment by jpnurmi** [comment]
What I'm proposing is to make buttons behave like dropdowns and textfields. Notice how the size of -2.0 to -4.0 dropdowns and textfields stays the same. They have reached their minimum size constraints, so they won't shrink smaller regardless of the density scale. Considering that -2.0 is the default on desktop, this also ensures nice and coherent default looks across the desktop. Compared to buttons with a hard-coded density, specifying a default minimum size constraint can provide the exact same default looks, yet it respects lower densities for apps with special needs.

![image](https://user-images.githubusercontent.com/140617/144201168-655b3c4e-d036-475c-9b7a-32b31d7bcc92.png)

**Comment by Feichtmeier** [comment]
Okay, we might end up with a solution which satisfies everyone, let's move over to yaru.dart, maybe I just misunderstood you, and you could share where you want to change the density exactly in the code.

**Comment by jpnurmi** [comment]
With https://github.com/ubuntu/yaru.dart/pull/117:

![Screenshot from 2021-12-13 16-26-42](https://user-images.githubusercontent.com/140617/145839984-46c136a0-d3bf-4753-891d-b346a5bddf91.png)
![Screenshot from 2021-12-13 16-26-59](https://user-images.githubusercontent.com/140617/145839983-8f2417d5-1f87-41c7-b8b6-c3994b86adfd.png)
