### ISSUE TITLE
Welcome screen alignment and design

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#567]
I agree with [this comment](https://discourse.ubuntu.com/t/new-desktop-installer-preview-build/24765/49) on discourse that the alignment of this window is inconsistent with the rest of the pages.

![](https://raw.githubusercontent.com/canonical/ubuntu-desktop-installer/main/.github/docs/images/preview_screenshot.png)

Since everything in the installer is left aligned this ListView in the middle should also be aligned to the left.

![grafik](https://user-images.githubusercontent.com/15329494/145791666-30248c03-3ea7-4f9f-a0ed-fd70abda4c70.png)

The question is what happens then with the white space that will be on the right? Eventually add the Ubuntu CoF icon?

![grafik](https://user-images.githubusercontent.com/15329494/145792016-eaaf144a-1964-4121-b1db-53cdf2229099.png)

Or the current mascot for the current release?

![grafik](https://user-images.githubusercontent.com/15329494/145792536-1c4805cc-4153-41b9-b1b1-e038da011baf.png)

**Comment by sukso96100** [comment]
Maybe a language icon(something like yaru icon of `gnome-language-selector`) and a message "Please choose your language"?

**Comment by jpnurmi** [comment]
I like the idea of using some nice welcoming graphics more than focusing too much on the fact that the user can (optionally) select a language.

**Comment by Feichtmeier** [comment]
Indeed!
Svgs (as those [official mascot SVGs by canonical designers](https://discourse.ubuntu.com/t/official-artwork-downloads-for-impish-indri/24291)) can be loaded as widgets into flutter with

```dart
  SvgPicture.asset(
    assetPath,
    color: ..optional color..,
    colorBlendMode: ...optional blende mode...,
    height: ...optional height...,
  ),
```

via https://pub.dev/packages/flutter_svg

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/149377662-3a8fe1d6-4e27-41c4-92b0-0a0b3a6fcf3b.png)

![grafik](https://user-images.githubusercontent.com/15329494/149378134-6d0dfae4-18a9-47bb-a1f9-6215ab054ea8.png)

Result

**Comment by Feichtmeier** [comment]
@elioqoshi @jpnurmi 

I think the new centred alignment of some pages really improved the visual focus of those pages. Would it be possible to make the other pages centred, too? While using the new installer I've found my eyes jumping a bit around when it changed from centred pages to left aligned pages
