### ISSUE TITLE
Use libhandy to round all four window corners

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#583]
Most gnome applications preinstalled in Ubuntu 21.10 use libhandy to somehow modify gtk3 that all four window corners are round:

![grafik](https://user-images.githubusercontent.com/15329494/146516094-41c19fcf-8886-450b-a3d3-15d54018f322.png)

We've managed to include and use libhandy inside the settings project:
https://github.com/Feichtmeier/settings/commit/7f62addf697a7eabdb0bf9431298bd9787e009ce

![grafik](https://user-images.githubusercontent.com/15329494/146516409-0e3a1711-00c0-4ffa-9f65-4110ac1ea1f7.png)
![grafik](https://user-images.githubusercontent.com/15329494/146516641-d38d8b1b-e1cc-402d-a8ef-6ebcec34b2ca.png)

Could this also be done in the installer?

I think it does not only "look better"/"look more modern" but also increases the visual consistency with the rest of the Ubuntu desktop after installation.

**Comment by seb128** [comment]
@robert-ancell hey, do you have any opinion about using libhandy?

**Comment by robert-ancell** [comment]
I think it should be OK because:
- libhandy is being used in many apps.
- We're only using a small subset of it.
- For the installer, we'll be able to control the exact version of libhandy, which avoids the sometimes unstable nature of it.

It may be worth investigating how much code libhandy is using for the rounded windows, and moving that into the Flutter shell or the desktop installer, but that can be done at a later stage.

**Comment by seb128** [comment]
@Feichtmeier would you maybe be wanting to work on the PR for the change?

**Comment by jpnurmi** [comment]
I'm sure there's more code to strip off, but here's the result of throwing out everything except `HdyWindow`, `HdyHeaderBar`, and their dependencies:

- lines of code (src/*) went down from ~31k to ~4k
- release build size went down from 896kb to 151kb

**Comment by Feichtmeier** [comment]
> @Feichtmeier would you maybe be wanting to work on the PR for the change?

I can but all the work has been done by @jpnurmi in this case so I can replicate the changes in the Linux directory in the settings app in the installer if you like

**Comment by jpnurmi** [comment]
Using libhandy is straightforward, but getting it in the snap is the laborious part. core20/20.04 has too old libhandy (0.x) without support for rounded corners, so I suppose libhandy 1.x would need to be built as part of the snap.

**Comment by jpnurmi** [comment]
By the way, it would be interesting to see if this has any effect on the window decoration rendering issue.

**Comment by kenvandine** [comment]
It should be trivial to build libhandy as a part, I've done this in a few snaps before.

**Comment by jpnurmi** [comment]
I'm running into a library version mismatch, possibly because the Flutter snap is core18 and therefore pulls in old versions of GTK & GLib etc.?

This is what I have for libhandy in snapcraft.yaml:
```diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index a8ce156c..d2b85479 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -117,7 +117,26 @@ parts:
     prime:
       - -lib/systemd/system/*
 
+  libhandy:
+    source: https://gitlab.gnome.org/GNOME/libhandy.git
+    source-branch: "libhandy-1-2"
+    source-depth: 1
+    plugin: meson
+    meson-parameters:
+      - --prefix=/usr
+      - --buildtype=release
+      - -Dvapi=false
+      - -Dintrospection=disabled
+      - -Dgtk_doc=false
+      - -Dtests=true
+      - -Dexamples=false
+      - -Dglade_catalog=disabled
+    build-packages:
+      - cmake
+      - libgtk-3-dev
+
   ubuntu-desktop-installer:
+    after: [libhandy]
     source: .
     source-type: git
     plugin: nil

```

I can see in the snapcraft output that version 3.24 gets installed:
```
Installing build dependencies: ... libgtk-3-dev=3.24.20-0ubuntu1
...
Setting up libgtk-3-dev:amd64 (3.24.20-0ubuntu1) ...
```

Also, meson finds 3.24 version when building libhandy:
```
Building libhandy 
...
Run-time dependency gtk+-3.0 found: YES 3.24.20
```

However, when building the installer, pkg-config finds 3.22:
```
[   +8 ms] Building Linux application...
...
[   +9 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1") 
[        ] -- Checking for module 'gtk+-3.0'
[  +32 ms] --   Found gtk+-3.0, version 3.22.30
[ +108 ms] -- Checking for module 'glib-2.0'
...
[  +96 ms] -- Checking for module 'libhandy-1'
[  +34 ms] --   Found libhandy-1, version 1.2.3
[ +128 ms] -- Configuring done
```

As a result, linking fails because `GtkEventControllerKey` was introduced in 3.24:
```
[   +4 ms] : && /snap/flutter/current/usr/bin/clang++  -isystem/root/stage/usr/include -isystem/root/stage/usr/include/x86_64-linux-gnu -O3 -DNDEBUG
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl -L/snap/flutter/current/usr/lib/
-L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -lblkid -lgcrypt -llzma -lpthread -ldl -L/snap/flutter/current/usr/lib/
-L/root/stage/lib -L/root/stage/usr/lib -L/root/stage/lib/x86_64-linux-gnu -L/root/stage/usr/lib/x86_64-linux-gnu CMakeFiles/ubuntu_desktop_installer.dir/main.cc.o
CMakeFiles/ubuntu_desktop_installer.dir/my_application.cc.o CMakeFiles/ubuntu_desktop_installer.dir/flutter/generated_plugin_registrant.cc.o  -o
intermediates_do_not_run/ubuntu_desktop_installer -L/root/parts/ubuntu-desktop-installer/build/packages/ubuntu_desktop_installer/linux/flutter/ephemeral
-Wl,-rpath,/root/parts/ubuntu-desktop-installer/build/packages/ubuntu_desktop_installer/build/linux/x64/release/plugins/ubuntu_wizard:/root/parts/ubuntu-desktop-installer/build/packages
/ubuntu_desktop_installer/build/linux/x64/release/plugins/url_launcher_linux:/root/parts/ubuntu-desktop-installer/build/packages/ubuntu_desktop_installer/linux/flutter/ephemeral:
plugins/ubuntu_wizard/libubuntu_wizard_plugin.so plugins/url_launcher_linux/liburl_launcher_linux_plugin.so -lflutter_linux_gtk /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +1 ms] /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_init'
[        ] /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_dec'
[        ] /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `g_atomic_ref_count_inc'
[        ] /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `log2@GLIBC_2.29'
[        ] /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `gtk_event_controller_key_new'
[        ] /root/stage/usr/lib/x86_64-linux-gnu/libhandy-1.so: undefined reference to `pow@GLIBC_2.29'
```
Same for e.g. glib-2.0 (2.64 vs. 2.56).

**Comment by jpnurmi** [comment]
If someone wants to help out with the snap config changes, the libhandy changes are here: https://github.com/jpnurmi/ubuntu-desktop-installer/commit/9d86e82f42e10d07d3c38e610fab9f4282080306

**Comment by jpnurmi** [comment]
Nevermind, I managed to build a snap with libhandy. :smile: The bad news is that the same rendering issues are still there.

https://user-images.githubusercontent.com/140617/149166485-b70020b3-3d8a-41bd-b196-f53c4c80a792.mp4

**Comment by Feichtmeier** [comment]
> #605 contains the code changes for rounded corners and the snap config changes for libhandy. It includes a hack to use Flutter from Git because of the linking issue described above.

Awesome!
Is this eventually related https://github.com/canonical/flutter-snap/issues/63 ?
