### ISSUE TITLE
Encryption disk option missing

### ISSUE THREAD

**Issue by lucamosca1** [canonical/ubuntu-desktop-installer#586]
As per subject, could be useful that an option to encrypt disk (with user password or a different one) is available and put in evidence.
In actual installer of 20.04 and 21.10 (I think), encryption option is hidden in 'Advanced' but other ubuntu derivates such as actual PopOS and Elementary has a proper screen in installation wizard.
I think that the same thing should be done here, in some companies dusk encryption is mandatory and you can not turn it on such as Windows BitLocker or Mac FileVault, you have to reinstall everything.

**Comment by jpnurmi** [comment]
Hi! We're still missing some pieces (subiquity & design) to be able to enable disk encryption, but it will eventually be there.

**Comment by lucamosca1** [comment]
Ok, cool. It was just a suggestion, you can close the issue.

Many thanks
