### ISSUE TITLE
Cannot see password on the "Who are you" page

### ISSUE THREAD

**Issue by oSoMoN** [canonical/ubuntu-desktop-installer#589]
Users have reported that there should be a toggle in the password fields on the "Who are you" page, to allow viewing the entered passwords.
This is especially important because there may be bugs in the keyboard layout selection, which result in the user not knowing for sure that they entered their password correctly.

**Comment by Feichtmeier** [comment]
@oSoMoN if you want you can assign me to this :)

**Comment by oSoMoN** [comment]
Thanks for implementing this @Feichtmeier !

**Comment by Feichtmeier** [comment]
> Thanks for implementing this @Feichtmeier !

You're welcome! :)
