### ISSUE TITLE
"{RELEASE}" placeholder in strings doesn't allow correct translations

### ISSUE THREAD

**Issue by oSoMoN** [canonical/ubuntu-desktop-installer#660]
I was translating strings that were added with the new dynamically generated slideshow into French yesterday, and I came across some strings that cannot be correctly translated because of the `{RELEASE}` placeholder.
For instance, on the welcome slide:

> Fast and full of new features, the latest version of {RELEASE} makes computing easier than ever.

In French, the preposition varies depending on the value of `{RELEASE}`:

> la dernière version d’Ubuntu

VS

> la dernière version de Lubuntu

**Comment by oSoMoN** [comment]
In the current ubiquity slideshow, I believe each flavour gets a translation template that is generated by substituting `{RELEASE}` with the name of the flavour (e.g. Ubuntu or Lubuntu), and so translations are not among flavours.

We should probably do the same here.

**Comment by bittin** [comment]
Swedish translation at 95%

**Comment by jpnurmi** [comment]
The idea was that flavors would set up their own translations. Passing localization delegates in `FlavorData` makes it possible to access the translations from the context where slides are built. Would that be sufficient?

I actually had an impression that flavors generally wouldn't use the same texts in the slides. Using a {RELEASE} placeholders seemed the right thing to do, nevertheless, so flavors are able to reuse some strings where they do fit.

**Comment by oSoMoN** [comment]
I agree that re-usability is nice, but if it comes at the expense of correct translations, I'd say it's a no-go.

I don't know what other languages are affected by this problem, if any, but I do care about French, and to re-iterate my point, in the current situation the translation of e.g. the `welcomeSlideDescription` string is incorrect if `RELEASE` == "Ubuntu" (but it is correct if e.g. `RELEASE` == "Lubuntu").

**Comment by bittin** [comment]
96%
