### ISSUE TITLE
Not all content is visible inside the window

### ISSUE THREAD

**Issue by madsrh** [canonical/ubuntu-desktop-installer#672]
Two things are obvious from this WM screenshot:

![image](https://user-images.githubusercontent.com/3986894/153304177-de28ad25-065e-458c-bb6b-d6dab3dc919e.png)

1. At 23:47 I really should be sleeping
2. Not all the content of the window is visible

I know that, as soon as I touch the scroll wheel on the mouse, the scrollbar is visible, but I wonder if there should be something to indicate that you can scroll down 🤷‍♂️ Something like the [undershoot in Yaru](https://github.com/ubuntu/yaru/issues/1790#issuecomment-578307205).

Just a thought 😃 

![image](https://user-images.githubusercontent.com/3986894/153305010-98eccdbe-0d4d-48f0-8e57-63953f885582.png)

**Comment by jpnurmi** [comment]
Typically, this only happens with VMware VMs that have an awfully small resolution/window by default. In that case, we have no other option than to squeeze the window into the available work area. Under normal circumstances, the window size is fixed to 960x680 to match the design.

**Comment by jpnurmi** [comment]
Maybe we could simply throw away that "The name it uses when it talks to other computers" label. Leaving a larger gap in the middle of the form makes the form feel uneven. It's not even immediately obvious which field the label is associated with. Ojn the other hand, adding more spacing could push the content down enough to make the password confirmation field only partly visible, which could be a good enough hint that there's more content? Yet, it would only help with this specific window size... :)

**Comment by Feichtmeier** [comment]
The inputs are now a bit less tall in yaru.dart (maybe need to make a release) so maybe this could help too on this page

**Comment by madsrh** [comment]
> The inputs are now a bit less tall in yaru.dart (maybe need to make a release) so maybe this could help too on this page


Ahh okay 👍 Even more reason to close this issue 😊 Thanks @Feichtmeier
