### ISSUE TITLE
Installer window should have more compact design to fit in 684 pixels in height

### ISSUE THREAD

**Issue by N0rbert** [canonical/ubuntu-desktop-installer#692]
See screenshot from 1366x768 screen with https://cdimage.ubuntu.com/daily-canary/current/jammy-desktop-canary-amd64.iso running inside QEMU:

![canary](https://user-images.githubusercontent.com/309456/154796798-e35af9fa-ffcb-4eda-bc4c-700f4117e027.png)

Not everyone works on FHD and 4K screens. See https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide :

> ![resolutions](https://user-images.githubusercontent.com/309456/154796875-9b400786-dc18-4c04-94bb-cb4eb1bff5a2.png)

**Comment by jpnurmi** [comment]
There's been a series of changes that made the installer support smaller resolutions. It should be fine at least down to 800x600.

- https://github.com/canonical/ubuntu-desktop-installer/pull/1598
- https://github.com/canonical/ubuntu-desktop-installer/pull/1371
- https://github.com/canonical/ubuntu-desktop-installer/pull/1474
