### ISSUE TITLE
Wrong window size

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#697]
The window has the wrong size after switching to [HdyWindow](https://github.com/canonical/ubuntu-desktop-installer/pull/618).

HdyWindow doesn't use GtkWindow.titlebar. The requested window size should take the header bar into account so that 960x680 is left for the content.

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/155127204-d5b1e65d-a2fd-4ffc-bcb2-ba21ea304665.png) | ![image](https://user-images.githubusercontent.com/140617/155127234-b57cb24d-7065-40fc-bf80-2fc8e7dcc3e0.png) |

**Comment by bittin** [comment]
The Text placement is sometime cut off (Live system or install screen), or behind pictures and such for the Slideshow, would be nice if this can be fixed before the final release
