### ISSUE TITLE
 Installer Broken 23 February Canary Image 

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#699]
Another day of the installer not installing
![VirtualBox_Ubuntu 2021-2022 Installer Test 23 Feb _23_02_2022_11_31_31](https://user-images.githubusercontent.com/43197/155302316-eb5f6735-f863-456e-ae2b-90807815695e.png)

**Comment by bittin** [comment]
Works with the older installer however

**Comment by bittin** [comment]
And no Canary was built today :(

**Comment by bittin** [comment]
Still no builds 25th February

**Comment by bittin** [comment]
Crashes with the 6th March build too

**Comment by jpnurmi** [comment]
20220318 works
