### ISSUE TITLE
i18n: use launchpad or weblate

### ISSUE THREAD

**Issue by ensag-dev** [canonical/ubuntu-desktop-installer#7]
Hello,
I'd like to translate the brand new installer but I'm not confident with the way translations are handled.
Would it be possible to use an interface like launchpad or a weblate instance?

**Comment by Lennoard** [comment]
Me too. I have it done though, but I'm afraid to PR and mess up everything.

**Comment by oSoMoN** [comment]
This is great, translations are very welcome!

I have a pending work item to research how to integrate the installer's translations with either Launchpad or another more user-friendly interface, so let's use this issue to track it.

If you have done translations already, do not be afraid to make a PR, we'll be reviewing and advising. Thanks in advance!

**Comment by fitojb** [comment]
I’d prefer any internationalization effort to be invested in Weblate rather than Launchpad, for the reasons I stated here:

https://discourse.ubuntu.com/t/ubuntu-should-use-weblate-instead-of-launchpad-rosetta/14944

**Comment by jhenstridge** [comment]
For what it is worth, I did some investigation into how to get snapd's translations into Launchpad.  Some of what I found might be applicable here.

The Launchpad API does not include a method for direct upload of translation templates as found in its web interface.  It does support importing from a Bazaar branch though.  If you are happy to have an up to date translation template checked into the git repository, then the easiest option would be to register a git -> Bazaar code import branch as the project's trunk series branch on Launchpad.  If you then turn on translation imports, changes should make their way in via Github -> Launchpad code hosting -> Rosetta.

If you don't want the translation template checked in, one alternative would be to have a Github Actions workflow that will periodically build the template and check it into a bare Bazaar branch set up on Launchpad as above.

To get translations out, you can specify a Bazaar branch that Rosetta will commit translation changes to.  This doesn't need to be related to the branch it imports translations from, so this could be another bare branch with no code in it.  It would then be fairly simple to write a workflow to periodically check out this Bazaar branch and copy the translations into git (either committing them directly to main, or generating pull requests).

**Comment by oSoMoN** [comment]
Thanks James, that's very useful.

**Comment by oSoMoN** [comment]
@fitojb your post and the follow-up answers are an interesting read, this will be taken into consideration for sure.

**Comment by oSoMoN** [comment]
I skimmed through the [weblate documentation](https://docs.weblate.org/en/latest/), and seeing that it supports both the [ARB file format](https://docs.weblate.org/en/latest/formats.html#arb-file) (used by flutter i18n) and [github integration](https://docs.weblate.org/en/latest/vcs.html#github), it's an appealing option indeed.

LXD already [uses it](https://hosted.weblate.org/projects/linux-containers/lxd/), so there's precedent for Canonical-sponsored projects.

**Comment by stgraber** [comment]
Right, on the LXD front the focus at the time was to get a platform where you can login through Github which can automatically import from a git repository and get us the updated `.po` files that we can merge back into the main repository.

Doing this with Launchpad would have required a mirror of the repository and logic to pull the translated files back into the main repo, possibly more annoyingly, it would have required all translators get a Launchpad account.

In general we've been quite happy with weblate but only use a very small fraction of its features. For larger projects with more active translators it feels like it's got a lot of nice features around tracking best practices, automatically filling in translation from similar strings and allowing for a variety of review mechanisms.

**Comment by oSoMoN** [comment]
Thanks very much for your feedback @stgraber!

**Comment by seb128** [comment]
I'm not familiar with how weblate is set up but one strong advantage from using launchpad is that the translations are in the hands of contributors who are trusted in the Ubuntu context. 

Launchpad also displays similar strings already translated on the platform and their translations which is useful to ensure consistency in Ubuntu translations. (weblate seems to have a similar feature but it's not focused on the Ubuntu set and consistency with random other github projects isn't as valuable to us)

That being said the launchpad translation UI hasn't benefited from much work in recent years and that's showing, our translators community also doesn't seem as active as it used to be. There is value investigating i a move could help us, we might want to do that as part of a shared reflection at the Ubuntu level (or at least standardize for the different Ubuntu projects we are hosting on github)

**Comment by seb128** [comment]
The launchpad translations system being unmaintained and comparing negatively to other solutions available nowadays has been discussed on https://discourse.ubuntu.com/t/reconcidering-workflows for reference, there has been no really conclusion though

**Comment by fitojb** [comment]
> I'm not familiar with how weblate is set up but one strong advantage from using launchpad is that the translations are in the hands of contributors who are trusted in the Ubuntu context 

@seb128 This benefit of course can be maintained if Ubuntu sets up its own instance of Weblate (like Fedora did), where its existing translators can register.

**Comment by fitojb** [comment]
Example of Flutter project using Weblate translations: https://github.com/git-touch/git-touch

**Comment by jpnurmi** [comment]
Announced on the ubuntu-translators mailing list: [New desktop installer is translatable on weblate](https://lists.ubuntu.com/archives/ubuntu-translators/2021-November/007779.html)

https://hosted.weblate.org/projects/ubuntu-desktop-installer/
