### ISSUE TITLE
Installer Broken 6th March Canary Image 

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#724]
New Installer is still broken

**Comment by jpnurmi** [comment]
20220318 works

**Comment by bittin** [comment]
Confirmed working, only missing some jammy branding, but i guess that will be fixed too?

**Comment by jpnurmi** [comment]
Yes, we need to update all the artwork. :+1:

**Comment by jpnurmi** [comment]
Thanks for the reminder. I put it on the Jammy TODO list: https://github.com/canonical/ubuntu-desktop-installer/issues/745
