### ISSUE TITLE
Update artwork

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#745]
Replace all Impish logos and images with Jammy ones, and use the new Ubuntu logo too.

**Comment by jpnurmi** [comment]
The logo on the welcome screen. Here's the starting point with the impish logo, and some different options for jammy.

| Light | Dark |
|---|---|
| ![1_light](https://user-images.githubusercontent.com/140617/159487328-bdda8da5-0165-4abd-aba2-7d59c399fa92.png) | ![1_dark](https://user-images.githubusercontent.com/140617/159487294-f4186107-1641-4ae2-b944-27d4712560ec.png) |
| ![2_light](https://user-images.githubusercontent.com/140617/159487356-5c4244f2-d536-4005-9920-402e667f160a.png) | ![2_dark](https://user-images.githubusercontent.com/140617/159487340-34d1ac29-bd71-4812-bc65-48cf6658f874.png) |
| ![3_light](https://user-images.githubusercontent.com/140617/159487397-817b8346-9ccb-40f9-b4d2-13818efee40a.png) | ![3_dark](https://user-images.githubusercontent.com/140617/159487424-bfbd5066-d2b5-4077-b2dc-627ecd8ef847.png) |
| ![4_light](https://user-images.githubusercontent.com/140617/159487432-c4a03fc3-5c5b-4f25-aa3d-c981fad95995.png) | ![4_dark](https://user-images.githubusercontent.com/140617/159487440-74734916-96b5-4330-b991-98c51b0ecaff.png) |
| ![5_light](https://user-images.githubusercontent.com/140617/159487453-97d86f95-3976-4375-8d70-ff564c597dc5.png) | ![5_dark](https://user-images.githubusercontent.com/140617/159487467-e36bed96-7745-45f6-aaff-e7e7dd13832f.png) |

**Comment by waynecrosby** [comment]
@jpnurmi I think A or C work best
