### ISSUE TITLE
dangerous ZFS file system layout

### ISSUE THREAD

**Issue by hadmut** [canonical/ubuntu-desktop-installer#779]
Hi,

I yesterday tried Ubuntu 22.04 beta, and the installer forces (if the user is not experienced enough to do a  manual installation and chooses the simple automatic installation) to use either LVM or ZFS in order to have encryption. I've chosen ZFS for the test and ran into the problem, that it does not even boot then, since ZFS is decrypted, but not mounted, and important files are unavailable then ( https://bugs.launchpad.net/bugs/1967621 )

However, this way I saw that the installer is creating ZFS file systems for /var/lib and some more directories under it. 

This is dangerous. 

ZFS supports the idea of snapshots, rollback, export/import and things like that, and that way it can easily happen, that /var/lib and the other directories like /usr /etc /bin ,... are not handled synchroneously. But then, the package information for debian/ubuntu packages is stored in /var/lib/dpkg, while most package contents are stored in /usr and /etc.

If it happens that the package meta information  or runtime data in /var/lib and the package contents in /usr /etc /bin ... are not consistent anymore, your system is just doomed beyond repair and needs reinstallation.

**Comment by kenvandine** [comment]
This is actually a zsys bug, https://bugs.launchpad.net/bugs/1967585

**Comment by kenvandine** [comment]
We think the not booting issue is from the bug I linked.  The other concerns should be filed on launchpad.  The ubuntu-desktop-installer isn't used in 22.04, so the installer you experienced this in would have been ubiquity.  We haven't released a beta with this new installer yet.  Issues with the 22.04 beta installer should be filed against https://bugs.launchpad.net/ubuntu/+source/ubiquity/

Thanks for your report.

**Comment by hadmut** [comment]
This bug report was not at about that booting issue. This was just the reason to find another problem. 

You would have noticed if you had ever bothered to read that bug. 

You're positively sure to be able to write software?
