### ISSUE TITLE
Respect new gnome dark mode settings in app-theme and eventually new yaru color versions

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/ubuntu-desktop-installer#783]
With 22.04, GCC triggers a new value 

org.gnome.desktop.interface color-scheme

![grafik](https://user-images.githubusercontent.com/15329494/161951370-27cfb427-aed0-46c9-8783-d44122e8a583.png)

It could be added to the settings class beneath
https://github.com/canonical/ubuntu-desktop-installer/blob/ba5a9505ff7d936cb236ceafc35efd8446cda5bb/packages/ubuntu_wizard/lib/settings.dart#L31

Also, if the installer wants to support the accent colors, things get a little bit more complicated. There are probably other ways to do it, but in the settings project, I've used changenotifiers for the gtk-themes instead:
https://github.com/Feichtmeier/settings/blob/master/lib/view/pages/appearance/theme_section.dart

I need to set up a new VM for the installer, then you can hopefully assign this issue to me if you want to :)

**Comment by jpnurmi** [comment]
Perhaps there could be an [inherited widget](https://api.flutter.dev/flutter/widgets/InheritedTheme-class.html) in `yaru_widgets` that provides the correct theme to its children?

**Comment by jpnurmi** [comment]
The 99% case
```dart
// follow the system defaults
YaruTheme(child: MyApp())
```

For the rest (e.g. an app wants a specific accent, always dark, or such)
```dart
// override specific attributes
YaruTheme(
  data: YaruThemeData(
    foo: bar, // 
    baz: qux, // 
  ),
  child: MyApp(),
)
```

**Comment by jpnurmi** [comment]
@seb128 @elioqoshi Do we want to offer accent color selection on the "Choose your look" page?

![Screenshot from 2022-04-06 14-16-17](https://user-images.githubusercontent.com/140617/161972627-e55a4c9c-cf95-44d6-91da-2c97077121ba.png)

**Comment by elioqoshi** [comment]
Oh no, that would be way too granular, I'd recommend to skip that part in the installer.

**Comment by seb128** [comment]
I've no strong opinion and would follow Elio's suggestion

**Comment by jpnurmi** [comment]
@Feichtmeier I have reported https://github.com/flutter/flutter/issues/101438 and proposed a fix https://github.com/flutter/engine/pull/32456

**Comment by Feichtmeier** [comment]
@jpnurmi nice!

are you sure this will be enough to get the dark theme no matter the yaru accent color?
there are now much more yaru variants available (official Ubuntu themes)
Not talking about the installer only, but in general I mean.

**Comment by jpnurmi** [comment]
@Feichtmeier Do you have a particular case in mind? There are dark variants of all `Yaru-<color>` themes even though Flutter doesn't really need to care about the theme anyway. It checks the color scheme or if not available, calculates the brightness of the window text color.

**Comment by Feichtmeier** [comment]
@jpnurmi 

if one wants to map flutter themes from yaru.dart to the corresponding gtk themes =)

If this still works then 👍  👍

**Comment by jpnurmi** [comment]
The Flutter engine patch is only for watching color scheme changes so that Flutter can correctly choose between `MaterialApp.theme` and `MaterialApp.darkTheme` when using the default "system" theme mode.

**Comment by jpnurmi** [comment]
Dark theme detection was fixed in the Flutter engine:
- https://github.com/flutter/engine/pull/33100 (not yet in stable)

Yaru.dart is now able to detect the appropriate variant:
- https://github.com/ubuntu/yaru.dart/pull/181 (not yet published?)

**Comment by Feichtmeier** [comment]
Uploaded 0.3.3 with your theme change :)
