### ISSUE TITLE
Contribution Guide!

### ISSUE THREAD

**Issue by ArishSultan** [canonical/ubuntu-desktop-installer#8]
Hi, I want to contribute to this project, is there any guide or a roadmap?

**Comment by kenvandine** [comment]
Right now the designs aren't in a public place, we'll work to get them published in a place that makes it easier to collaborate. Your contributions are welcome, and appreciated, just give us a little time to get prepared.

**Comment by iapicca** [comment]
@kenvandine 
I'd like to sign the [cla](https://ubuntu.com/legal/contributors/agreement) but I'm not sure
what to insert at `Please add the Canonical Project Manager or contact`

**Comment by kenvandine** [comment]
> @kenvandine
> I'd like to sign the [cla](https://ubuntu.com/legal/contributors/agreement) but I'm not sure
> what to insert at `Please add the Canonical Project Manager or contact`

You can reference me as your contact.  Thanks!

**Comment by ArishSultan** [comment]
The UI designs provided in the latest issues (all issues marked as specification).

Are those final or still being worked on? if yes than, when will the development start?

**Comment by MarcusTomlinson** [comment]
@ArishSultan those designs may be tweaked a bit here and there, but for the most part they are final yes. Development has started.

**Comment by ArishSultan** [comment]
Is there anything that i can work on?

**Comment by oSoMoN** [comment]
I added contributor guidelines in https://github.com/canonical/ubuntu-desktop-installer/pull/60.

**Comment by oSoMoN** [comment]
> Is there anything that i can work on?

To answer your question Arish, yes, there's a lot that you can work on, contributions very welcome!
UI and UX specifications are published as [Github issues](https://github.com/canonical/ubuntu-desktop-installer/issues?q=is%3Aissue+label%3Aspecification+sort%3Acreated-asc). Any specification issue without an assignee is up for grabs, if you start work on one of them please make sure to comment on the issue to say so, a project administrator will assign it to you.

**Comment by oSoMoN** [comment]
[Contributor guidelines](https://github.com/canonical/ubuntu-desktop-installer/blob/main/CONTRIBUTING.md) are now merged.
