### ISSUE TITLE
Hungarian language ubuntu-desktop-installer

### ISSUE THREAD

**Issue by AntoszHUN** [canonical/ubuntu-desktop-installer#809]
Hi! Someone started translating ubuntu-desktop-installer to Hungarian. I continued this yesterday on the page below.

https://hosted.weblate.org/projects/ubuntu-desktop-installer/#languages

The Weblate site is now closed for maintenance. I'll finish as soon as it's available. Will anyone be able to unite?

**Comment by jpnurmi** [comment]
Hi, thanks for contributing! The process is semi-automatic in the way that Weblate automatically opens a PR once a day (e.g. [yesterday](https://github.com/canonical/ubuntu-desktop-installer/pull/802)) that one of us will merge after the CI has passed.
