### ISSUE TITLE
snapd repeatedly interrupts Install Ubuntu to deploy Firefox to LiveCD desktop in install mode

### ISSUE THREAD

**Issue by c13-github** [canonical/ubuntu-desktop-installer#815]
Environment:
Jammy amd64 2022-03-29 daily live on DVD
AMD FM2+ (Lllano) A10-7850K 3.4 GHz stock
ASUS Crossblade Ranger FM2+
4GB DDR3-1300 RAM
No internet connection

Scenario:
Boot LiveCD in oem install mode

Result expected:
Ubuntu 22.04 will load in LiveCD mode
Install Ubuntu 22.04 LTS application will start and then complete installation of OS as requested. Show details will show all activity.

Result encountered:
Install Ubuntu 22.04 LTS starts very slowly as other LiveCD activity appears to take precedence
Show details reveals that Ubuntu 22.04  installer is continuously interrupted by snapd attempting to deploy Firefox.  systemd will then deactivate. snapd will reload. Progress bar appears to show that the step "Copying files" is progressing extremely slowly
One this particular system, Install Ubuntu has been observed running over 2 hrs without completing

**Comment by c13-github** [comment]
Restarting the LiveCD gives these clues in the console before Gnome desktop is displayed

[FAILED] Failed to start Modem Manager.
[FAILED] Failed to start Snap Daemon.for details. failed at package install time.....
[FAILED] Failed to start Ubuntu live CD installer

**Comment by c13-github** [comment]
Observing the LiveCD boot to advance to the Gnome desktop albeit with intensive DVD seek activity, I was able to open a virtual console. The process for snapd was ID 2710 running as root.

kill -9 2710 stopped the process. It was than respawned shortly after.

**Comment by c13-github** [comment]
Issued the below sequence in the new virtual console:

sudo systemctl disable snapd service
top # identify the snapd respawned process
sudo kill -9 'pid_of_snapd"
sudo systemctl stop snapd service
#receive error about being unable to stop snapd service

The disc-seeking behaviour slowly finally and fully stopped. In my main graphical console I had crashed with the apropos 'Aw Snap.." graphic. The Desktop recovered shortly after and took me to the login prompt for which I used the known ID.

I will now attempt to start the ubuntu-installer from the Desktop.

**Comment by c13-github** [comment]
The minimal installation choice with the options:

ZFS
Download updates

completed on this hardware in approximately 40 minutes after this intervention using the Live DVD.

I have established anecdotally that snapd imay be racing the desktop installer with continuously respawning snap daemons trying to install desktop packages in LiveCD mode, after the user starts the desktop installer to install Ubuntu 22.04.

The Copying Files step of the installation is unable to take precedence over the daemon and progress is greatly slowed.

The workaround is to disable snapd in the LiveCD session, logout and log back in the complete the installation as desired.

**Comment by jpnurmi** [comment]
Thank you for the bug report but I'm afraid it ended up in the wrong place. This repository is for developing the new desktop installer. The legacy installer in Jammy is called Ubiquity: https://launchpad.net/ubuntu/+source/ubiquity
