### ISSUE TITLE
Should copy the accessibility configuration to the target

### ISSUE THREAD

**Issue by seb128** [canonical/ubuntu-desktop-installer#830]
If the user enable some accessibility option during the installation those should also be enabled on the target system

The current installer does the copy using this script
https://git.launchpad.net/casper/tree/ubiquity-hooks/30accessibility

**Comment by jpnurmi** [comment]
It could be reasonable to make the accessibility menu visible by default in the live session.

**Comment by seb128** [comment]
Yes, it is in the 'install only' session from ubiquity so makes sense to do the same with the new installer

**Comment by jpnurmi** [comment]
Fixed by
- https://github.com/canonical/ubuntu-desktop-installer/pull/1058
