### ISSUE TITLE
Is Ubuntu going to switch to the new installer ?

### ISSUE THREAD

**Issue by om26er** [canonical/ubuntu-desktop-installer#836]
Great decision to not make the move in 22.04 but I wonder if Ubuntu still plans to move to the flutter based installer ?

**Comment by bittin** [comment]
@seb128 said on IRC some weeks ago, the plan is for 22.10 instead

**Comment by seb128** [comment]
Yes, that's the plan, the issue tracker isn't the right place for questions though

**Comment by bittin** [comment]
not @seb128 but the roadmap for now is 23.04 i think @Sebastian2023
