### ISSUE TITLE
Screen ? - Choose your look

### ISSUE THREAD

**Issue by madsrh** [canonical/ubuntu-desktop-installer#84]
Everybody loves the "new" settings [option where the user can switch between](https://cdn.allthings.how/wp-content/uploads/2020/04/allthings.how-how-to-enable-dark-mode-in-ubuntu-20-04-image.png) the default, light or dark theme.

I think it would be great if this option was presented to the user during the install.

![installer-theme-mockup](https://user-images.githubusercontent.com/3986894/117210811-774d9580-adf8-11eb-86af-bf7733102124.jpg)

**Comment by oSoMoN** [comment]
@long-chung what do you think of the suggestion?

**Comment by long-chung** [comment]
@oSoMoN Looks great

**Comment by oSoMoN** [comment]
Where in the sequence of screens should this go?

**Comment by long-chung** [comment]
I think the step before the installation slides/copying files would make the most sense, unless anybody has a different opinion?

**Comment by lyrebird-sound-cloning-system** [comment]
Pop OS does a post setup after restarting the computer. This kind of personalization settings fits better in a OOBE instead of in the initial installation.

**Comment by elbeicktalat** [comment]
@long-chung I think this page should be appear after choosing the installations type to show the theme on the installer.

**Comment by madsrh** [comment]
Just a quick reminder that this screen needs to be updated with the [recent changes to the Yaru theme](https://github.com/ubuntu/yaru/pull/2922) (only light and dark theme options now).

As you know, there's more changes coming and new preview thumbs from Wayne is needed (same as found in [GCC](https://gitlab.gnome.org/Community/Ubuntu/gnome-control-center/uploads/a346954476a1f0f74f710fa687ce6176/current.png)).

**Comment by Feichtmeier** [comment]
@oSoMoN I would like to work on this :)

**Comment by oSoMoN** [comment]
All yours @Feichtmeier !

**Comment by elbeicktalat** [comment]
Hi there,
I'm not sure about the radio box, I believe it will be more beautiful if you made it with cards like the installation type page #27, also we have to discuss about the title is it really necessary? 
What do you think ?

**Comment by madsrh** [comment]
Good idea @elbeicktalat. I think it would look better without the radio buttons 😅 
Is this possible @Feichtmeier ?

**Comment by Muqtxdir** [comment]
Hi, 
> Looking at the screenshot in the PR, I would say the thumbs should be bigger.
Is this possible @Feichtmeier ?

For [GCC MR](https://code.launchpad.net/~muqtxdir-m/ubuntu/+source/gnome-control-center/+git/gnome-control-center/+ref/applied/ubuntu/impish) on launchpad, I used the theme-previews at **270x200** px, Attached below is a zip file containig those two SVGs
📎: [theme-previews.zip](https://github.com/canonical/ubuntu-desktop-installer/files/6757757/theme-previews.zip)

**Comment by Feichtmeier** [comment]
I currently they are use the big images and are scaled down to 1/5 of the screen

**Comment by Feichtmeier** [comment]
@madsrh @elbeicktalat and whoelse has an opinion on that, I used @jpnurmi 's OptionCard - is this better?

![Peek 2021-07-03 11-06](https://user-images.githubusercontent.com/15329494/124349345-dbb98500-dbee-11eb-94e3-8649d7fd37b1.gif)

**Comment by madsrh** [comment]
Much better @Feichtmeier 
I love the Simon and Garfunkel reference (the word _darkness_ shouldn't be capitalized)

**Comment by Feichtmeier** [comment]
![grafik](https://user-images.githubusercontent.com/15329494/124349517-b11bfc00-dbef-11eb-9b00-4cb90a30b326.png)
@madsrh ?

**Comment by madsrh** [comment]
Bigger isn't always better BUT is there any chance that the thumbs could be bigger and the also bigger optioncards? Like on page #27?

https://user-images.githubusercontent.com/10974330/110313110-47eff780-8006-11eb-93fd-3d1379939d36.png

**Comment by Feichtmeier** [comment]
@madsrh I don't know. I have a 2,5k screen and the window is already scaled a little bit bigger than on a full hd screen. When the window changes this, the stuff looks like this:

![Peek 2021-07-03 11-35](https://user-images.githubusercontent.com/15329494/124350094-e5dd8280-dbf2-11eb-9b51-b1f91edc98e4.gif)

**Comment by elbeicktalat** [comment]
@Feichtmeier For me is much better than before, also I think if you increase the example size I mean the image, will be more better.

**Comment by elbeicktalat** [comment]
I think the space between the cards is so small, I don't know which is better space around or evenly. 
For sure not space between specialy when there is only 2 cards.

**Comment by jpnurmi** [comment]
> I think the space between the cards is so small

:+1: How about the same as on the "try or install page"?

> I used @jpnurmi 's OptionCard

No no, the credits for that one belong to Olivier! :)

**Comment by Feichtmeier** [comment]
![Peek 2021-07-03 14-17](https://user-images.githubusercontent.com/15329494/124353889-83dc4780-dc09-11eb-90fb-147ec94a64d1.gif)

?

**Comment by madsrh** [comment]
Okay @Feichtmeier I think I've figured out how to explain what I'm seeing. When going through the install screens the cards most have same size in every screen. So for this screen the cards should IMHO have the same size as used on page 27.
You get the idea:

![image](https://user-images.githubusercontent.com/3986894/124368079-82d50580-dc5d-11eb-99d6-61b7c068943d.png)

-

![image](https://user-images.githubusercontent.com/3986894/124368284-fed04d00-dc5f-11eb-904a-6f0df6cdfcd8.png)

WDYT?

**Comment by Feichtmeier** [comment]
@madsrh good idea

It would be cool to make OptionCards behave and look equal everywhere. 

Also @jpnurmi and me seemed to agree that we could maybe change the bg color of the card instead of the elevation on selection?
Like this (sorry for the wrong app, but same page)
![Peek 2021-07-04 14-55](https://user-images.githubusercontent.com/15329494/124385869-f156a980-dcd7-11eb-8ecf-c42f4b8e105f.gif)

**Comment by jpnurmi** [comment]
The highlight looks a bit strong. 🙂 I recall you mentioned somewhere just changing the shadow color. Did you try how it would look that way?

**Comment by Feichtmeier** [comment]
> The highlight looks a bit strong. slightly_smiling_face I recall you mentioned somewhere just changing the shadow color. Did you try how it would look that way?

Yes but the shadowColor looks a bit weird:
![wip](https://user-images.githubusercontent.com/15329494/124386456-cf125b00-dcda-11eb-941c-4b2c8e5e92e2.gif)

Maybe with opacity changing?
![wip](https://user-images.githubusercontent.com/15329494/124386499-0c76e880-dcdb-11eb-9134-24ad5ce2335c.gif)

**Comment by jpnurmi** [comment]
Agreed, the colored shadow doesn't look too good. :) What about a flat card with a highlighted border?

![image](https://user-images.githubusercontent.com/140617/124387764-0b948580-dce0-11eb-9949-ea98b0c18f25.png)

Sorry for the colors and the outline is also too thick. It's just a quick Gimped version of the elevation illustration at https://material.io/components/cards#behavior

**Comment by Feichtmeier** [comment]
![wip](https://user-images.githubusercontent.com/15329494/124388287-9fffe780-dce2-11eb-9399-d36b2fc277f6.gif)

Like this? Or with a reduced primary color?

**Comment by jpnurmi** [comment]
I was thinking an entirely flat card with a 1px accent color outline. ☺️

**Comment by Feichtmeier** [comment]
> I was thinking an entirely flat card with a 1px accent color outline. relaxed

![wip](https://user-images.githubusercontent.com/15329494/124389459-772e2100-dce7-11eb-8190-a19a6879eea2.gif)

Like this?

**Comment by jpnurmi** [comment]
Sorry for these short and dull comments. :smile: What if you keep elevation for unselected cards? Making the selected one flat visualizes that the card has been toggled down on the surface.

**Comment by madsrh** [comment]
I'm really not a fan of orange text but perhaps this will look better with the new accent color 🙈

The flat cards look good and are also in line with the mockups from the design team (IDK how accurate they are)

**Comment by Feichtmeier** [comment]
@madsrh :) I live it, but I agree that it is a bit aggressive

@jpnurmi like this?
![wip](https://user-images.githubusercontent.com/15329494/124391080-202c4a00-dcef-11eb-8854-eded715302fc.gif)

**Comment by jpnurmi** [comment]
I wish the orange text had more contrast against the dark background, but that's a different discussion. From the options so far, the last two are my favorites. :+1:

**Comment by Feichtmeier** [comment]
> I wish the orange text had more contrast against the dark background, but that's a different discussion. From the options so far, the last two are my favorites. +1

I plan to adapt the dark yaru flutter theme to the dark yaru gtk theme, which would make the color darker and thus the contrast higher

**Comment by Feichtmeier** [comment]
@long-chung sorry for the confusion about what issue is what.

Here is a gif of the things we have been discussing:

- different optioncard
- flat AppBar

if you agree on this I put it in my PR
![ok](https://user-images.githubusercontent.com/15329494/124568310-11f04200-de45-11eb-8d8b-b65361b3a4f7.gif)

**Comment by long-chung** [comment]
@Feichtmeier Thanks for clarifying. Looks good, +1 from me.

**Comment by oSoMoN** [comment]
> I love the Simon and Garfunkel reference heartsgrinning (the word _darkness_ shouldn't be capitalized)

While I also appreciate the reference to "the sound of silence", I wonder if it's really appropriate. People who don't get the reference might be confused. @long-chung can you please comment?

**Comment by oSoMoN** [comment]
Also, this reference makes the work of translators quite hard.

**Comment by Feichtmeier** [comment]
Sure thing I am not really attached to it :) Was just a middle long sentence that somehow fitted in there 👍 🕶️  💡

**Comment by waynecrosby** [comment]
@Feichtmeier I really like the animation transitions but I'm not sure the orange text is working and it isn't explicitly obvious which selection you have made. I would suggest just using white and dark grey text and just use the orange to outline the box. Below are a couple of examples with the text and visual knocked back (when not selected) and a small shadow to emphasise your choice. There is also a text update but I'm not sure it's better than what we have, let me know what you think?
![Dark](https://user-images.githubusercontent.com/42238722/124945275-e8cadf80-e005-11eb-93af-1de6d841d5f4.png)
![Light](https://user-images.githubusercontent.com/42238722/124945285-ea94a300-e005-11eb-985d-73b7039c7081.png)
![screens](https://user-images.githubusercontent.com/42238722/124945302-eec0c080-e005-11eb-8869-8ee6602c4aca.gif)
Text change?
![Dark-text-change](https://user-images.githubusercontent.com/42238722/124945595-347d8900-e006-11eb-95a9-af34340f5aef.png)

**Comment by Feichtmeier** [comment]
@waynecrosby alright ! WIll do - thanks for the feedback :)
