### ISSUE TITLE
New WSL Slide Show and OOBE integration

### ISSUE THREAD

**Issue by cnihelton** [canonical/ubuntu-desktop-installer#949]
I'm opening this issue aiming to get a consensus on the design of the new WSL OOBE slide show and its integration  with the setup wizard as we port the OOBE to Windowsbefore pushing any code.

The context is briefly described in [this design brief](https://docs.google.com/document/d/10JOcbWoncdyz9V4gnMGX3OwXK4VdnMQO484j6CvE13g/preview#) and it was agreed in a design team meeting that we'd invoke them to review any design change proposals instead of requesting any mockups since we anticipated very few details changed in this step.

Here is the old experience (with the slide show running as a Windows application and the OOBE as a Linux app rendered thru WSLg):

https://user-images.githubusercontent.com/11138291/175563924-52559da1-11e2-47a4-8f78-c6201f10a4bc.mp4

And here are both pieces integrated as a single application.

https://user-images.githubusercontent.com/11138291/175563943-6a9bc55f-3aed-470e-bc2e-64425286bdf4.mp4

I am requesting evaluation of:
1. The slide show design (made compatible with the Ubuntu Desktop Installer) and
2. Its integration with the OOBE as a single app (transitioning as part of the same wizard)

@elioqoshi could you give us your evaluation on those topics?

**Comment by jpnurmi** [comment]
For what it's worth, the installation slides are on a normal page in the desktop installer. Entering and leaving the installation slides shows the same transitions as any other page.

**Comment by CarlosNihelton** [comment]
One detail that I forgot to mention that must be considered is that the progress indicator might be better represented by a spinner I'm this use case, since it's value remains unknown until completion, this we may consider preserving it from the previous design.

**Comment by CarlosNihelton** [comment]
Here is the same (proposed) design running on Windows:

https://user-images.githubusercontent.com/11138291/175923276-81d97a10-b069-4bfc-a96d-277b5c2e2f36.mp4

**Comment by CarlosNihelton** [comment]
And here the spinner version (instead of the linear progress indicator):

![image](https://user-images.githubusercontent.com/11138291/175968924-9b45a5b3-fbde-4e00-911f-b850d4925592.png)
